### ISSUE TITLE
R2S中的minimal固件的更新源不可用

### ISSUE THREAD

**Issue by ForestL18** [klever1988/nanopi-openwrt#101]
R2S中的minimal固件的更新源不可用，opkg update就会提示下载失败，https://openwrt.proxy.ustclug.org/snapshots/targets/rockchip-rk3328网址无法打开，显示404，大佬们可以解决一下更新源的问题吗，谢谢啦😁

**Comment by klever1988** [comment]
#https://github.com/klever1988/nanopi-openwrt/issues/97
