### ISSUE TITLE
防火墙在页面点击的时候会卡好久，不知道是不是个例

### ISSUE THREAD

**Issue by ddzzfg** [klever1988/nanopi-openwrt#102]
另外：动态DNS 点击时候也会有一点卡顿，完全没有其他页面点击流畅

固件版本 ：OpenWrt R20.3.19 / LuCI Master (git-20.088.29068-cebe120) built by DYC

**Comment by klever1988** [comment]
绝对绝对绝对不是个例 因为argon主题就是这样子的  页面全部读取才会显示出来
你换成bootstrap主题 就会读取一条显示一条了
