### ISSUE TITLE
不能编译slim版本

### ISSUE THREAD

**Issue by chenyuyou** [klever1988/nanopi-openwrt#1022]
fork源码以后，编译了r2s和x86，没有编译出slim的版本的固件，不知道什么原因

**Comment by klever1988** [comment]
发一下你编译进程的链接才能帮你看吧

**Comment by chenyuyou** [comment]
> 

你发布的固件也没有slim版本的

**Comment by klever1988** [comment]
哦对 是我在actions脚本里关闭了forked项目的slim编译 (因为出来的东西都一样，关了给github省点电)
昨天发布的版本没有slim固件是因为编译出错了

**Comment by chenyuyou** [comment]
> 
怎么打开slim编译，不太熟悉这个编译流程

**Comment by klever1988** [comment]
我也不知道 我初学的
