### ISSUE TITLE
R2S 升级 HTTP请求失败 404

### ISSUE THREAD

**Issue by LarryLi-cn** [klever1988/nanopi-openwrt#1027]
请教一下,在线升级如下错误怎么办?
HTTP request sent, awaiting response... 404 NOT FOUND
2022-02-03 13:09:49 ERROR 404: NOT FOUND.

**Comment by chenyuyou** [comment]
新版本的没编译，等新版本编译成功

**Comment by LarryLi-cn** [comment]
> 新版本的没编译，等新版本编译成功
多谢!
