### ISSUE TITLE
为什么一直不修复，插usb网卡就重启扑街的bug

### ISSUE THREAD

**Issue by gngpp** [klever1988/nanopi-openwrt#1047]

**Comment by novicewu** [comment]
我也遇到这个问题，买的CF-811AC搭配R2S，只要一插上就死机。清大佬解决

**Comment by StevenWHU** [comment]
相同的问题

**Comment by koala9527** [comment]
相同的问题

**Comment by DrZBilibili** [comment]
究竟哪个老版本才能用Wifi啊？

**Comment by koala9527** [comment]
> 究竟哪个老版本才能用Wifi啊？

用骷髅的固件解决了

**Comment by DrZBilibili** [comment]
骷髅那个版本才行啊？试了几个固件都用不了5G

**Comment by koala9527** [comment]
> 骷髅那个版本才行啊？试了几个固件都用不了5G

确实5G的不行，试了很久，2.4G凑合用了，不想折腾了

**Comment by DrZBilibili** [comment]
主要看别人有用到AC 5G的频段  试了很多个固件都不行 只有Legcy模式下才能用Master模式 用5G自己就切到Client的 很蛋疼...
