### ISSUE TITLE
请问新版固件能不能默认加上hello world插件？

### ISSUE THREAD

**Issue by tianzhuwang07** [klever1988/nanopi-openwrt#1053]
passwall太复杂了，而且会接管DNS，导致出现莫名其妙的问题，只能停止使用插件。同时passwall进行局域网访问控制时也不好开启白名单。

我实际使用发现hello world相当简洁且稳定，功能也足够用，强烈建议新固件默认加上！

**Comment by zhdw22114632** [comment]
你可以自己安装啊，很好装的，不过hello world不能导入节点连接，不知道怎么处理，刚刚试过

**Comment by tianzhuwang07** [comment]
> 

2021年六月份固件自带的hello world，可以导入节点链接啊，我一直用的都是老固件。
目前的版本是1.23，重新编译插件吗？如果可以，能分享一下你的ipk文件给我吗？谢谢！

**Comment by tianzhuwang07** [comment]
目前passwall开启时，pc浏览器可以科学上网，但是手机不可以，尝试重启手机、开飞行模式也不行。

使用helloworld就没有问题。

**Comment by tianzhuwang07** [comment]
>
