### ISSUE TITLE
Docker版存在Docker Bug

### ISSUE THREAD

**Issue by ni7ht** [klever1988/nanopi-openwrt#1066]
这个docker有新手设置指南吗？感谢各位指点，其他的都有拉取镜像啥的设置这里没有找到啊。
![download](https://user-images.githubusercontent.com/37174285/158979353-f0ff7e65-6455-4a31-bd3d-c4bbfbb865d7.png)

**Comment by sdmkjz** [comment]
你这docker好像安装的不全 建议使用命令运行容器 图形化功能有限 不太好用

**Comment by momowind** [comment]
我和你一样，它这个固件的DOCKER有问题，后来无奈换的别家固件

**Comment by ni7ht** [comment]
> 你这docker好像安装的不全 建议使用命令运行容器 图形化功能有限 不太好用

我是直接下载的最新docker版，新手啊，不懂哪里有问题……

**Comment by ni7ht** [comment]
> 我和你一样，它这个固件的DOCKER有问题，后来无奈换的别家固件

是这样吗？我是下载的最新的2022-02-28发布的docker版固件，那我试试旧版固件看看。

**Comment by momowind** [comment]
> > 我和你一样，它这个固件的DOCKER有问题，后来无奈换的别家固件
> 
> 是这样吗？我是下载的最新的2022-02-28发布的docker版固件，那我试试旧版固件看看。

别家的docker都没问题

**Comment by ni7ht** [comment]
2022-04-07版本已解决
