### ISSUE TITLE
能否在minimal版本中加入Samba？

### ISSUE THREAD

**Issue by RadiumLei** [klever1988/nanopi-openwrt#107]
我尝试手动安装，但报错缺少依赖libatomic1，并且此依赖无法安装

<img width="1055" alt="截屏2020-03-31 下午1 39 33" src="https://user-images.githubusercontent.com/41866065/77991047-6e68d580-7355-11ea-9c81-4a3e33762d7d.png">

**Comment by NathanDai** [comment]
可以手动安装3.6版本 可以正常使用

**Comment by klever1988** [comment]
嗯用luci-app-samba就好了
