### ISSUE TITLE
2022/4/2更新后passwall和openclash都没了，而且ssrplus+还无法订阅

### ISSUE THREAD

**Issue by wanghuzhou** [klever1988/nanopi-openwrt#1075]
暂时回退到2022/4/1了

**Comment by InsOnYou** [comment]
安装OpenClash时，kmod依赖提示内核不对，导致安装失败。

**Comment by Biyanbin** [comment]
我甚至连安装都没办法 有别的版本可以先凑合用的吗？

**Comment by L1cardo** [comment]
最新版openclash需要安装kmod-inet-diag依赖
参考https://github.com/vernesong/OpenClash/issues/2215

**Comment by ppyohhh** [comment]
> 最新版openclash需要安装kmod-inet-diag依赖 参考[vernesong/OpenClash#2215](https://github.com/vernesong/OpenClash/issues/2215)

今天发布的43版本 重新装一下把

**Comment by wanghuzhou** [comment]
> 最新版openclash需要安装kmod-inet-diag依赖 参考[vernesong/OpenClash#2215](https://github.com/vernesong/OpenClash/issues/2215)

感谢大佬

**Comment by klever1988** [comment]
一个失误，导致opclash没有正确编译，现已修复~

**Comment by younasiqw** [comment]
4月版本没有smartdns，安装了luci 和 smartdns也不显示选项有大佬怎么解决吗

**Comment by klever1988** [comment]
passwall也已加回，帮忙测试一下正常不 @wanghuzhou

**Comment by wanghuzhou** [comment]
![image](https://user-images.githubusercontent.com/25093017/161700216-e9d2d652-158a-4a9f-9126-8a793a3dd38f.png)
![image](https://user-images.githubusercontent.com/25093017/161700357-f02684cb-a032-4df0-8960-44bfa7ce3926.png)
已正常使用，就是订阅页面有点ui问题，但不影响输入

本次升级我是通过下载img.gz上传 保留配置升级的，openclash无法使用，看日志发现Country.mmdb好像出问题了，删了之后重新启动自动下载新的就没问题了。
@klever1988
