### ISSUE TITLE
R2S的固件能添加subconverter-openwrt和samba4吗？

### ISSUE THREAD

**Issue by lam2888** [klever1988/nanopi-openwrt#1089]
r2s毕竟是usb2.0，samba3也太慢了！最好还是换为samba4,不过听说5.15内核原生不支持samba4，不知道有没有魔改5.15的内核支持samba4的？还有subconverter-openwrt最好也添加到源里，说不定openclash有天要用上。不好意思，才发现samba4己添加至源。不过卸载samba3，装上samba4,还是没见到samba4的使用界面。

**Comment by H-Tung** [comment]
@lam2888 你解决网页无samba4的问题了吗？我使用R5S-20221015-with-docker的固件还是能安装但网页端找不到
