### ISSUE TITLE
r1s h3 固件问题

### ISSUE THREAD

**Issue by wcwhqs** [klever1988/nanopi-openwrt#110]
当使用shadowsocksR plus+的时候，只能使用全局模式连通，其它模式不通。

**Comment by wcwhqs** [comment]
我已经测试了近期的好几个版本，都是一样的效果。启用ss plus+后，一开始都正常，国内外都可访问，没几分钟，突然国内就没法访问了。

**Comment by TheStoneOasis** [comment]
> 我已经测试了近期的好几个版本，都是一样的效果。启用ssr plus+后，一开始都正常，国内外都可访问，没几分钟，突然国内就没法访问了。

我之前有过类似情况，取消了所有ipv6服务后正常。

**Comment by klever1988** [comment]
检查一下自己的手机和电脑是不是设置了自定义dns，如有请改为自动获取

**Comment by wcwhqs** [comment]
> 检查一下自己的手机和电脑是不是设置了自定义dns，如有请改为自动获取

![FireShot Capture 003 - FriendlyWrt - Turbo ACC 网络加速 - LuCI - 192 168 77 1](https://user-images.githubusercontent.com/29819873/78021490-e8b14e00-7385-11ea-91d6-5187826bb7a8.png)
各种尝试、折腾，我把这个选择了就好了，有点神奇。：）
