### ISSUE TITLE
r2s 启用geoip 假死问题

### ISSUE THREAD

**Issue by kid-oh** [klever1988/nanopi-openwrt#1101]
ssrp和passwall分流中如果启用geoip的话长时间可能会出现假死的情况，就是路由和网络一切正常，但是局域网无法访问路由后台，只能通过远程访问后台来进行重启。不知道是固件问题还是插件问题（geoip数据庞大承受不了）

**Comment by klever1988** [comment]
哪个geoip你是说mosdns?

**Comment by kid-oh** [comment]
> 哪个geoip你是说mosdns?

不是mosdns，passwall-规则管理-中国IP段-geoip2-cn和ssrp-高级设置-国内IP-自定义。设置完并更新规则后可能几个小时或者十几个小时就崩掉了😂
