### ISSUE TITLE
R1s 固件的启动还是有些问题：

### ISSUE THREAD

**Issue by cat00fish** [klever1988/nanopi-openwrt#1102]
slim版可以启动，使用正常。但是如果增加分区，并挂载为overlay，重启后，就无法再启动了。

普通版启动后十几秒钟，系统就自动重启，并不停的重复这样，无法使用。

**Comment by cat00fish** [comment]
slim版，采用原地升级的方式自动扩容后，正常！

**Comment by klever1988** [comment]
胖版大概率是某个内核模块或者驱动不兼容，这个要排查起来就难咯
