### ISSUE TITLE
mosdns动态模式与“启动 UPnP 与 NAT-PMP 服务”冲突

### ISSUE THREAD

**Issue by kid-oh** [klever1988/nanopi-openwrt#1109]
之前一直排查不到什么原因，mosdns启用后只有tg能连上，其他都上不了网，今天把“启动 UPnP 与 NAT-PMP 服务”关了之后就好了，希望大佬在相关选项增加说明，谢谢！
<img width="530" alt="截屏2022-04-23 上午10 44 22" src="https://user-images.githubusercontent.com/30406467/164869054-43c6801d-d801-430c-b2ac-fada9ed153dd.png">

**Comment by klever1988** [comment]
这两个应该是没关系的啊，独立的进程。
昨天之前的版本存在geoip库没有预装导致mosdns不能启动，昨天修复了，再试试看，应该是无关的

**Comment by kid-oh** [comment]
> 这两个应该是没关系的啊，独立的进程。
> 昨天之前的版本存在geoip库没有预装导致mosdns不能启动，昨天修复了，再试试看，应该是无关的

噢噢 那可能刚好我更新新版就修复了，因为之前的版本确实不行
