### ISSUE TITLE
机型R2S，请问能否在固件中加入Docker CE？谢谢

### ISSUE THREAD

**Issue by djun** [klever1988/nanopi-openwrt#111]
你好，我的机型R2S，已刷入2020-3-25 release的Lienol版，需要用到Docker但发现其中没有包含Docker CE，
查资料 官方原版的FriendlyWrt好像是有包含Docker CE的（内核支持+“服务”中有Docker入口），使用Docker是需要在内核编译时加入与之相关的支持的，但研究不出如何修改workflow文件中的编译选项，

请问能否把FriendlyWrt原有的Docker CE加回Lienol版，或其他带passwall的版本？非常感谢！

参考：https://github.com/coolsnowwolf/lede/issues/3334

**Comment by klever1988** [comment]
加了内核参数  试试看能不能加入dockerman

**Comment by klever1988** [comment]
![image](https://user-images.githubusercontent.com/56048681/78041281-10fb7580-73a3-11ea-8a21-5173111ab9b7.png)
你要的docker来了

**Comment by djun** [comment]
非常感谢！

**Comment by djun** [comment]
> ![image](https://user-images.githubusercontent.com/56048681/78041281-10fb7580-73a3-11ea-8a21-5173111ab9b7.png)
> 你要的docker来了

[https://github.com/klever1988/nanopi-openwrt/releases/tag/R2S-Lienol-2020-03-31](url)
请问“自动发布 R2S-Lienol-2020-03-31”这个release已经加入的吗？还是需要再等新一天编译的版本？谢谢

**Comment by klever1988** [comment]
31加了的 我下来刷过了

**Comment by djun** [comment]
好的，先谢谢，晚上测试拉取运行镜像有没有什么问题

**Comment by maryjeck** [comment]
R2S的Minimal版本考虑增加么？？

**Comment by klever1988** [comment]
> R2S的Minimal版本考虑增加么？？

不考虑 因为docker引擎消耗大量资源

**Comment by sjqboss** [comment]
你的一系列R2S固件SSR+插件有bug，没有订阅功能，请检查。
