### ISSUE TITLE
0505版本R2S with Docker版在线升级中断，应该此版本扩容有问题

### ISSUE THREAD

**Issue by lam2888** [klever1988/nanopi-openwrt#1122]
如题，后来下载0505 r2s with docker的镜像，在ubuntu下输入命令sudo gzip -dc r2s-with-docker.img.gz | sudo dd of=/dev/sdb
，再通过gparted扩容也是报错误，0504 r2s docker版则没有这个问题。

刚刚在线升级了0506 r2s with docker的固件也是没问题。

**Comment by klever1988** [comment]
可能是github抽风 自动编译的固件上传不完整吧
