### ISSUE TITLE
R2S with Docker 0508版本在线升级卡在tar: write: Broken pipe

### ISSUE THREAD

**Issue by lam2888** [klever1988/nanopi-openwrt#1124]
r2s with docker 0508版本在线升级中，出现以下提示，然后就不动了。把内存卡插在读卡器上，sudo fsck.ext4 -y /dev/sdb1和sdb2,一定是要自动修复的。
root@OpenWrt:~# tar: write: Broken pipe

反正最后都是在线升级，卡tar: write: Broken pipe。

**Comment by klever1988** [comment]
![image](https://user-images.githubusercontent.com/56048681/167304572-358570fa-71f0-446c-ab10-3ffb468f6a49.png)


档案没有问题 写入中断可能是其他原因，网络吧
