### ISSUE TITLE
r2s with docker 0509版在线升级失败

### ISSUE THREAD

**Issue by lam2888** [klever1988/nanopi-openwrt#1127]
![2022-05-10_08-31-35](https://user-images.githubusercontent.com/17683972/167519891-7b789db4-ddfb-4eed-9fef-45a8ead430a1.png)
己经换了闪迪A2性能的TF卡，不可能空间不够，也用读卡器修复过TF卡。sudo fsck.ext4 -y /dev/sdb1和sdb2 还是在线升级失败。

**Comment by klever1988** [comment]
tmp分区占用过大，可能是某个插件占用的，升级时停掉不必要的插件再试

**Comment by lam2888** [comment]
> 

试过了，只留下passwall，还是不行。

**Comment by lam2888** [comment]
upg文件夹是干嘛的？tmp分区用的是不是tmpfs? 才850mb。
![2022-05-10_16-22-16](https://user-images.githubusercontent.com/17683972/167583706-978be25e-f313-43e6-81fb-aa1aeec84aa0.png)

**Comment by lam2888** [comment]
![2022-05-10_16-31-09](https://user-images.githubusercontent.com/17683972/167585082-d98a335b-4bda-47cf-a8a9-f36136d350bf.png)
tmp分区小，应该是编译默认分区小吧？tmpfs应该3倍于解压后的固件大小才对。

**Comment by lam2888** [comment]
![2022-05-10_16-39-18](https://user-images.githubusercontent.com/17683972/167586748-e07837a1-6a05-45bf-9ddc-79d3221f5344.png)
r2s 只有1G运行内存，tmpfs用的是运行内存吧？默认开启tmpfs都用了350mb，在线升级r2s docker 0509版解压用了650mb，1G运存的tmpfs就不够用了。

**Comment by lam2888** [comment]
![2022-05-13_08-55-32](https://user-images.githubusercontent.com/17683972/168190786-d2b2f469-d9b6-47ad-a033-ac5f3de0975e.png)
用了隔壁家00575的在线升级固件，升级r2s with docker版，则没有问题，唯一的缺点是刷完后，需要ssh登录reboot.
