### ISSUE TITLE
请问用您给的脚本更新是保留配置还是不保留配置？

### ISSUE THREAD

**Issue by Benjamin23333** [klever1988/nanopi-openwrt#113]
如题

**Comment by klever1988** [comment]
保留的

**Comment by Benjamin23333** [comment]
> 保留的

谢谢解答

**Comment by Benjamin23333** [comment]
> 保留的

那我还想问下，昨天我刷了minimal的看到ssr+，passwall，openclash都有，这三个插件切换的话是不是需要做什么比如重启防火墙的工作？

**Comment by yanjun42637** [comment]
请问下可否集成smartdns，感谢

**Comment by klever1988** [comment]
> 那我还想问下，昨天我刷了minimal的看到ssr+，passwall，openclash都有，这三个插件切换的话是不是需要做什么比如重启防火墙的工作？
不需要，只要启动其中一个的时候，确保另外两个是关闭的就可以了

**Comment by Benjamin23333** [comment]
> > 那我还想问下，昨天我刷了minimal的看到ssr+，passwall，openclash都有，这三个插件切换的话是不是需要做什么比如重启防火墙的工作？
> 
> 不需要，只要启动其中一个的时候，确保另外两个是关闭的就可以了

再次谢谢解答
