### ISSUE TITLE
升级时可以从web后台的“系统 ”=>"升级备份"=>"刷写新的固件"里面升级吗？

### ISSUE THREAD

**Issue by choicky** [klever1988/nanopi-openwrt#1132]
如题。

这固件我见Readme里面写着 `终端内在线升级方法` ，是不是只能 ssh 登录后升级？

我之前使用其他固件，那个固件是可以从升级时可以从web后台的“系统 ”=>"升级备份"=>"刷写新的固件"里面升级的。不知这固件能不能从web后端升级呢？

**Comment by sherdai63** [comment]
终端内在线升级方法：可以直接在"系统”=>“TTYD 终端”里升级，不需要第三方软件ssh登录升级。

**Comment by choicky** [comment]
@sherdai63 多谢指导。

另外，docker 版本的升级是否需要 `ver=-with-docker` 参数呢？ 我发现有些老 issue 说需要，但项目的 readme 没说。

**Comment by klever1988** [comment]
也可以的

**Comment by klever1988** [comment]
> @sherdai63 多谢指导。
> 
> 另外，docker 版本的升级是否需要 `ver=-with-docker` 参数呢？ 我发现有些老 issue 说需要，但项目的 readme 没说。

需要的
