### ISSUE TITLE
自编译找不到github actions构件输出处

### ISSUE THREAD

**Issue by kesongyuan** [klever1988/nanopi-openwrt#1144]
klever1988大佬，你自编译中写的github actions构件输出处我找不到，能指点一下吗

**Comment by alfchao** [comment]
https://github.com/klever1988/nanopi-openwrt/issues/705#issuecomment-874238200
但是下不了了,expired。

**Comment by doKill** [comment]
https://github.com/klever1988/nanopi-openwrt/actions/runs/2374742252
