### ISSUE TITLE
需要内置软件包kmod-usb-net-rndis及其依赖包

### ISSUE THREAD

**Issue by niukai** [klever1988/nanopi-openwrt#115]
你好，我需要使用安卓手机usb共享网络向R2S提供网络，我目前无法安装kmod-usb-net-rndis导致没识别我的华为手机无法先实现使用手机网络，希望添加kmod-usb-net-rndis和依赖包，谢谢。

**Comment by klever1988** [comment]
加入了

**Comment by niukai** [comment]
神速啊：）
