### ISSUE TITLE
这个zerospace 没看懂是干啥的

### ISSUE THREAD

**Issue by zhangguanzhang** [klever1988/nanopi-openwrt#1158]
```
cd lede/; pv /dev/zero > zerospace || true; sync; rm -f zerospace; cd -
```

**Comment by klever1988** [comment]
把写过数据的块填0，这样btrfs就可以进一步把镜像压缩变小。

**Comment by zhangguanzhang** [comment]
收到

**Comment by zhangguanzhang** [comment]
![image](https://user-images.githubusercontent.com/18641678/171671600-138db43c-89c2-4766-80b3-d384f6fae66f.png)
![image](https://user-images.githubusercontent.com/18641678/171671806-2e731bfc-f5d4-465d-97eb-5f856ec04b87.png)
另外咨询下，这个名字你是怎么搞的，我看了下你的yml和github action文档没看到那里能设置成不一样的

**Comment by klever1988** [comment]
event_type

https://github.com/klever1988/nanopi-openwrt/blob/4a0f7a67d75682cbdd54b7f563499653b9fe4b7b/.github/workflows/dispatch.yml#L16

https://gist.github.com/Daniel-ltw/552b90800b07c22e4a83dfa68ada6318

**Comment by zhangguanzhang** [comment]
感谢解答
