### ISSUE TITLE
需要内置包kmod-usb-net-cdc-ether；usb-modeswitch；kmod-usb-net-rndis；usbutils

### ISSUE THREAD

**Issue by niukai** [klever1988/nanopi-openwrt#117]
需要固件内置软件包：kmod-usb-net-cdc-ether；usb-modeswitch；kmod-usb-net-rndis；usbutils。他们有依赖，需要全都添加才行，谢谢：）

**Comment by klever1988** [comment]
kmod-usb-net-cdc-ether已添加，usbutils可以通过opkg安装，其他已有
