### ISSUE TITLE
Packages missing from update 2022-06-11

### ISSUE THREAD

**Issue by cryptou** [klever1988/nanopi-openwrt#1172]
Hi! Passwall seems to be missing from the new update for R4S (2022-06-11).
I tried the r4s and r4s-slim releases, as well as forking+building. Same issue.

**Comment by alexleungch** [comment]
r2s missed passwall too. Core 5.4 doesn't support the passwall plugin?

**Comment by klever1988** [comment]
it was brought back.

**Comment by cryptou** [comment]
Thanks for fixing it so quickly!
