### ISSUE TITLE
风扇温控问题

### ISSUE THREAD

**Issue by huahuaj** [klever1988/nanopi-openwrt#1188]
大佬您好：
     我下载了您编译的r4s.img这个固件，删除了系统中自带的风扇温控脚本，自己重新添加了一个，R4S重启之后我的温控脚本是起作用的，风扇会转，但是打不开openwrt的web页面，这是什么问题导致的呢？
我的温控脚本：
#!/bin/sh /etc/rc.common
START=21
start ( ) {
echo 0 > /sys/class/pwm/pwmchip1/export
echo 0 > /sys/class/pwm/pwmchip1/pwm0/enable
echo 50000 > /sys/class/pwm/pwmchip1/pwm0/period
echo 1 > /sys/class/pwm/pwmchip1/pwm0/enable
echo 49990 > /sys/class/pwm/pwmchip1/pwm0/duty_cycle; # 初始风扇不转
while true
do
temp=$(cat /sys/class/thermal/thermal_zone0/temp ) #获取 cpu 温度
if [ $temp -gt 45000 ] ; then # 温度高于 50 风扇开始转， 数值可修改
echo 30000 > /sys/class/pwm/pwmchip1/pwm0/duty_cycle;
elif [ $temp -le 40000 ] ; then # 温度低于 47 风扇停转， 数值可修改
echo 49990 > /sys/class/pwm/pwmchip1/pwm0/duty_cycle;
fi
sleep 1s; # 1 秒检测一次， 正常使用可以设置为 60s
done
}

**Comment by Mosys** [comment]
这个脚本就有问题，你吧这个脚本挂后台运行就好了。
![CD8ACB39-B1F4-4758-839F-0A1A5FB40962](https://user-images.githubusercontent.com/27868504/180919967-f322fb62-8fcb-428a-bbd2-4a9a6ef83351.jpeg)

**Comment by Lil-Gun** [comment]
> 这个脚本就有问题，你吧这个脚本挂后台运行就好了。 ![CD8ACB39-B1F4-4758-839F-0A1A5FB40962](https://user-images.githubusercontent.com/27868504/180919967-f322fb62-8fcb-428a-bbd2-4a9a6ef83351.jpeg)

感谢指导，看方法实测r5s也可用

**Comment by damoncoo** [comment]
> > 这个脚本就有问题，你吧这个脚本挂后台运行就好了。 ![CD8ACB39-B1F4-4758-839F-0A1A5FB40962](https://user-images.githubusercontent.com/27868504/180919967-f322fb62-8fcb-428a-bbd2-4a9a6ef83351.jpeg)
> 
> 感谢指导，看方法实测r5s也可用

请问你们的风扇都是怎么装的？ USB 还是？

**Comment by Mosys** [comment]
> > > 这个脚本就有问题，你吧这个脚本挂后台运行就好了。 ![CD8ACB39-B1F4-4758-839F-0A1A5FB40962](https://user-images.githubusercontent.com/27868504/180919967-f322fb62-8fcb-428a-bbd2-4a9a6ef83351.jpeg)
> > 
> > 
> > 感谢指导，看方法实测r5s也可用
> 
> 请问你们的风扇都是怎么装的？ USB 还是？

这个脚本该固件通用，记得把问题 close 掉吧

**Comment by huahuaj** [comment]
> 大佬您好： 我下载了您编译的r4s.img这个固件，删除了系统中自带的风扇温控脚本，自己重新添加了一个，R4S重启之后我的温控脚本是起作用的，风扇会转，但是打不开openwrt的web页面，这是什么问题导致的呢？ 我的温控脚本： #!/bin/sh /etc/rc.common START=21 start ( ) { echo 0 > /sys/class/pwm/pwmchip1/export echo 0 > /sys/class/pwm/pwmchip1/pwm0/enable echo 50000 > /sys/class/pwm/pwmchip1/pwm0/period echo 1 > /sys/class/pwm/pwmchip1/pwm0/enable echo 49990 > /sys/class/pwm/pwmchip1/pwm0/duty_cycle; # 初始风扇不转 while true do temp=$(cat /sys/class/thermal/thermal_zone0/temp ) #获取 cpu 温度 if [ $temp -gt 45000 ] ; then # 温度高于 50 风扇开始转， 数值可修改 echo 30000 > /sys/class/pwm/pwmchip1/pwm0/duty_cycle; elif [ $temp -le 40000 ] ; then # 温度低于 47 风扇停转， 数值可修改 echo 49990 > /sys/class/pwm/pwmchip1/pwm0/duty_cycle; fi sleep 1s; # 1 秒检测一次， 正常使用可以设置为 60s done }

**Comment by huahuaj** [comment]
>

**Comment by huahuaj** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "klever1988/nanopi-openwrt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月10日(星期四) 上午10:08
***@***.***&gt;;
抄送:&nbsp;"☞ ***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [klever1988/nanopi-openwrt] 风扇温控问题 (Issue #1188)





 
这个有文字版的吗。。

**Comment by Mosys** [comment]
1. 进入 /etc/init.d 查看是否有 fa-fancontrol 或者 pwm-fan 等包含fan字段的脚本，如果有选中删除。
2. 分别执行如下命令，逐行copy到命令行后回车即可；
    
    ```bash
    touch /etc/init.d/pwm-fan
    chmod 777 /etc/init.d/pwm-fan
    touch /usr/bin/pwm-fan.sh
    chmod 777 /usr/bin/pwm-fan.sh
    ```
    
3. 将以下内容完整 copy 到 /usr/bin/pwm-fan.sh 文件中
    
    ```bash
    #!/bin/sh
    echo 0 > /sys/class/pwm/pwmchip0/export
    echo 0 > /sys/class/pwm/pwmchip0/pwm0/enable
    echo 50000 > /sys/class/pwm/pwmchip0/pwm0/period
    echo 1 > /sys/class/pwm/pwmchip0/pwm0/enable
    echo 46990 > /sys/class/pwm/pwmchip0/pwm0/duty_cycle
    sleep 5
    echo 49990 > /sys/class/pwm/pwmchip0/pwm0/duty_cycle
    while true 
    do
        temp=$(cat /sys/class/thermal/thermal_zone0/temp ) #去掉了$旁的空格
        if [ $temp -gt 50000 ] ; then # 温度高于 50 风扇开始转，可修改，比如65000为65度；
            echo 30000 > /sys/class/pwm/pwmchip0/pwm0/duty_cycle;
        elif [ $temp -le 45000 ] ; then # 温度低于 45 风扇停转，可修改，比如55000为55度；
            echo 49990 > /sys/class/pwm/pwmchip0/pwm0/duty_cycle;
        fi #多加了fi
        sleep 30s; # 1s检测一次，正常使用设置为60s
    done
    ```
    
4. 将以下内容完整 copy 到 /etc/init.d/pwm-fan 文件中
    
    ```bash
    #!/bin/sh /etc/rc.common
    START=99
    start() {
        nohup /usr/bin/pwm-fan.sh &
    }
    ```
    
5. 登陆后台web管理界面，在【系统】--【启动项】--“启动脚本”下面能看到99号优先级名为pwm-fan的脚本，点击第二个【启动】按钮，风扇就开始转了
    
    ```bash
    /etc/init.d/pwm-fan enable
    ```
    
6. 测试程序
    
    运行 AES 跑分命令
    
    ```bash
    openssl speed -evp aes-256-gcm
    ```
    
    查看温度命令
    
    ```bash
    cat /sys/class/thermal/thermal_zone0/temp
    ```

**Comment by Mosys** [comment]
> 这个脚本就有问题，你吧这个脚本挂后台运行就好了。 ![CD8ACB39-B1F4-4758-839F-0A1A5FB40962](https://user-images.githubusercontent.com/27868504/180919967-f322fb62-8fcb-428a-bbd2-4a9a6ef83351.jpeg)

1. 进入 /etc/init.d 查看是否有 fa-fancontrol 或者 pwm-fan 等包含fan字段的脚本，如果有选中删除。
2. 分别执行如下命令，逐行copy到命令行后回车即可；
    
    ```bash
    touch /etc/init.d/pwm-fan
    chmod 777 /etc/init.d/pwm-fan
    touch /usr/bin/pwm-fan.sh
    chmod 777 /usr/bin/pwm-fan.sh
    ```
    
3. 将以下内容完整 copy 到 /usr/bin/pwm-fan.sh 文件中
    
    ```bash
    #!/bin/sh
    echo 0 > /sys/class/pwm/pwmchip0/export
    echo 0 > /sys/class/pwm/pwmchip0/pwm0/enable
    echo 50000 > /sys/class/pwm/pwmchip0/pwm0/period
    echo 1 > /sys/class/pwm/pwmchip0/pwm0/enable
    echo 46990 > /sys/class/pwm/pwmchip0/pwm0/duty_cycle
    sleep 5
    echo 49990 > /sys/class/pwm/pwmchip0/pwm0/duty_cycle
    while true 
    do
        temp=$(cat /sys/class/thermal/thermal_zone0/temp ) #去掉了$旁的空格
        if [ $temp -gt 50000 ] ; then # 温度高于 50 风扇开始转，可修改，比如65000为65度；
            echo 30000 > /sys/class/pwm/pwmchip0/pwm0/duty_cycle;
        elif [ $temp -le 45000 ] ; then # 温度低于 45 风扇停转，可修改，比如55000为55度；
            echo 49990 > /sys/class/pwm/pwmchip0/pwm0/duty_cycle;
        fi #多加了fi
        sleep 30s; # 1s检测一次，正常使用设置为60s
    done
    ```
    
4. 将以下内容完整 copy 到 /etc/init.d/pwm-fan 文件中
    
    ```bash
    #!/bin/sh /etc/rc.common
    START=99
    start() {
        nohup /usr/bin/pwm-fan.sh &
    }
    ```
    
5. 登陆后台web管理界面，在【系统】--【启动项】--“启动脚本”下面能看到99号优先级名为pwm-fan的脚本，点击第二个【启动】按钮，风扇就开始转了
    
    ```bash
    /etc/init.d/pwm-fan enable
    ```
    
6. 测试程序
    
    运行 AES 跑分命令
    
    ```bash
    openssl speed -evp aes-256-gcm
    ```
    
    查看温度命令
    
    ```bash
    cat /sys/class/thermal/thermal_zone0/temp
    ```
