### ISSUE TITLE
wireguard 空包 不能正确构建到image中

### ISSUE THREAD

**Issue by john5du** [klever1988/nanopi-openwrt#1189]
![image](https://user-images.githubusercontent.com/45614150/176984141-7fe8c0fa-ea87-4b81-a7f7-3cea9f581d12.png)
![image](https://user-images.githubusercontent.com/45614150/176891522-79b81096-3556-4da3-a171-b4b94da10ec8.png)

**Comment by trednx** [comment]
was the problem with wireguard solved? can smbd confirm that wireguard is working now?

**Comment by john5du** [comment]
> was the problem with wireguard solved? can smbd confirm that wireguard is working now?

还是不能用

**Comment by john5du** [comment]
已经能拉取到正确的包
