### ISSUE TITLE
请问usb无线网卡都支持哪些（除写明的8821cu）？

### ISSUE THREAD

**Issue by Benjamin23333** [klever1988/nanopi-openwrt#120]
我看到您的更新日志里写着支持8821cu，但是我在一个issues里看到您放出您测试用的usb网卡的京东链接，我点进去问商家，他说这个是8811cu，我就有点懵了，请问到底支持哪些usb网卡？

**Comment by klever1988** [comment]
comfast 811ac
搜这个就行了

**Comment by Benjamin23333** [comment]
> comfast 811ac
> 搜这个就行了
> 价格35
> ![image](https://user-images.githubusercontent.com/56048681/78133567-38a91700-7451-11ea-947f-7cf2c567e71a.png)

对对对，我看到您在某个issues里给的就是这个，但是我问客服，客服说这个是8811cu，我就有点搞不明白了，还有5G无线54M的bug修了吗？

**Comment by klever1988** [comment]
那是客服搞不清楚
可以上到150Mbps

**Comment by Benjamin23333** [comment]
> 那是客服搞不清楚
> 可以上到150Mbps

谢谢

**Comment by Benjamin23333** [comment]
> 那是客服搞不清楚
> 可以上到150Mbps

对了，插上之后刷上固件就有无线信号么？还是要手动设置添加？

**Comment by klever1988** [comment]
插上就自动设置ap了
