### ISSUE TITLE
更新后 unblockmusic 貌似失效了

### ISSUE THREAD

**Issue by NianyiYang** [klever1988/nanopi-openwrt#1213]
没更新之前一直能用的，前天更了下，网易云直接无法连接网络了，关闭 unblockmusic 插件后马上就能播放了...

**Comment by Thomaszzz11** [comment]
网易云去网上下载一个旧版本就可以了

**Comment by NianyiYang** [comment]
> 网易云去网上下载一个旧版本就可以了

你是说网易云本体更新了后把插件屏蔽了？这倒有可能

**Comment by NianyiYang** [comment]
旧版用了几天，现在也不能用了。。。周董再见了hhh
