### ISSUE TITLE
请问如何编译固件 x86无限重启 

### ISSUE THREAD

**Issue by boyu899** [klever1988/nanopi-openwrt#1223]

**Comment by ZJY2001** [comment]
同求，我也碰到一样的问题，换4月份的古见就好，新固件在pve上无限重启

**Comment by boyu899** [comment]
kmod-fast-classifier=y  改成n
参考的另一个议题 成功进去 修改了common.seed和x86的seed（如有）

仅供参考 还没有大神给具体原因

**Comment by boyu899** [comment]
也不知道kmod-fast-classifier=y  这个是什么  不配置会不会对系统某些功能有影响 配置了又冲突无限重启 请大神指教

**Comment by boyu899** [comment]
> No description provided.
