### ISSUE TITLE
20221119版本adguard home后台无法登入

### ISSUE THREAD

**Issue by amwsuhje** [klever1988/nanopi-openwrt#1257]
机型:R4S
ADGUARD HOME正常运行，进入网页管理，用户名密码正确，点登入，无跳转，无提示，删除核心重新下载安装，故障依旧

**Comment by klever1988** [comment]
![image](https://user-images.githubusercontent.com/56048681/202887368-30ec8b26-8b3d-4af7-b110-8931e3b8c6a2.png)

没有问题啊

**Comment by amwsuhje** [comment]
可能是浏览器问题了，刚刚看了回复换了个浏览器可以进入了，谢谢，我关闭吧
