### ISSUE TITLE
我就是在弱电箱里测试的r2s测试光猫100M，用另外的软路由测试，光猫就是1000M，其他什么都没变

### ISSUE THREAD

**Issue by Nightfallcc** [klever1988/nanopi-openwrt#129]

**Comment by klever1988** [comment]
换条网线

**Comment by Nightfallcc** [comment]
线在墙里，弱电箱离光猫10M，8根线通。 其他3个路由都是1000M。

**Comment by klever1988** [comment]
那就是r2s的硬件问题了，你可以试试其他固件

**Comment by Nightfallcc** [comment]
所有固件都刷过了，现在只能当旁路由。




| |
格兰亚多
|
|
邮箱：gelanyaduo@163.com
|

签名由 网易邮箱大师 定制

在2020年04月02日 20:34，klever1988 写道：

那就是r2s的硬件问题了，你可以试试其他固件

**Comment by klever1988** [comment]
网线不好 换线材不便的话 给两头的水晶头换个高级一些的试试看

**Comment by Nightfallcc** [comment]
所有接头都换了一遍，都换了绿联的6类。能想的，都搞了一遍。就是墙里的没办法。🙏




| |
格兰亚多
|
|
邮箱：gelanyaduo@163.com
|

签名由 网易邮箱大师 定制

在2020年04月02日 20:47，klever1988 写道：

网线不好 换线材不便的话 给两头的水晶头换个高级一些的试试看
