### ISSUE TITLE
升级4月2日minimal 无法连接路由器

### ISSUE THREAD

**Issue by forestslin** [klever1988/nanopi-openwrt#130]
反馈个问题，通过代码升级4月2日minimal 无法连接路由器，lan口灯不亮，无法上网
重新刷tf卡，问题也是一样。
不知道是个例还是都存在的问题

**Comment by klever1988** [comment]
我刚更新 正常启动 没有发现异常

**Comment by Nightfallcc** [comment]
我也是，SSH更新后，LAN没反应。重新写入也不行，换固件OK了。

**Comment by NEFever** [comment]
我也是刷了，lan没反应

**Comment by xuealan** [comment]
4月2日R2S刷了两个大的版本 LAN口都没反应 55555

**Comment by coderafei** [comment]
遇到相同情况，lan口灯都不亮了

**Comment by LearningChanging** [comment]
遇到相同情况，lan口灯都不亮了

**Comment by klever1988** [comment]
https://github.com/friendlyarm/uboot-rockchip/commit/e19137c754437403e8d077083ba51ea7b50a7e5f

应该是友善昨天改uboot没有测试

**Comment by klever1988** [comment]
修复了
