### ISSUE TITLE
minimal系统保存BUG

### ISSUE THREAD

**Issue by 296475202** [klever1988/nanopi-openwrt#138]
Minimal系统选项修改主机名和管理密码重启后会自动恢复成默认主机名和默认密码，只有拔电重启才会保存到。

**Comment by klever1988** [comment]
修改密码不拔电重启没有重现你的问题

**Comment by 296475202** [comment]
> 修改密码不拔电重启没有重现你的问题


那可能是SD咔的问题，不是系统问题🤔
