### ISSUE TITLE
Lienol固件，希望有mount, lsusb, locate

### ISSUE THREAD

**Issue by potato1992** [klever1988/nanopi-openwrt#141]
大佬能不能加入mount luci界面，我想挂载移动硬盘。还有一些基础的命令能不能加进来，比方说lsusb, updatedb(配合locate命令找东西很方便)

**Comment by klever1988** [comment]
https://github.com/Lienol/openwrt

请Lienol大佬收录diskman插件

**Comment by w261643358** [comment]
https://github.com/w261643358/lede/actions/runs/220383345  大佬帮看看小弟编译的X86-64固件我看集成了docker
但是我想要的passwall没有发现，ssrplus我不想要想删除却没有删除，

**Comment by klever1988** [comment]
https://drive.google.com/folderview?id=1PsS3c0P7a4A4KY8plQg4Fla8ZI-PGBb1

**Comment by klever1988** [comment]
你喜欢passwall的话直接编译lienol分支是最好的了

https://github.com/Lienol/openwrt

我自己弄了一个你可以试试看

https://github.com/klever1988/lienol-openwrt-autobuild/actions

**Comment by klever1988** [comment]
findutils-find
