### ISSUE TITLE
还需要大神帮忙在 R1S-Lienol 中增加docker

### ISSUE THREAD

**Issue by GeekerXu** [klever1988/nanopi-openwrt#15]
还需要大神帮忙在 R1S-Lienol 中增加docker。
我自己尝试用您的r1s_lienol.yml，在我的库里增加luci-app-dockerman后进行编译，编译成功了，并生成固件，但是刷入r1s后打开docker，页面显示
This page contains the following errors:
error on line 250 at column 57: attributes construct error
Below is a rendering of the page up to the first error.
同时编译的luci-app-adbyby-plus，也出现了类似问题：
This page contains the following errors:
error on line 424 at column 25: AttValue: " or ' expected
Below is a rendering of the page up to the first error.

**Comment by klever1988** [comment]
lienol最近不知道在搞什么 luci docker暂时加不上的 再等等吧

**Comment by GeekerXu** [comment]
好的 谢谢
