### ISSUE TITLE
云解锁网易云音乐能换成解锁网易云灰色歌曲么

### ISSUE THREAD

**Issue by sunshinegw** [klever1988/nanopi-openwrt#16]
两个版本都用过，感觉云解锁网易云音乐速度慢，而且替换后的灰色歌曲音乐版本不对，不是同一个人唱的了，没有解锁网易云灰色歌曲体验好。

**Comment by klever1988** [comment]
可以  我都加上吧

**Comment by sunshinegw** [comment]
多谢多谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "klever1988"<notifications@github.com&gt;; 
发送时间: 2020年2月29日(星期六) 晚上7:11
收件人: "klever1988/nanopi-openwrt"<nanopi-openwrt@noreply.github.com&gt;; 
抄送: "心若向阳"<1459366899@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [klever1988/nanopi-openwrt] 云解锁网易云音乐能换成解锁网易云灰色歌曲么 (#16)




可以  我都加上吧

**Comment by klever1988** [comment]
已替换
