### ISSUE TITLE
r2s固件，实测无法通过局域网使用域名加端口的方式访问

### ISSUE THREAD

**Issue by lsl330** [klever1988/nanopi-openwrt#17]

**Comment by lsl330** [comment]
测试了r2s的好多固件都有这问题的存在，可以方便排查下原因么？

我看大雕的回复是“和 NET NS 内核选项有关，Docker 会自动选上这个”
不知道是不是因为编译时docker的原因导致这问题？

**Comment by klever1988** [comment]
> 测试了r2s的好多固件都有这问题的存在，可以方便排查下原因么？
> 
> 我看大雕的回复是“和 NET NS 内核选项有关，Docker 会自动选上这个”
> 不知道是不是因为编译时docker的原因导致这问题？

![image](https://user-images.githubusercontent.com/56048681/75604947-e48cd900-5b18-11ea-991e-6478fde3846d.png)
是这样？

**Comment by lsl330** [comment]
是的，但我测试智能连接路由的局域网ip（192.168.2.1），nas的就连接不上（192.168.2.3）

**Comment by lsl330** [comment]
又测试了一下，Lienol版固件可以连上，lean的固件还是不行

**Comment by klever1988** [comment]
> 又测试了一下，Lienol版固件可以连上，lean的固件还是不行

这个 我目前没有交换机 没有测试条件了
你可以尝试在 http://friendlywrt/cgi-bin/luci/admin/network/hosts 添加一条映射试试看

**Comment by lsl330** [comment]
> > 又测试了一下，Lienol版固件可以连上，lean的固件还是不行
> 
> 这个 我目前没有交换机 没有测试条件了
> 你可以尝试在 http://friendlywrt/cgi-bin/luci/admin/network/hosts 添加一条映射试试看

lienol版可以连上，lean不行，我看了下config文件，lienol版没有编译docker，lean编译了，不知道这是不是原因

**Comment by lsl330** [comment]
刚测试minimal固件也可以局域网端口映射，谢谢编译如此好的固件
