### ISSUE TITLE
r1s h3固件能否加入openwrt和adguardhome

### ISSUE THREAD

**Issue by q943613777** [klever1988/nanopi-openwrt#174]
这两个平时都比较常用。不知能否可以在编译的时候一起打包编译

**Comment by q943613777** [comment]
> **什么**和adguardhome？

😅 sorry，打少了几个字，是openwrt clash 和一款广告过滤软件adguardhome

**Comment by potato1992** [comment]
> > **什么**和adguardhome？
> 
> sweat_smile sorry，打少了几个字，是openwrt clash 和一款广告过滤软件adguardhome

同求adguardhome，LEAN固件的Adbyby Plus +在海外根本没法用，过滤不了youtube.
