### ISSUE TITLE
minimal版本能否加上smb,minidlna,Watchcat 这3个插件

### ISSUE THREAD

**Issue by lhf19900402** [klever1988/nanopi-openwrt#176]
smb,minidlna：可以组个小的家庭影院，smb方便传输
Watchcat ：我发现拨号模式偶尔长时间会自动断开，有时候我关电源重启偶尔会失败，感觉加上这个插件方便拨号的设备使用，

**Comment by klever1988** [comment]
再往里加东西就不叫minimal了
