### ISSUE TITLE
smb传输速度骤降

### ISSUE THREAD

**Issue by lhf19900402** [klever1988/nanopi-openwrt#177]
我是千兆网线和网卡，R2S刷的Lean版，用smb传输大文件的时候刚开始是20-30M/s  经过几秒钟后会骤降到10M/s  像突然变百兆一样，我是往R2S插的U盘（2.0）里拷东西的，换了几块盘都是一样的   不知道是不是限速了？

**Comment by klever1988** [comment]
ntfs或者fat分区 在linux下性能不济 前期速度快 是内存缓冲写入 内存写满之后 速度就下降到真实数据了
