### ISSUE TITLE
请问如何不编译预先集成的ipk插件？

### ISSUE THREAD

**Issue by TheStoneOasis** [klever1988/nanopi-openwrt#18]
1.编译版本：
   R1S-Lean版

2.求助问题：
  我在自己的workflow里只写了几个常用的ipk，但刷入固件后发现还是有很多我没写进去的插件（比如 
   watchcat，sqm，adblock等），请问该如何在启动workflow编译前，把这些插件取消呢？

**Comment by klever1988** [comment]
你看到我有一个remove unused config 脚本吗，
对就是在那个脚本里面用sed去掉友善官方config里头预配置的插件

**Comment by TheStoneOasis** [comment]
> 你看到我有一个remove unused config 脚本吗，
> 对就是在那个脚本里面用sed去掉友善官方config里头预配置的插件

谢谢回复，但我点开那个文件，好像没看到watchcat，sqm，adblock等ipk字符啊

**Comment by TheStoneOasis** [comment]
> 你看到我有一个remove unused config 脚本吗，
> 对就是在那个脚本里面用sed去掉友善官方config里头预配置的插件

我看了下，所有预装的ipk都在appconfig.seed里，我不想要的ipk是不是直接在这个seed里删就好?

**Comment by klever1988** [comment]
完全可以的 
我以为你要去掉原厂的预配置组件
要去掉我的就在app_config.seed里面去

**Comment by klever1988** [comment]
完全可以的
我以为你要去掉原厂的预配置组件
要去掉我的就在app_config.seed里面去
