### ISSUE TITLE
希望出一个lean稳定版，远程上网课使用

### ISSUE THREAD

**Issue by Howardnm** [klever1988/nanopi-openwrt#180]
希望出一个lean大更稳定版，精简轻便的，远程上网课用，留学生之痛，只要机器一直稳定运行24小时以上，顺利出国看直播网课，中途不会突然失灵就行了

**Comment by klever1988** [comment]
minimal没有问题，lean版东西比较多，稳定性就难说咯

**Comment by Howardnm** [comment]
minimal好像没上网插件吧

**Comment by klever1988** [comment]
上网插件？

**Comment by Howardnm** [comment]
R2S minimal新版的有ssr+吗？

**Comment by Howardnm** [comment]
我现在在用lean很不稳定，上着网课突然就挂了

**Comment by klever1988** [comment]
> R2S minimal新版的有ssr+吗？

有的, ssrp, passwall和openclash

**Comment by Howardnm** [comment]
minimal哪版本最稳定？上课用

**Comment by klever1988** [comment]
基本上每一版minimal我都可以运行到下次升级重启，我大概三四天测试一次升级

**Comment by iamid0** [comment]
Can we have WireGuard in the mini release?

**Comment by klever1988** [comment]
> Can we have WireGuard in the mini release?

you can simply compile your binary with adding CONFIG_PACKAGE_luci-app-wireguard to the configuration area.

**Comment by iamid0** [comment]
> > Can we have WireGuard in the mini release?
> 
> 
> 
> you can simply compile your binary with adding CONFIG_PACKAGE_luci-app-wireguard to the configuration area.

Thanks. I will have a try. ^_^
