### ISSUE TITLE
您好，有问题请教

### ISSUE THREAD

**Issue by People-11** [klever1988/nanopi-openwrt#181]
我也在尝试使用Lean的源码编译OpenWrt，需要设置什么才能在主页面显示cpu频率与温度呢？

**Comment by People-11** [comment]
另外也想请教一下，CPUfreq插件在Menuconfig内没有显示，我看.config内已经有包括，编译后的固件依然没有，请问如何添加？

**Comment by klever1988** [comment]
温度需要autocore插件
autocore和cpufreq插件的Makefile限制了不能在arm固件里编译
你需要修改一下Makefile
另外这两个插件没啥用的 看看而已
