### ISSUE TITLE
可以编译出支持neo3的版本不

### ISSUE THREAD

**Issue by xmzhangya** [klever1988/nanopi-openwrt#182]
nanopi neo3和r2s配置基本一致，friendlywrt源代码已经更新，同时支持了neo3和r2s了

**Comment by klever1988** [comment]
你可以直接刷入neo3试试的，应该是直接能用，因为两者的编译代码没什么区别，只是调整了输出的固件文件名称而已

**Comment by klever1988** [comment]
能不能用吱个声🌝

**Comment by xmzhangya** [comment]
> 能不能用吱个声🌝

还没买😄😄～我就是买前咨询一下，准备挑选一个旁路由来代替我现在的树莓派

**Comment by klever1988** [comment]
> > 能不能用吱个声🌝
> 
> 还没买😄😄～我就是买前咨询一下，准备挑选一个旁路由来代替我现在的树莓派

rk3328很菜，温度还高，买rk3399才算顶的上树莓派
