### ISSUE TITLE
Patch kernel failed. 

### ISSUE THREAD

**Issue by iamid0** [klever1988/nanopi-openwrt#185]
This is the output from Actions. 

`20s
48
##[error]Process completed with exit code 1.
21
Note: switching to '68d9cb82143b864d70e4fb3d7cbb7068f82216a1'.
22

23
You are in 'detached HEAD' state. You can look around, make experimental
24
changes and commit them, and you can discard any commits you make in this
25
state without impacting any branches by switching back to a branch.
26

27
If you want to create a new branch to retain commits you create, you may
28
do so (now or later) by using -c with the switch command. Example:
29

30
  git switch -c <new-branch-name>
31

32
Or undo this operation with:
33

34
  git switch -
35

36
Turn off this advice by setting config variable advice.detachedHead to false
37

38
HEAD is now at 68d9cb8214 kernel: Update kernel 5.4 to version 5.4.50
39

40
Applying target/linux/generic/backport-5.4/010-Kbuild-don-t-hardcode-path-to-awk-in-scripts-ld-vers.patch using plaintext: 
41
patching file scripts/ld-version.sh
42

43
Applying target/linux/generic/backport-5.4/011-kbuild-export-SUBARCH.patch using plaintext: 
44
patching file Makefile
45
Hunk #1 FAILED at 471.
46
1 out of 1 hunk FAILED -- saving rejects to file Makefile.rej
47
Patch failed!  Please fix target/linux/generic/backport-5.4/011-kbuild-export-SUBARCH.patch!
48
`

How did I encounter the above error? 

Forked the entire code, 
edited nanopi-openwrt/.github/workflows/r2s_lean_minimal.yml by adding wireguard and ttyd to trigger the Action. 

Successfully built yesterday, but failed today with the above error message.

**Comment by klever1988** [comment]
upstream kernel code updated
script refreshed now
