### ISSUE TITLE
opkg update 失败

### ISSUE THREAD

**Issue by nuintun** [klever1988/nanopi-openwrt#186]
![批注 2020-09-01 204043](https://user-images.githubusercontent.com/1730277/91855060-36184b00-ec97-11ea-94ca-db8ad5bd209c.png)

请问怎么解决？

**Comment by klever1988** [comment]
有些软件源是不存在的，op编译自己加进去的，手动编辑/etc/opkg/distfeeds.conf去掉不存在的源即可
