### ISSUE TITLE
为何Fork以后总是无法编译成功

### ISSUE THREAD

**Issue by isyume** [klever1988/nanopi-openwrt#189]
除了去掉了几个插件，把y改为n，其他都没动，为何总是编译不成功？
![image](https://user-images.githubusercontent.com/54021172/92050783-4592b380-edbf-11ea-80b5-ff350f16c5dc.png)

**Comment by klever1988** [comment]
把rm -f target/linux/rockchip-rk3328/patches-4.14/0001-net-thunderx-workaround-BGX-TX-Underflow-issue.patch target/linux/generic/hack-4.14/999-net-patch-linux-kernel-to-support-shortcut-fe.patch改成
rm -f target/linux/rockchip-rk3328/patches-4.14/0001-net-thunderx-workaround-BGX-TX-Underflow-issue.patch


或者


去掉luci-app-sfe
