### ISSUE TITLE
亲，能编译时候集成openclash么，这个分流牛逼

### ISSUE THREAD

**Issue by hetaoxiaoming** [klever1988/nanopi-openwrt#19]
亲，能编译时候集成openclash么，这个分流牛逼

**Comment by klever1988** [comment]
这种几年前的arm板性能非常有限，加载那种接管全局流量的分流软件恐怕要使极限性能（跑满1g已经跟够呛了）在下降两三成，所以不建议啦

你要clash也有别人编译好的，github搜索soffchan就能找到。

**Comment by soffchen** [comment]
集成 openclash 的 https://github.com/soffchen/NanoPi-R2S

**Comment by hetaoxiaoming** [comment]
谢谢啦
