### ISSUE TITLE
发现两个不错的主题，集成个？

### ISSUE THREAD

**Issue by nuintun** [klever1988/nanopi-openwrt#191]
[infinityfreedom](https://github.com/xiaoqingfengATGH/luci-theme-infinityfreedom)

![Login](https://raw.githubusercontent.com/xiaoqingfengATGH/luci-theme-infinityfreedom/master/screenshots/000.Login.jpg)
![Firewall](https://raw.githubusercontent.com/xiaoqingfengATGH/luci-theme-infinityfreedom/master/screenshots/002.Firewall.jpg)

[edge](https://github.com/garypang13/luci-theme-edge)

![Dashboard](https://raw.githubusercontent.com/garypang13/luci-theme-edge/master/Screenshots/3.png)
![Extensions](https://raw.githubusercontent.com/garypang13/luci-theme-edge/master/Screenshots/5.png)

**Comment by klever1988** [comment]
靠 你还真讲究

**Comment by nuintun** [comment]
@klever1988 看着爽才有动力进后台耍 :joy: 这俩官方提供了 ipk，倒是可以直接装 ，关了吧 :joy:

**Comment by klever1988** [comment]
好的大佬 infinityfreedom集成进去了 我再照办就是

**Comment by nuintun** [comment]
@klever1988 大佬牛B，给你笔芯 :heart:
