### ISSUE TITLE
密码不对 

### ISSUE THREAD

**Issue by xiaotiantian1132** [klever1988/nanopi-openwrt#193]
刷入了9月6日的minial版本 密码不对 进不去系统

**Comment by klever1988** [comment]
怎么刷的   tf卡刷还是au.sh升级?

**Comment by xiaotiantian1132** [comment]
tf卡刷的

**Comment by klever1988** [comment]
用户名root 密码password

**Comment by xiaotiantian1132** [comment]
![image](https://user-images.githubusercontent.com/39047774/92425829-eb2c9500-f1ba-11ea-92c5-47743b0bc829.png)

**Comment by xiaotiantian1132** [comment]
![image](https://user-images.githubusercontent.com/39047774/92425854-fed7fb80-f1ba-11ea-8a57-f4ac0c295375.png)

**Comment by xiaotiantian1132** [comment]
一直用的k大的minimal系统 很稳定 就这次刷的6号的之后输入密码死活进不去

**Comment by klever1988** [comment]
这几天脚本改动大，可能弄出bug了
你刷下7号的试试看

**Comment by xiaotiantian1132** [comment]
好的，试一下7号的看看

**Comment by xiaotiantian1132** [comment]
重新刷入7号版本之后恢复正常，如果能添加多拨插件就更好了
