### ISSUE TITLE
openwrt 官方加入了 nanopi r2s了

### ISSUE THREAD

**Issue by aueu** [klever1988/nanopi-openwrt#194]
后面会考虑根据基于openwrt官方源码吗

https://github.com/openwrt/openwrt/blob/master/target/linux/rockchip/image/armv8.mk

https://downloads.openwrt.org/snapshots/targets/rockchip/armv8/

**Comment by nicedayesc** [comment]
我刷了openwrt 的镜像 但是貌似 起不来

**Comment by klever1988** [comment]
可以启动，最大的问题是更新固件设置无法保存

**Comment by nicedayesc** [comment]
我刷了之后  红灯不跳，刷你这个固件 和 friendly 固件 都能起来

**Comment by klever1988** [comment]
sd卡兼容性问题 原生方式固件问题较多 先撤了吧
