### ISSUE TITLE
zram内核模块建议打开

### ISSUE THREAD

**Issue by aueu** [klever1988/nanopi-openwrt#196]
https://forum.openwrt.org/t/rfc-new-zram-zswap-package-and-scripts/49076/3
https://github.com/openwrt/openwrt/tree/master/package/system/zram-swap

越来越多的golang app出现，吃内存大户
swap挂载到zram设备上压缩，在内存不够，需要swap的时候，性能提升会非常明显，再也不用担心docker容器

**Comment by klever1988** [comment]
已解决
