### ISSUE TITLE
如何正确使用 R2S在线升级？

### ISSUE THREAD

**Issue by tancolo** [klever1988/nanopi-openwrt#197]
Hello Klever,

我R2S 之前刷的是 20.04.08版本，想通过在线升级方式更新到20.09.08
使用该方法 执行脚本后 https://prnt.sc/udskme
看到是有提示： https://prnt.sc/udscys
显示的各种提示，应该是成功的，
其中 最后一句 “准备刷机” 是什么意思？ 是等着他自动完成吗？我等了许久 也没有啥反应，我重新登陆LUCI web端，
https://prnt.sc/udsdyn  还是之前的版本信息。
是我遗漏了什么重要步骤？ 怎么没有在线升级成功？ 
Thank you!

我查看到 https://github.com/klever1988/nanopi-openwrt/issues/47 这个应该是没有以上“在线升级脚本”之前的方法吧？

**Comment by klever1988** [comment]
![image](https://user-images.githubusercontent.com/56048681/92510483-81ee6580-f23e-11ea-9aa4-9303383ffa44.png)

你下载没成功，后续的脚本执行都出错

把下载时连接的s3域名添加到ssrp的域名列表，走代理下载确保成功
