### ISSUE TITLE
r1s Lean 固件 国内间歇性断流

### ISSUE THREAD

**Issue by sitsh** [klever1988/nanopi-openwrt#20]
R1S-Lean-2020-02-27-ROM
R1S-Lean-2020-02-28-ROM
默认 开启了ssr plus  导入了一个 v2ray ws+tls 节点  国内白名单 方式
其他 所有其他 配置 都 默认 没有修改过。

故障现象是  国内 会断流  
在客户端 pc  命令行 ping baidu.com 时 能解析到 正确的ip地址，
 但是 全部超时没响应，其他国内域名也是一样的现象，(Lan 口 接 ap  和直接 用 r1s 无线 一样的情况)
 这时 ping 国外 ip 都能正常得到响应。

这时通过 ssh 登陆 r1s  在r1s 上 ping baidu.com 能得到正确的响应 ，
过一些时候 后  上面的 国内断流会自动恢复， 观察 路由器 在线时间 和 ssr plus 日志 都没有重启过
访问国外 ip 通过 ssr plus v2ray 走的流量始终都是 正常没有断流过。

**Comment by GeekerXu** [comment]
确实存在这个问题，刷r1s_lienol 版感觉很好

**Comment by klever1988** [comment]
对插件没有太多需求的话 刷minimal好一点

**Comment by sitsh** [comment]
> minimal

r1s 固件好像还没有 minimal 版本的。 以后会放出吗

**Comment by oceanblue007** [comment]
可能是多路负载均衡的问题，禁用负载均衡就好了
