### ISSUE TITLE
能否恢复ChinaDNS_NG？

### ISSUE THREAD

**Issue by twour** [klever1988/nanopi-openwrt#200]
能否恢复ChinaDNS_NG？挺需要的

**Comment by klever1988** [comment]
minimal恢复了chinadns-ng选项
大包版加入了https://github.com/WuSiYu/luci-app-chinadns-ng

**Comment by twour** [comment]
passwall的dns过滤模式里有ChinaDNS了么？

**Comment by klever1988** [comment]
![image](https://user-images.githubusercontent.com/56048681/93155518-dd39bf80-f738-11ea-8f71-7949db6169ef.png)
