### ISSUE TITLE
ssr插件貌似有问题?.....

### ISSUE THREAD

**Issue by yuban10703** [klever1988/nanopi-openwrt#201]
![image](https://user-images.githubusercontent.com/39484884/92997382-7607e980-f545-11ea-8365-4db41e0f02e2.png)
![image](https://user-images.githubusercontent.com/39484884/92997422-ca12ce00-f545-11ea-9af9-746df3e69784.png)

![image](https://user-images.githubusercontent.com/39484884/92997390-8fa93100-f545-11ea-99fc-4907495cf1a4.png)

内网主机列表填写的是一个不存在的ip
但是v2ray服务端的log一直在刷访问www.baidu.com

**Comment by klever1988** [comment]
可能是adbyby插件在作妖
https://github.com/coolsnowwolf/lede/blob/master/package/lean/luci-app-adbyby-plus/root/usr/share/adbyby/adbybyupdate.sh

**Comment by yuban10703** [comment]
emm,不过我没开启adbyby..,这个脚本不开启也会运行么....
![image](https://user-images.githubusercontent.com/39484884/92997774-57efb880-f548-11ea-88d3-756283d432c6.png)

**Comment by klever1988** [comment]
不是adbyby
应该是/usr/bin/ssr-switch
这是自动检测和切换失效节点的脚本

**Comment by yuban10703** [comment]
emm,我把自动切换关闭了,后台还是在刷,用passwall貌似没问题,挺奇怪的,,,,,
![image](https://user-images.githubusercontent.com/39484884/92998368-0b0de100-f54c-11ea-9512-257786fad177.png)

![image](https://user-images.githubusercontent.com/39484884/92998232-46f47680-f54b-11ea-8a6e-aaee3c5a7192.png)
下面是ssrp的设置
![image](https://user-images.githubusercontent.com/39484884/92998288-8cb13f00-f54b-11ea-8678-2b4556e40975.png)
![image](https://user-images.githubusercontent.com/39484884/92998306-abafd100-f54b-11ea-968b-c35191a6c824.png)
![image](https://user-images.githubusercontent.com/39484884/92998312-af435800-f54b-11ea-9d72-22a2302af74c.png)
![image](https://user-images.githubusercontent.com/39484884/92998302-a2266900-f54b-11ea-8aee-9cd30e645895.png)
![image](https://user-images.githubusercontent.com/39484884/92998326-c08c6480-f54b-11ea-9ac5-e7eff4eb0ab6.png)
![image](https://user-images.githubusercontent.com/39484884/92998329-c6824580-f54b-11ea-8fc7-9a2084391c32.png)

**Comment by klever1988** [comment]
你把/usr/bin/ssr-switch删除 然后重启 看看还刷不刷

**Comment by yuban10703** [comment]
我试试

**Comment by yuban10703** [comment]
![image](https://user-images.githubusercontent.com/39484884/92998700-f0d50280-f54d-11ea-876b-76a9eac10f7f.png)
删除后重启了,然后开机打开ssrp后还在刷......

**Comment by klever1988** [comment]
备份一下ssr-check然后删掉它试试

**Comment by yuban10703** [comment]
![image](https://user-images.githubusercontent.com/39484884/92998918-76a57d80-f54f-11ea-9660-c8b1eddd70c5.png)
正常了,emmm
![image](https://user-images.githubusercontent.com/39484884/92998925-8755f380-f54f-11ea-854d-325ea5c08ef4.png)
