### ISSUE TITLE
请问 R1S-Lienol-2020-09-11 的版本为何没有科学上网插件

### ISSUE THREAD

**Issue by ddcatgg** [klever1988/nanopi-openwrt#203]
大家好！
如题，在下面的地址下载了最新 R1S 编译包，烧录TF后打开R1S的配置页面，服务里面没有科学上网插件。
https://github.com/klever1988/nanopi-openwrt/releases/tag/R1S-Lienol-2020-09-11

求解答，谢谢！

**Comment by klever1988** [comment]
确实漏了，lienol的代码https://github.com/Lienol/openwrt/blob/dev-19.07/include/target.mk 取消了pw软件包的默认编入，我加进去了
