### ISSUE TITLE
希望整合 WireGuard

### ISSUE THREAD

**Issue by Kaiyuan** [klever1988/nanopi-openwrt#209]
我打算用 WireGuard 组网，然后刷了系统之后发现没有... OPKG 装 就缺少 kmod-wireguard。
目前正尝试自己编译。

**Comment by klever1988** [comment]
友善的内核没有添加wireguard模块，没办法从内核编译阶段添加

你可能要从op原生编译的方式去添加了， https://github.com/klever1988/nanopi-openwrt/blob/master/.github/workflows/r2s_native-dev.yml
