### ISSUE TITLE
动态DNS里面发服务提供商没有阿里DDNS，请问加上这个方便吗？

### ISSUE THREAD

**Issue by yaoniming-158** [klever1988/nanopi-openwrt#21]
X86架构里面通用的插件里面有，但是换上R2S以后就没了，感觉有一点点不方便。
如果加上方便吗？

**Comment by klever1988** [comment]
ok

**Comment by yaoniming-158** [comment]
> 好



> ok

昨晚试了一下只有这位 Lienol大佬固件里面没有，另外以为Lean大佬里面同样的“动态DNS“插件里面在服务里面有aliddns。

**Comment by klever1988** [comment]
> > 好
> 
> > ok
> 
> 昨晚试了一下只有这位 Lienol大佬固件里面没有，另外以为Lean大佬里面同样的“动态DNS“插件里面在服务里面有aliddns。

没听懂 现在出现了吗 我已经加入编译参数了
