### ISSUE TITLE
想请教各位：R2S下，Turbo ACC 网络加速都怎么启用的？

### ISSUE THREAD

**Issue by drw2005** [klever1988/nanopi-openwrt#217]
是全部启用，还是有选择的启用？有什么影响呢？感谢！
https://www.z4a.net/images/2020/09/21/QQ20200921095327.jpg

**Comment by klever1988** [comment]
我认为dns还有点意义，其他的几个也就那样，bbr据说能改善丢包网络，但是对wifi有反效果，offloading减轻路由器转发负载，但是对于500m以下的宽带意义不大，因为跑满宽带仍然不会跑满cpu负载能力，然后是fullcone，只是用来提升nat级别，满足某些设备如ps4的联机要求。

**Comment by drw2005** [comment]
> 我认为dns还有点意义，其他的几个也就那样，bbr据说能改善丢包网络，但是对wifi有反效果，offloading减轻路由器转发负载，但是对于500m以下的宽带意义不大，因为跑满宽带仍然不会跑满cpu负载能力，然后是fullcone，只是用来提升nat级别，满足某些设备如ps4的联机要求。

谢谢老大指点。
