### ISSUE TITLE
咨询一下   passwall里的服务器端如何配置？大佬可以帮帮我吗

### ISSUE THREAD

**Issue by LissyTube** [klever1988/nanopi-openwrt#218]

**Comment by klever1988** [comment]
这没办法帮你 去电报群问吧

**Comment by LissyTube** [comment]
U1S1 确实
55r+就可以用   pass 的就不能用哈哈哈好诡异

klever1988 <notifications@github.com> 于2020年9月22日周二 上午9:38写道：
