### ISSUE TITLE
风扇问题，总是起起停停的。。。

### ISSUE THREAD

**Issue by bingmiao** [klever1988/nanopi-openwrt#228]
没有找到风扇相关的配置项
请问如何改对应代码实现啊？

现在基本温度在50的时候就开始，转10秒钟左右，然后就停了

我想让他60的时候开始转，50的时候停止

求教了

**Comment by klever1988** [comment]
可以停止pwmfan服务，让风扇停转
也可以编辑/usr/bin/start-rk3328-pwm-fan.sh，控制风扇的规则
