### ISSUE TITLE
大神你好，能不能加入两个插件openvpn 和 SoftEther

### ISSUE THREAD

**Issue by stevenlinfeng** [klever1988/nanopi-openwrt#23]
大神你好，能不能加入两个插件openvpn 和 SoftEther,我编译大雕，选择Arm架构，独立编译这两个插件IPK包总是不成功，崩溃了。

**Comment by klever1988** [comment]
我不知道你说的插件完整名称 你发一下 或者github上插件的源码地址也行

**Comment by stevenlinfeng** [comment]
https://github.com/SoftEtherVPN/SoftEtherVPN

**Comment by stevenlinfeng** [comment]
> 我不知道你说的插件完整名称你发一下或github上插件的源码地址也行

https://github.com/SoftEtherVPN/SoftEtherVPN

**Comment by klever1988** [comment]
加进去了 明天跑看看

**Comment by stevenlinfeng** [comment]
谢谢

**Comment by stevenlinfeng** [comment]
> 加进去了明天跑看看

忘记跟你说是R2S

**Comment by stevenlinfeng** [comment]
> 加进去了明天跑看看

能编译成功吗？

**Comment by klever1988** [comment]
r2s lean版 应该已经有了 你刷看看

**Comment by stevenlinfeng** [comment]
有了谢谢
