### ISSUE TITLE
ShadowSocksR Plus+订阅失败

### ISSUE THREAD

**Issue by Efforts1983** [klever1988/nanopi-openwrt#235]
大佬帮忙看一下更新固件后订阅地址无法更新，刷了几个固件都是同样的问题。手机端和PC端都可以更新！！这是后台日志
![QQ截图20201006103206](https://user-images.githubusercontent.com/72425328/95152795-78660800-07c0-11eb-9cbf-c742065cbeb9.png)

**Comment by klever1988** [comment]
机场给的订阅链接的格式问题，ssrp不支持
