### ISSUE TITLE
Passwall 中的Socks5无法启动

### ISSUE THREAD

**Issue by chwater** [klever1988/nanopi-openwrt#24]
日志：
2020-03-02 15:16:02: 找不到-c /var/etc/passwall/SOCKS5_1.json -b 0.0.0.0 -u主程序，无法启动！

版本：
OpenWrt 19.07-SNAPSHOT / LuCI 18-Lienol (git-20.057.51438-539f769)

**Comment by klever1988** [comment]
r1s还是r2s？

**Comment by chwater** [comment]
R2S
