### ISSUE TITLE
最近几版openclash缺组件运行不起来

### ISSUE THREAD

**Issue by catbbc** [klever1988/nanopi-openwrt#248]
好像缺libcap-bin

**Comment by timedecay** [comment]
同缺组件，无法运行 open clash...

**Comment by Xsw777777** [comment]
软件包里好像是有的，去安装下就行

**Comment by klever1988** [comment]
升级了libcap 能用了吗现在？

**Comment by catbbc** [comment]
昨晚的目前👌

在 2020年10月21日，21:19，klever1988 <notifications@github.com> 写道：

﻿

升级了libcap 能用了吗现在？

**Comment by Xsw777777** [comment]
可




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "klever1988"<notifications@github.com&gt;; 
发送时间: 2020年10月21日(星期三) 晚上9:19
收件人: "klever1988/nanopi-openwrt"<nanopi-openwrt@noreply.github.com&gt;; 
抄送: "♂睡不醒"<321665641@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [klever1988/nanopi-openwrt] 最近几版openclash缺组件运行不起来 (#248)





 
升级了libcap 能用了吗现在？

**Comment by yuanzhuohao** [comment]
同样问题，你们有人解决了吗？

**Comment by timedecay** [comment]
> 同样问题，你们有人解决了吗？

解决了啊，大概几天后的版本就解决了。
