### ISSUE TITLE
opkg 命令失效

### ISSUE THREAD

**Issue by lwl19** [klever1988/nanopi-openwrt#251]
root@FriendlyWrt:/# opkg install zstd
Upgrading zstd on root from 1.3.8-1 to 1.4.5-2...
Downloading https://openwrt.proxy.ustclug.org/snapshots/packages/aarch64_cortex-a53/packages/zstd_1.4.5-2_aarch64_cortex-a53.ipk
Collected errors:
 * opkg_install_pkg: Package size mismatch: zstd is 52106 bytes, expecting 52092 bytes
 * opkg_install_cmd: Cannot install package zstd.

Collected errors:
 * opkg_download: Failed to download https://openwrt.proxy.ustclug.org/snapshots/targets/rockchip-rk3328/generic/packages/Packages.gz, wget returned 8.
 * opkg_download: Failed to download https://openwrt.proxy.ustclug.org/snapshots/packages/aarch64_cortex-a53/helloworld/Packages.gz, wget returned 8.
 * opkg_download: Failed to download https://openwrt.proxy.ustclug.org/snapshots/packages/aarch64_cortex-a53/lienol/Packages.gz, wget returned 8.

**Comment by klever1988** [comment]
在线升级？
zstd不需要另外安装了，现在都自带了
