### ISSUE TITLE
Hello, what's the url_fullconenat_patch:      url_flowoffload_patch: 

### ISSUE THREAD

**Issue by uosX** [klever1988/nanopi-openwrt#26]
你好，我需要Nanopi R2S ： pptp, L2TP, OpenVPN; server and client，
或者secrets.url1和secrets.url2应该设置什么内容呀

**Comment by uosX** [comment]
We need the pptp, L2TP, OpenVPN; server and client

**Comment by uosX** [comment]
Nanopi R2S

**Comment by klever1988** [comment]
直接删了那几行就可以编译了 没什么用

**Comment by uosX** [comment]
你的luci-app-flowoffload里面，FULLCONE NAT加速 | 运行中，是不是因为你这两句更换了Linux内核？
