### ISSUE TITLE
请问minimal 10-1版本，为何翻墙ping www.google.com失败

### ISSUE THREAD

**Issue by lyjhyjyes** [klever1988/nanopi-openwrt#287]
光猫桥接，R2S主路由，一直用内置ssr+翻墙，很正常。
为什么cmd ping ping www.google.com 失败，请求超时
请问一直开SSR插件翻墙，会影响国内上网网速吗？
我一般是需要扶墙，才开ssr，不是担心流量不够

**Comment by klever1988** [comment]
ping数据包是icmp
ssr只接管tcp

**Comment by lyjhyjyes** [comment]
明白，谢谢

klever1988 <notifications@github.com> 于2020年10月29日周四 下午5:29写道：
