### ISSUE TITLE
opkg update 失敗

### ISSUE THREAD

**Issue by isinglever** [klever1988/nanopi-openwrt#288]
我按照readme里的方法進行在線升級，但是第一步就報錯了。請問如何解決呢
`Collected errors:
 * opkg_download: Failed to download https://openwrt.proxy.ustclug.org/snapshots/targets/rockchip-rk3328/generic/packages/Packages.gz, wget returned 8.
 * opkg_download: Failed to download https://openwrt.proxy.ustclug.org/snapshots/packages/aarch64_cortex-a53/helloworld/Packages.gz, wget returned 8.
 * opkg_download: Failed to download https://openwrt.proxy.ustclug.org/snapshots/packages/aarch64_cortex-a53/lienol/Packages.gz, wget returned 8.`

**Comment by isinglever** [comment]
這個連接提示404 not found

**Comment by coolboy0961** [comment]
多搜搜以前的issue。
https://github.com/klever1988/nanopi-openwrt/issues/286#issuecomment-718837157

**Comment by isinglever** [comment]
> 多搜搜以前的issue。
> [#286 (comment)](https://github.com/klever1988/nanopi-openwrt/issues/286#issuecomment-718837157)

感謝解答
