### ISSUE TITLE
能否给minimal加上frp？

### ISSUE THREAD

**Issue by darktoy** [klever1988/nanopi-openwrt#29]
我就随便一讲，打扰了。
非常感谢提供固件。

**Comment by darktoy** [comment]
刷的R2S-Lean-2020-03-03-minimal-ROM.zip
我自己在软件包里装上frpc和luci-app-frpc，好像用不了，服务里表里没有。
原因我也没法查，毕竟菜鸟。

**Comment by klever1988** [comment]
我先加上

**Comment by darktoy** [comment]
哇哦，谢谢。
