### ISSUE TITLE
内核v2ray版本4.27.0-1，能否升级一下？或者自己怎么更新

### ISSUE THREAD

**Issue by Deckard-f-Cain** [klever1988/nanopi-openwrt#292]
查了一下软件包，v2ray的还是4.27.0-1，现在最新的已经到了4.32.0了。。。passwall里面有组件更新，但更新后，软件包显示还是4.27.0. ssrp 里的应该没有升级，而我主要就是用ssrp。求各位大佬指点迷津

**Comment by klever1988** [comment]
ok 晚点弄

**Comment by bike3097a** [comment]
> ok 晚点弄

啥时候添加 smartdns插件呀？

**Comment by Deckard-f-Cain** [comment]
> ok 晚点弄

感谢大佬！

**Comment by klever1988** [comment]
已经加入新版的v2ray了

**Comment by Deckard-f-Cain** [comment]
> 已经加入新版的v2ray了
谢谢！已经用上了！感谢！我关闭这条了
