### ISSUE TITLE
网易音乐解除限制pro有问题

### ISSUE THREAD

**Issue by wespochac** [klever1988/nanopi-openwrt#30]
Lienol版中，其中第二个网易音乐插件有些问题，感觉可以去掉

**Comment by klever1988** [comment]
截图看下第几个 地址栏一起截图一下

**Comment by wespochac** [comment]
R1S的效果图
昨日在R2S上的也是如此
![2020-03-04_18-49-31](https://user-images.githubusercontent.com/61771278/75872865-e670d800-5e49-11ea-9a8a-b6af7449ec1f.png)
![2020-03-04_18-49-58](https://user-images.githubusercontent.com/61771278/75872866-e670d800-5e49-11ea-80a0-74c796ec1635.png)
