### ISSUE TITLE
R2S 刷R2S-Lienol-2020-03-03会出现系统崩溃

### ISSUE THREAD

**Issue by NathanDai** [klever1988/nanopi-openwrt#32]
输入系统 通过dhcp联网 关闭ipv6 打开网络加速 打开hello word 可以正常上网
但是大概半个小时到一个小时之后 系统就会崩溃 :
(1)192.168.2.1打不开 
(2)网络不通 
(3)ping 路由器地址可以ping通 
重启路由器恢复正常 但是过大概半个小时到一个小时之后 系统就会重新崩溃

**Comment by klever1988** [comment]
等今天新版发布后更新一下试试看

**Comment by NathanDai** [comment]
刷了R1S-Lean-2020-03-07 连启动都启动不了了 R1S-Lienol-2020-03-06可以正常启动

**Comment by klever1988** [comment]
你的设备 到底是R1S还是R2S。。。

**Comment by NathanDai** [comment]
刷了最新的固件已经正常了 感谢
