### ISSUE TITLE
最近几天的固件，没有一个能进后台的，DHCP全都有问题，拔电源重启一个样

### ISSUE THREAD

**Issue by gimgoo** [klever1988/nanopi-openwrt#326]
最近几天的固件，没有一个能进后台的，DHCP全都有问题，拔电源重启一个样

**Comment by avsba001** [comment]
我是12月1号的Lienol版本，重刷先用工具把tf写1G左右的0数据，刷好后开DHCP，不要开acc加速，现在很正常

**Comment by Wyaohui** [comment]
> 我是12月1号的Lienol版本，重刷先用工具把tf写1G左右的0数据，刷好后开DHCP，不要开acc加速，现在很正常

原理是啥？我也是，最近固件经常进不到后台，网络端口也不识别，只能知己改ip然后碰运气进

**Comment by avsba001** [comment]
> > 我是12月1号的Lienol版本，重刷先用工具把tf写1G左右的0数据，刷好后开DHCP，不要开acc加速，现在很正常
> 
> 原理是啥？我也是，最近固件经常进不到后台，网络端口也不识别，只能知己改ip然后碰运气进

![image](https://user-images.githubusercontent.com/29015932/101588608-baf6cb80-3a21-11eb-8d66-53778aed5015.png)
为了保险我都这样操作，除了404大佬的超频固件我启动不了其他都还好

**Comment by avsba001** [comment]
> > 我是12月1号的Lienol版本，重刷先用工具把tf写1G左右的0数据，刷好后开DHCP，不要开acc加速，现在很正常
> 
> 原理是啥？我也是，最近固件经常进不到后台，网络端口也不识别，只能知己改ip然后碰运气进

![image](https://user-images.githubusercontent.com/29015932/101588687-eaa5d380-3a21-11eb-806d-9b594bdd6f82.png)
不是很懂，我理解的是像格式化那样，数据并没有丢，刷入同一个人的固件可能污染现有配置
