### ISSUE TITLE
R2S openwrt Passwall中的访问控制无效

### ISSUE THREAD

**Issue by luyaoxiansen** [klever1988/nanopi-openwrt#338]
能检测到所有设备具体IP和MAC地址，但是设置模式都是大陆白名单，有几个设备不需要代理，访问控制中设置不代理（或走GFW）都无效，还是走的大陆白名单模式（中国列表以外模式）    
访问控制这个功能基本无效，我看有人4月分左右就在讨论这个问题，这么多版本了，还是没有解决。

**Comment by jian2333** [comment]
你最后怎么解决的，我的11-24版本也有这个问题，还想升级最新的看有没解决， 就看到你这个提问了
