### ISSUE TITLE
大佬能帮忙编译一下nanopi r1 h3的固件吗

### ISSUE THREAD

**Issue by q943613777** [klever1988/nanopi-openwrt#34]
大佬能帮忙编译一下nanopi r1 h3的固件吗，感谢。

**Comment by q943613777** [comment]
可以的话带passawll、去广告、turbo ACC这三个插件足够。感谢

**Comment by klever1988** [comment]
我感觉h5和h3的固件没有多大区别，内核和op都是一样的，你可以试试h5直接刷到卡上去启动h3

**Comment by q943613777** [comment]
> 我感觉h5和h3的固件没有多大区别，内核和op都是一样的，你可以试试h5直接刷到卡上去启动h3

我试过了r1s h3的可以刷进去，r1s h5刷进去系统启动不了

**Comment by q943613777** [comment]
> 我感觉h5和h3的固件没有多大区别，内核和op都是一样的，你可以试试h5直接刷到卡上去启动h3

我试过了r1s h3的可以刷进去也可以启动，r1 h5刷进去系统启动不了。不过是在电报群下载的固件。不是刷入你的固件。

**Comment by klever1988** [comment]
我试试看吧 手上没有h3 编译出来你帮我试试

**Comment by q943613777** [comment]
> 我试试看吧 手上没有h3 编译出来你帮我试试

好的。感谢大佬

**Comment by klever1988** [comment]
发了 试一下

**Comment by q943613777** [comment]
> 发了 试一下

收到，感谢大佬。晚上回去试一下

**Comment by q943613777** [comment]
> 发了 试一下

刷上了，可以正常使用。目前没发现有任何问题

**Comment by q943613777** [comment]
> 发了 试一下

感谢大佬。如果有h3的新固件，记得喊我

**Comment by liuwenlong001** [comment]
> > 发了试一下
> 
> 刷上了，可以正常使用。目前没发现有任何问题

请问能否分享下？

**Comment by klever1988** [comment]
在release那边
