### ISSUE TITLE
编译成功但是发布失败

### ISSUE THREAD

**Issue by rpwtinfo** [klever1988/nanopi-openwrt#36]
大佬，我用了你的代码，没有任何修改，但是出现这个错误
 Create Release0s
##[error]Bad credentials
Run actions/create-release@v1
##[error]Bad credentials

我看其他包括编译和打包都是成功的，这个是啥问题？谢谢

**Comment by klever1988** [comment]
https://github.com/settings/tokens

**Comment by rpwtinfo** [comment]
大佬，我是一个github小菜鸟，我想问一下，token我申请了，应该怎么用呢？我找不到设置环境变量的地方。有没有简单一点的教程呀。谢谢谢谢谢谢。

**Comment by klever1988** [comment]
你把脚本里面secrets.sec_token改成secrets.GITHUB_TOKEN应该就行了
