### ISSUE TITLE
What's app call doesn't work

### ISSUE THREAD

**Issue by xenstar** [klever1988/nanopi-openwrt#371]
What's app call is always stuck in "connecting". My UDP server is turned on. I have attached the setting.
<img width="419" alt="what'sapp call" src="https://user-images.githubusercontent.com/55502651/108196811-835c7c00-7154-11eb-8018-3ef3363e5bce.png">

Anyways to fix it?

**Comment by xenstar** [comment]
There is some issue with UDP. I check with this website https://networktest.twilio.com/ also failed. 

Please check. In SSR+, I have already enabled UDP (Selected Same as Server)

<img width="933" alt="UDP" src="https://user-images.githubusercontent.com/55502651/108346996-faf4de80-721a-11eb-8c5b-c914f667f6e1.png">

**Here is my setting** 

<img width="430" alt="setting v2ray" src="https://user-images.githubusercontent.com/55502651/108347374-62ab2980-721b-11eb-9e6c-3cb1b07ffe11.png">

**Comment by klever1988** [comment]
You can try to upgrade the geographic IP database from this APP, or switch to other route mode.

**Comment by xenstar** [comment]
"from this APP" this app what do you mean? You can reply to me in Chinese.

**Comment by klever1988** [comment]
ssrp插件有ip数据库不是，升级一下看看，如果不行切换ssrp的运行模式到全局试试看是不是udp不支持

**Comment by xenstar** [comment]
Hi, Thanks for the quick reply. Well I have updated the IP Database, also tried with Global Mode, doesn't work. Tried with telegram call, what's app call, it's stuck at "connecting". You can have a try actually. 

When I am using same server, on phone with v2rayNG, it works. So I am using there is nothing wrong with the server, but issue with some settings on the firmware.

**Comment by xenstar** [comment]
Change to another firmware, and it's working. The issue is still with the firmware, hopefully you can check it sometimes and fix it. All the best.
