### ISSUE TITLE
R2S的ShadowSocksR Plus+无法代理外置无线网卡的流量

### ISSUE THREAD

**Issue by maiapig** [klever1988/nanopi-openwrt#379]
用的usb无线网卡是RTL190CT，无线功能和LAN口的ShadowSocksR Plus+功能可以正常使用，但是无线网不能科学上网。。请问是需要什么特别的设置吗，谢谢

**Comment by klever1988** [comment]
无线和lan是桥接的 不需要特别设置 你手机应该是内置了什么“安全dns”功能导致手机dns不走路由了 换成绕过大陆模式试试

**Comment by maiapig** [comment]
原来是我把无线设置成和wan口桥接了。。设置成lan之后确实可以使用了，感谢。
