### ISSUE TITLE
R2s2月28日版没有USB盘的网络共享了吗？

### ISSUE THREAD

**Issue by laulay2033** [klever1988/nanopi-openwrt#381]
不知新版本里的软件包安装能用吗？如果可以，应该安装哪个软件以实现网络共享？多谢！

**Comment by klever1988** [comment]
加进去咯

**Comment by laulay2033** [comment]
共享目录时只勾选了"可浏览"和"允许匿名用户"，window10访问时即使用root登陆，输入了路由器root密码，总提示“拒绝访问” 。是要输入其他缺省密码吗？
