### ISSUE TITLE
新固件里网络共享使用问题

### ISSUE THREAD

**Issue by laulay2033** [klever1988/nanopi-openwrt#385]
共享目录时只勾选了"可浏览"和"允许匿名用户"，window10访问时即使用root登陆，输入了路由器root密码，总提示“拒绝访问” 。是要输入其他缺省密码吗？还是在共享目录设定时勾选项有漏选？多谢！

**Comment by klever1988** [comment]
这版的插件确实有问题 我会替换掉

**Comment by klever1988** [comment]
修复了 试一下

**Comment by laulay2033** [comment]
刷了3月6号的版本，正常了。辛苦！
