### ISSUE TITLE
【已解决】风扇控制丢失20210303

### ISSUE THREAD

**Issue by anpplex** [klever1988/nanopi-openwrt#387]
全新卡刷升级后，开机启动项fa-rk3328-pwmfan丢失，需要自己另外配置
感谢@CWZ7605 
1.
通过OpenWrt TTYD终端上传friendlywrt/target/linux/rockchip-rk3328/base-files/usr/bin/start-rk3328-pwm-fan.sh到系统/usr/bin/目录下并通过chmod 777 start-rk3328-pwm-fan.sh修改脚本权限。
2.
通过OpenWrt TTYD终端上传friendlywrt/target/linux/rockchip-rk3328/base-files/etc/init.d/fa-rk3328-pwmfan到系统/etc/init.d/目录下，并通过chmod 777 fa-rk3328-pwmfan修改脚本权限。
3.
通过命令ln -s /etc/init.d/fa-rk3328-pwmfan /etc/rc.d/S96fa-rk3328-pwmfan创建一个启动脚本的软链接到/etc/rc.d/目录下。
4.
通过命令/etc/init.d/fa-rk3328-pwmfan start启动脚本。
5.
通过OpenWrt启动项页面可以看到fa-rk3328-pwmfan这个服务已经启动，并且风扇是停止的状态。（温度在关闭的范围）

参考链接：
1.
friendlyarm/friendlywrt@e1fb88f friendlywrt官方固件added support for pwm fan提交
2.
https://github.com/friendlyarm/friendlywrt/tree/e1fb88ff29bcf634c875b94a9026565c7780149f/target/linux/rockchip-rk3328/base-files 所需脚本，注意有一个是rk3399的，rk3328不需要

**Comment by klever1988** [comment]
感谢， 我给他加进去吧
