### ISSUE TITLE
R1S Lienol 版，本地网速跑不满

### ISSUE THREAD

**Issue by urock666** [klever1988/nanopi-openwrt#39]
移动300M宽带，R1S-H5, lean版可以跑满， lienol只能到250-260左右。
在speedtest.net和speedtest.cn测速，没开代理。

**Comment by klever1988** [comment]
在系统->启动项停止掉一些无用的服务试试看能不能有提升

**Comment by iamid0** [comment]
R1S-H5, Lienol 似乎的确慢一点点。原因不明。不过已经很棒了。谢谢你的贡献。

**Comment by TheStoneOasis** [comment]
奇了怪了，我是lean版跑不满200兆宽带，只能跑到100.

**Comment by CWZ7605** [comment]
> 
> 
> 奇了怪了，我是lean版跑不满200兆宽带，只能跑到100.

那是您网线有问题

**Comment by TheStoneOasis** [comment]
> > 奇了怪了，我是lean版跑不满200兆宽带，只能跑到100.
> 
> 那是您网线有问题

但之前刷的固件都没问题
