### ISSUE TITLE
新固件的passwall dns解析问题

### ISSUE THREAD

**Issue by Hiccup6** [klever1988/nanopi-openwrt#393]
不管是fake ip 还是doh pdns 不到一天就得重启一下passwall，不然全局解析不出来网页。

**Comment by klever1988** [comment]
国内网站也无法解析了吗

**Comment by xmx12138** [comment]
我更新好几次新版固件了，但是passwall 一直不能用，所以折腾了几次都又换回去年的固件了。
大神啊，管理IP能不能还像老版固件一样，改成192.168.2，一般光猫默认的是192.168.1，刷了新固件有冲突。
期待有一天能用上新版固件里面的新插件。呜呜。。。。

**Comment by klever1988** [comment]
> 我更新好几次新版固件了，但是passwall 一直不能用，所以折腾了几次都又换回去年的固件了。
> 大神啊，管理IP能不能还像老版固件一样，改成192.168.2，一般光猫默认的是192.168.1，刷了新固件有冲突。
> 期待有一天能用上新版固件里面的新插件。呜呜。。。。

pass感觉设置太麻烦了我也没试， ssrp可以，ip我自己都想改，每次我都手动200.1很麻烦，索性我就改了

**Comment by Hiccup6** [comment]
是的，全局都无法解析了。重启passwall才可以。
