### ISSUE TITLE
请问如何把剩余的空间扩容?

### ISSUE THREAD

**Issue by gekkjoe** [klever1988/nanopi-openwrt#397]
软件包里的cfdisk安装了打不开 用DiskGenius格式化剩余空间之后挂载再重启再看空间最后成功了 还有更方便的方法吗

**Comment by gekkjoe** [comment]
直接用DiskGenius 解决了 #

**Comment by klever1988** [comment]
我试了很多办法 目前还不知道怎么在openwrt内部在线扩容 
目前唯一的办法还是你说的那样 离线扩容
