### ISSUE TITLE
R2S.请问下mini固件支持usb无线网卡么？如果支持的话是些型号

### ISSUE THREAD

**Issue by blakejia** [klever1988/nanopi-openwrt#40]

**Comment by raiuka** [comment]
同问，是否可以在下一个版本内支持RTL8821CU

**Comment by soffchen** [comment]
> 同问，是否可以在下一个版本内支持RTL8821CU

https://github.com/soffchen/NanoPi-R2S 这个支持

打 offload 补丁会导致网卡驱动失败

**Comment by klever1988** [comment]
不要热衷于卖周边，厂家应该先把温度解决好。买r2s的人没几个考虑无线的，所以我故意删掉无线驱动。
