### ISSUE TITLE
请问怎么自己安装插件

### ISSUE THREAD

**Issue by Smartbird-Gmz** [klever1988/nanopi-openwrt#400]
习惯用helloworld，然后就想自己安装这个插件，但是一直安装失败.网上的方法都试了，还是不行，请问有什么解决方案

**Comment by Smartbird-Gmz** [comment]
> 习惯用helloworld，然后就想自己安装这个插件，但是一直安装失败.网上的方法都试了，还是不行，请问有什么解决方案
（R4S）

**Comment by klever1988** [comment]
已经加进去咯
