### ISSUE TITLE
R2S-Lienol-2020-03-08 Passwall Socks5 不可用

### ISSUE THREAD

**Issue by chwater** [klever1988/nanopi-openwrt#41]
基本页面显示 socks未运行：
<img width="1152" alt="1" src="https://user-images.githubusercontent.com/2589338/76189729-631f0000-6216-11ea-9b37-5441bc5e8071.png">

日志中显示已运行：
<img width="773" alt="2" src="https://user-images.githubusercontent.com/2589338/76189877-ad07e600-6216-11ea-99a6-681faa690e12.png">

实际连接测试socks代理无法工作

**Comment by klever1988** [comment]
应该是Lienol插件问题 ，更新新版解决吧

**Comment by chwater** [comment]
Lienol插件系统内可以手动更新么？还是等你们的新固件的发布？

**Comment by klever1988** [comment]
> Lienol插件系统内可以手动更新么？还是等你们的新固件的发布？

只有我没有们。。。
是啊 直接刷比较简单

**Comment by chwater** [comment]
感谢！！！
