### ISSUE TITLE
Bug: 勾选“禁止解析 IPv6 DNS 记录”会导致无法打开luci管理页面

### ISSUE THREAD

**Issue by Sakurakouji-Runa** [klever1988/nanopi-openwrt#416]
### 勾选下图中“禁止解析 IPv6 DNS 记录”复选框会导致无法打开luci管理界面，显示为白屏。
![Snipaste_2021-03-13_20-19-34](https://user-images.githubusercontent.com/46081776/111029779-7839fa80-8439-11eb-91aa-f65bccf09dd4.png)

 该bug可以稳定复现，步骤如下：
> 1. 勾选该复选框，保存&应用
> 2. 打开新标签页，访问luci管理界面，显示为白屏
> 3. 取消勾选该复选框，保存&应用
> 4. 刷新在另一标签页的luci管理界面，正常显示

_环境：R2S，2021-03-13版
备注：因该bug导致的无法进入luci管理界面，只在系统启动一分钟左右之后生效，在刚刚启动系统后的约一分钟内可以正常进入luci管理界面。_

**Comment by klever1988** [comment]
无法复现，试过主机名和ipv4访问都可以正常打开，也重启过

**Comment by samanhk2** [comment]
今天的版本如果是升级过来的会有很多不明bug比如passwall卡死，无速度，IPV6出现故障，但是重新卡刷就好了，我有两个卡，一个卡刷没问题，换另一个升级来的卡问题出现，所以我还是建议今天的版本重新卡刷，比较稳妥。

发自我的iPhone

**Comment by klever1988** [comment]
> 今天的版本如果是升级过来的会有很多不明bug比如passwall卡死，无速度，IPV6出现故障，但是重新卡刷就好了，我有两个卡，一个卡刷没问题，换另一个升级来的卡问题出现，所以我还是建议今天的版本重新卡刷，比较稳妥。 发自我的iPhone
> […](#)
> 在 2021年3月13日，21:59，klever1988 ***@***.***> 写道： ﻿ 无法复现，试过主机名和ipv4访问都可以正常打开，也重启过 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

昨天比较大的变动就是恢复了upx压缩，还有给autoupdate.sh提供了扩容功能，出问题的哪个你应该是用autoupdate.sh升级的吧？

**Comment by samanhk2** [comment]
是的，有用脚本升级


发自我的iPad

**Comment by Sakurakouji-Runa** [comment]
> 是的，有用脚本升级 发自我的iPad
> […](#)
> 在 2021年3月14日，10:27，klever1988 ***@***.***> 写道： ﻿ 今天的版本如果是升级过来的会有很多不明bug比如passwall卡死，无速度，IPV6出现故障，但是重新卡刷就好了，我有两个卡，一个卡刷没问题，换另一个升级来的卡问题出现，所以我还是建议今天的版本重新卡刷，比较稳妥。 发自我的iPhone … 在 2021年3月13日，21:59，klever1988 @.***> 写道： ﻿ 无法复现，试过主机名和ipv4访问都可以正常打开，也重启过 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 昨天比较大的变动就是恢复了upx压缩，还有给autoupdate.sh提供了扩容功能，出问题的那个你应该是用autoupdate.sh升级的吧？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

感谢回复，更新到最新版本后这个bug就消失了，现在一切正常。问题解决了，我把issue关了。
