### ISSUE TITLE
怎么添加其他插件到r1s h5的版本里面

### ISSUE THREAD

**Issue by zia123-ai** [klever1988/nanopi-openwrt#42]

**Comment by zia123-ai** [comment]
你更新速度太快了🤣

**Comment by klever1988** [comment]
添加编译参数到app_config.seed就行了

**Comment by zia123-ai** [comment]
现在r1s flow还是不能用吗

**Comment by zia123-ai** [comment]
编译了会不会没用

**Comment by CWZ7605** [comment]
> 
> 
> 现在r1s flow还是不能用吗

FLOW一直是正常的。如果你fork过去执行不成功，你可以把release部分更换为action中输出即可。

**Comment by zia123-ai** [comment]
> > 现在r1s flow还是不能用吗
> 
> FLOW一直是正常的。如果你fork过去执行不成功，你可以把release部分更换为action中输出即可。

我说的是这个,flow加速在r1s里面用不了
                                                                                                                                                                 ![flow加速](https://raw.githubusercontent.com/klever1988/nanopi-openwrt/master/assets/Acc.jpg "flow加速状态")

**Comment by klever1988** [comment]
r1s目前没有打补丁，我尝试打了补丁了，但系统很不正常，连关机重启都会卡住。暂时就这样吧。因为lan口也就350M的峰值，用不到flow

**Comment by zia123-ai** [comment]
> r1s目前没有打补丁，我尝试打了补丁了，但系统很不正常，连关机重启都会卡住。暂时就这样吧。因为lan口也就350M的峰值，用不到flow

好 谢谢大佬😁
