### ISSUE TITLE
OpenVPN和OpenClash 配合使用

### ISSUE THREAD

**Issue by Olivercoco** [klever1988/nanopi-openwrt#424]
您好，我想在外部通过OpenVPN链接到r2s(固件里的OpenVPN Server)，且用Openclash分流，请问这是可做到吗？我该如何设置呢？
OpenVPN可以正常链接，但需要走代理的部分无法访问。

**Comment by klever1988** [comment]
https://github.com/vernesong/OpenClash/issues/1255
https://comzyh.gitbook.io/clash/real-ip-tun-example

你可以参考一下

**Comment by Olivercoco** [comment]
多谢指教。
