### ISSUE TITLE
版本：Minimal-12-04，请问如果不对调WAN、LAN带宽是不是只能跑到100M？

### ISSUE THREAD

**Issue by llllllllllx** [klever1988/nanopi-openwrt#427]
使用默认的WAN口拨号，LAN口直连电脑测速只能跑最高100M。对调后可以跑满带宽

**Comment by klever1988** [comment]
不是这个问题 不对调照样跑944M
你的网线接触不好 带宽降到100M了

**Comment by llllllllllx** [comment]
> 不是这个问题 不对调照样跑944M
> 你的网线接触不好 带宽降到100M了

但我网线没有换呀，一样的网线，对掉前只有100M，对调后跑满500M

**Comment by llllllllllx** [comment]
那我自己再检查检查吧，谢谢了
