### ISSUE TITLE
passwall 的谷歌连网测试失败，但是实际是通的!

### ISSUE THREAD

**Issue by symantes** [klever1988/nanopi-openwrt#430]
r4s 3.18 版本 passwall 的谷歌连网测试失败，但是实际是通的!

**Comment by symantes** [comment]
GFW的模式下

**Comment by Goodman-vip** [comment]
是的,我的更新了也是这样

**Comment by Goodman-vip** [comment]
用Hello world 科学上网后,再打开passwall ,然后点里面的谷歌能连接,,如果直接用passwall 科学上网后谷歌连网测试失败,奇怪吧

**Comment by symantes** [comment]
> 是的,我的更新了也是这样

刚刚试验，已经好了！
