### ISSUE TITLE
大佬请问为何内置的passwall等插件速度很慢？

### ISSUE THREAD

**Issue by cookiibear** [klever1988/nanopi-openwrt#435]
前两天更新的r2s，测试下来hello world、passwall、ssrp跑出来youtube只能有几百k，切换到电脑clash，同一节点能有七万多，请问是哪里设置有问题吗？还是需要重新刷写固件？

**Comment by Butterflyflower** [comment]
passwall高级设置 
设置成下面一样

转发配置
TCP不转发端口
不使用
 UDP不转发端口
不使用

TCP转发端口
所有
UDP转发端口
所有

**Comment by cookiibear** [comment]
> passwall高级设置
> 设置成下面一样
> 
> 转发配置
> TCP不转发端口
> 不使用
> UDP不转发端口
> 不使用
> 
> TCP转发端口
> 所有
> UDP转发端口
> 所有

谢谢大佬！

**Comment by cookiibear** [comment]
更改设置以后重启一下好像就好了，但是为啥使用helloworld情况下，safari上youtube可以跑十几万k，使用edge只能几百k？
