### ISSUE TITLE
大神R2S-Lienol版可否增加一个完全版得非常感谢

### ISSUE THREAD

**Issue by kulanchong** [klever1988/nanopi-openwrt#44]
大神R2S-Lienol版可否增加一个完全版得非常感谢

**Comment by klever1988** [comment]
什么意思？完全版

**Comment by kulanchong** [comment]
其实也没差多少，就是qos插件，几个插件也集成下，现在lienol版得是89m有精简一些插件了，现在得已经很好用了，只是如果大神闲暇之余考虑编一个插件比较全得版本

**Comment by klever1988** [comment]
qos就加入sqm吧？
