### ISSUE TITLE
r4s

### ISSUE THREAD

**Issue by zengjialuo2020** [klever1988/nanopi-openwrt#455]
r4s.img passwall tcp  不能运行  能国内上网  不能科学上网
             ShadowSocksR Plust   问题一样

**Comment by klever1988** [comment]
我不会科学上网 各路大神会的过来帮帮忙

**Comment by lhf19900402** [comment]
我也不懂什么是科学上网，只是出于对路由器智能系统的爱好刷了这个固件，目的是做一些例如广告过滤、离线下载、小型nas之类的方便应用😆

**Comment by drw2005** [comment]
大佬不是说了吗，在这里讨论这个不合适。
