### ISSUE TITLE
opkg 安装kmod-l2tp报错-请问有没有编译好的ipk呀

### ISSUE THREAD

**Issue by jason416** [klever1988/nanopi-openwrt#458]
用3-23版本，安装l2tp支持时，会有kmod报错，请问能添加编译好的ipk吗。
![image](https://user-images.githubusercontent.com/30687767/112316964-8cf27a00-8ce6-11eb-8ed7-3f502ae74209.png)

**Comment by klever1988** [comment]
![image](https://user-images.githubusercontent.com/56048681/112672959-1ea4e780-8e9f-11eb-8253-12104a3202fb.png)

可以正常安装了

![image](https://user-images.githubusercontent.com/56048681/112673012-2f555d80-8e9f-11eb-998c-a7b468cb496e.png)

**Comment by jason416** [comment]
> ![image](https://user-images.githubusercontent.com/56048681/112672959-1ea4e780-8e9f-11eb-8253-12104a3202fb.png)
> 
> 可以正常安装了
> 
> ![image](https://user-images.githubusercontent.com/56048681/112673012-2f555d80-8e9f-11eb-998c-a7b468cb496e.png)

谢谢大佬恢复，请问我需要如何操作呢？我目前用的是3-23版本。

**Comment by klever1988** [comment]
下载新版呀

**Comment by jason416** [comment]
> 下载新版呀

我用了3-27号得，发现使用不了了呢。有如下报错：

> Sat Mar 27 14:37:05 2021 daemon.debug xl2tpd[1872]: start_pppd: I'm running:
Sat Mar 27 14:37:05 2021 daemon.debug xl2tpd[1872]: "/usr/sbin/pppd"
Sat Mar 27 14:37:05 2021 daemon.debug xl2tpd[1872]: "plugin"
Sat Mar 27 14:37:05 2021 daemon.debug xl2tpd[1872]: "pppol2tp.so"
Sat Mar 27 14:37:05 2021 daemon.debug xl2tpd[1872]: "pppol2tp"
Sat Mar 27 14:37:05 2021 daemon.debug xl2tpd[1872]: "8"
Sat Mar 27 14:37:05 2021 daemon.debug xl2tpd[1872]: "passive"
Sat Mar 27 14:37:05 2021 daemon.debug xl2tpd[1872]: "nodetach"
Sat Mar 27 14:37:05 2021 daemon.debug xl2tpd[1872]: ":"
Sat Mar 27 14:37:05 2021 daemon.debug xl2tpd[1872]: "file"
Sat Mar 27 14:37:05 2021 daemon.debug xl2tpd[1872]: "/tmp/l2tp/options.vpn0"
Sat Mar 27 14:37:05 2021 daemon.err pppd[6352]: Error loading shared library /usr/lib/pppd/2.4.8/pppol2tp.so: No such file or directory
Sat Mar 27 14:37:05 2021 daemon.err pppd[6352]: Couldn't load plugin pppol2tp.so
Sat Mar 27 14:37:05 2021 daemon.debug xl2tpd[1872]: child_handler : pppd exited for call 2730 with code 2
Sat Mar 27 14:37:05 2021 daemon.info xl2tpd[1872]: call_close: Call 46639 to x.x.x.x disconnected

我看了下，确实没有pppol2tp.so文件。
```
root@ImmortalWrt:~# ls /usr/lib/pppd/2.4.8/
rp-pppoe.so
root@ImmortalWrt:~# 
```

**Comment by klever1988** [comment]
![image](https://user-images.githubusercontent.com/56048681/112727717-ccc39680-8f5e-11eb-8ecc-80636cc4b907.png)


我用slim版测试的 你用大杂烩么？

**Comment by jason416** [comment]
@klever1988 对，我用的大杂烩版本，就有上面的问题~

**Comment by jason416** [comment]
用slim版本，本地仓库直接安装可以解决。
