### ISSUE TITLE
不能从之前的固件直接终端在线升级到slim版么？

### ISSUE THREAD

**Issue by nonozone** [klever1988/nanopi-openwrt#459]
求问，命令没反应

**Comment by klever1988** [comment]
![image](https://user-images.githubusercontent.com/56048681/112330716-41929880-8cf3-11eb-9f20-2a1ce515b6e1.png)


这个不是吗

**Comment by nonozone** [comment]
> ![image](https://user-images.githubusercontent.com/56048681/112330716-41929880-8cf3-11eb-9f20-2a1ce515b6e1.png)
> 
> 这个不是吗

没反应，事实上两个命令都没反应...

试了下，好像是无法从路由器直接下载这个脚本

![image](https://user-images.githubusercontent.com/1277444/112398428-25b4e400-8d3f-11eb-9728-7fcb9a4ed040.png)

**Comment by nonozone** [comment]
关掉所有广告过滤，然后重启之后可以了。

BTW问一句，在新版本搜索下载ssrplus ，为啥不行？

![image](https://user-images.githubusercontent.com/1277444/112400475-66166100-8d43-11eb-8ba9-21212f8a5c2f.png)

**Comment by klever1988** [comment]
因为上游把一些插件代码从base移到packages，导致编译生成的本地软件源收录不完整，在修复中~~

**Comment by nonozone** [comment]
还有个问题，更新过来之后，好像DNS不生效，网络通了，域名都ping不通，lan 都设置了，不知道哪里的问题

**Comment by nonozone** [comment]
最终还是直接卡刷解决了...

**Comment by nonozone** [comment]
> 因为上游把一些插件代码从base移到packages，导致编译生成的本地软件源收录不完整，在修复中~~

那现在哪个插件可以正常用的？好急- - 哈哈

**Comment by klever1988** [comment]
> > 因为上游把一些插件代码从base移到packages，导致编译生成的本地软件源收录不完整，在修复中~~
> 
> 那现在哪个插件可以正常用的？好急- - 哈哈

修复了 试试

**Comment by nonozone** [comment]
好像还是不行，重启也不行，需要升级固件么？

**Comment by nonozone** [comment]
更新固件后解决，谢谢。
