### ISSUE TITLE
使用RTL8821CU后，无线界面显示问题

### ISSUE THREAD

**Issue by CWZ7605** [klever1988/nanopi-openwrt#46]
目前官方源的luci是新布局，而lean的是旧布局。
在lean版本上使用8821CU，看到的无线界面下方没有保存，应用之类的按钮，也无法打开无线安全界面。
大佬是否能解决？如需网卡，可无偿提供一个。

**Comment by iotsys** [comment]
[R2S.请问下mini固件支持usb无线网卡么？如果支持的话是些型号 #40](https://github.com/klever1988/nanopi-openwrt/issues/40)

**Comment by klever1988** [comment]
我去买个usb wifi吧。。

**Comment by klever1988** [comment]
已添加无线网卡支持，你可以测试了

**Comment by CWZ7605** [comment]
好的，感谢大佬！
