### ISSUE TITLE
在线更新脚本提示找不到resize2fs

### ISSUE THREAD

**Issue by nonozone** [klever1988/nanopi-openwrt#471]
![image](https://user-images.githubusercontent.com/1277444/112708942-4a03f280-8ef0-11eb-8c95-774a9ab69558.png)

**Comment by klever1988** [comment]
稍微有些麻烦

手动下载这个ipk并安装应该就可以

https://mirrors.tencent.com/lede/snapshots/packages/aarch64_generic/base/resize2fs_1.45.6-2_aarch64_generic.ipk


新版重新把resize2fs加入预装包了

**Comment by nonozone** [comment]
额，要安装个啥扩展才可以离线安装软件包吧？

**Comment by nonozone** [comment]
终端搞定，opkg install ...ipk
