### ISSUE TITLE
R4S可否集成显卡驱动？jellyfin必备

### ISSUE THREAD

**Issue by JSZMonkey** [klever1988/nanopi-openwrt#473]
R4S可否集成显卡驱动？jellyfin必备

**Comment by klever1988** [comment]
哈哈哈 你们消息可真灵啊

**Comment by JSZMonkey** [comment]
集成了吗？

**Comment by JSZMonkey** [comment]
怎么把驱动加到自己固件上？

**Comment by klever1988** [comment]
加了 试跑编译看看

**Comment by JSZMonkey** [comment]
试了没有 能行不？

**Comment by klever1988** [comment]
https://github.com/klever1988/nanopi-openwrt/commit/a625dfb87de433c3e5cab723d96b1f14d404fca3

已经加进去了，能不能用我就不知道了，没试

**Comment by amaztony** [comment]
slim版有docker吗

**Comment by klever1988** [comment]
> slim版有docker吗

slim版可以自己装docker的，内置的软件源很容易
