### ISSUE TITLE
一个安全问题

### ISSUE THREAD

**Issue by fanyusen1993** [klever1988/nanopi-openwrt#474]
路由器下同一个局域网下的终端访问这个地址http://192.168.1.1:7681/，都不用输入密码。。。。。。

**Comment by klever1988** [comment]
![image](https://user-images.githubusercontent.com/56048681/112731406-fdf99200-8f71-11eb-9659-8815aadef9f4.png)

不是有这个鉴权吗？

**Comment by fanyusen1993** [comment]
可能我的不是最新版本，我更新一下再看看

**Comment by fanyusen1993** [comment]
更新了最新的固件，好像网络接口配置不继承原来的，导致断网了一段时间。
我这里还是一样的现象，不需要输入密码，可能是我关闭了密码登录只允许密钥登陆导致的吧。
目前我在防火墙把这个端口关了，懒得折腾了。

**Comment by fanyusen1993** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/56048681/112731406-fdf99200-8f71-11eb-9659-8815aadef9f4.png)
> 
> 不是有这个鉴权吗？

更新了最新的固件，好像网络接口配置不继承原来的，导致断网了一段时间。
我这里还是一样的现象，不需要输入密码，可能是我关闭了密码登录只允许密钥登陆导致的吧。
目前我在防火墙把这个端口关了，懒得折腾了。
