### ISSUE TITLE
安装软件失败，but incompatible with the architectures configured，

### ISSUE THREAD

**Issue by hwdef** [klever1988/nanopi-openwrt#476]
![image](https://user-images.githubusercontent.com/13084946/112741349-9b2ae980-8fb7-11eb-8cdd-b456867fe60c.png)

**Comment by hwdef** [comment]
r2s

**Comment by klever1988** [comment]
几号的版本，我试过今天的没有问题

**Comment by hwdef** [comment]
我的也是是今天的，
r2s  slim版本，没联网。

**Comment by hwdef** [comment]
有些软件没问题，例如 chinadns，有的有问题，例如luci-app-ssr-plus

**Comment by klever1988** [comment]
要联网，有些插件的依赖需要联网才能安装到

**Comment by hwdef** [comment]
联网之后就可以了，感谢！
