### ISSUE TITLE
求助。。R2S终端内用在线升级脚本没反应

### ISSUE THREAD

**Issue by maiapig** [klever1988/nanopi-openwrt#496]
R2S终端内用在线升级脚本没反应，固件版本是ImmortalWrt 18.06-SNAPSHOT r9281+14-671443066 / LuCI openwrt-18.06 branch (git-21.060.52352-74ea004)，求大佬解答，万分感谢
![image](https://user-images.githubusercontent.com/38374633/113181321-348e2000-9284-11eb-8c3e-d75ae2574ae6.png)

**Comment by dalidaji** [comment]
wget -qO- https://ghproxy.com/https://raw.githubusercontent.com/klever1988/nanopi-openwrt/master/scripts/autoupdate.sh | sh

**Comment by maiapig** [comment]
> wget -qO- https://ghproxy.com/https://raw.githubusercontent.com/klever1988/nanopi-openwrt/master/scripts/autoupdate.sh | sh

。。确实可以了 看来是被墙了是吧 有什么办法可以让这个脚本走ssrplus+的代理吗

**Comment by klever1988** [comment]
github.io
github.com
githubapp.com
githubassets.com
githubusercontent.com
添加到“强制”

**Comment by maiapig** [comment]
> github.io
> github.com
> githubapp.com
> githubassets.com
> githubusercontent.com
> 添加到“强制”

啊这。。现在ssrp是英文版的了，“强制”是哪个选项啊，谢谢大佬
![image](https://user-images.githubusercontent.com/38374633/113514576-11c07c00-95a2-11eb-9906-bf7229f72e3b.png)

**Comment by TomFoxLee** [comment]
> 
> 
> > github.io
> > github.com
> > githubapp.com
> > githubassets.com
> > githubusercontent.com
> > 添加到“强制”
> 
> 啊这。。现在ssrp是英文版的了，“强制”是哪个选项啊，谢谢大佬

應該是 bypass domain list 那一塊。

另外你可以試試 "opkg update luci-i18n-ssr-plus-zh-cn" 看能不能把中文介面裝回來。。。
