### ISSUE TITLE
您好，和其他网友反映的一样，passwall和ssr无法使用

### ISSUE THREAD

**Issue by lyjhyjyes** [klever1988/nanopi-openwrt#501]
使用固件R2S-Minimal-2020-11-27-ROM，这几天忽然不能使用路由器passwall和ssr，而我的订阅链接在win10 v2ray客户端正常使用。
https://github.com/klever1988/nanopi-openwrt/issues/498 这里网友反馈也有问题。
当然9天前您的置顶帖说了不要问扶墙。
不方便回答可以关了帖子。
谢谢了，仅做反馈

**Comment by klever1988** [comment]
11-27 很可能是v2版本和服务端匹配不上了
31号的版本可能有bug 你可以换用今天的试试看
