### ISSUE TITLE
开启AdGuardHome去广告插件，网页转圈许久才加载完

### ISSUE THREAD

**Issue by dalidaji** [klever1988/nanopi-openwrt#503]
AdGuardHome：开启
规则：anti-AD
访问网站：cnbeta

**Comment by klever1988** [comment]
路由器指给你客户端（也就是电脑）的dns地址解析不畅 ，但具体卡在路由器内部哪个环节不好说，自己多尝试一些设置试一下吧

**Comment by dalidaji** [comment]
网络请求逻辑在客户端上，浏览器无法访问某些域名的资源，通过延长超时时间导致浏览器转圈许久。
