### ISSUE TITLE
请问带佬怎么自己扩容分区啊？

### ISSUE THREAD

**Issue by baby195lxl** [klever1988/nanopi-openwrt#506]
全插件的很多不太需要，安装silm版想自己装插件但安装几个之后就没有多少容量了，查了资料也没有找到怎么处理
![image](https://user-images.githubusercontent.com/48685934/113428044-abecbc80-9408-11eb-9957-2f04a80ade9a.png)

**Comment by klever1988** [comment]
卡拔下来用winddows+读卡器 
软件可以选择diskgenius

**Comment by baby195lxl** [comment]
好的，谢谢

**Comment by baby195lxl** [comment]
> 卡拔下来用winddows+读卡器
> 软件可以选择diskgenius
带佬，用diskgenius说"block bitmap中有标记为已使用的未用簇",用chkdsk报错"文件系统的类型是RAW，CHKDSK无法供RAW驱动器使用」"，这个和内存卡有关系吗

**Comment by caseysui** [comment]
> block bitmap中有标记为已使用的未用簇

你怎么解决的，我也遇到了这个问题。。。

**Comment by baby195lxl** [comment]
虚拟机安装Linux使用gparted

> > block bitmap中有标记为已使用的未用簇
> 
> 你怎么解决的，我也遇到了这个问题。。。离线扩容提示 block bitmap中有标记为已使用的未用簇

**Comment by klever1988** [comment]
> 虚拟机安装Linux使用gparted
> 
> > > block bitmap中有标记为已使用的未用簇
> > 
> > 
> > 你怎么解决的，我也遇到了这个问题。。。离线扩容提示 block bitmap中有标记为已使用的未用簇

其实用读卡器插到运行中openwrt也可以用cfdisk和resize2fs扩容，原先不知道每个用户linux基础怎么样，我都不知道怎么回答，只能从简

**Comment by baby195lxl** [comment]
> > 虚拟机安装Linux使用gparted
> > > > block bitmap中有标记为已使用的未用簇
> > > 
> > > 
> > > 你怎么解决的，我也遇到了这个问题。。。离线扩容提示 block bitmap中有标记为已使用的未用簇
> 
> 其实用读卡器插到运行中openwrt也可以用cfdisk和resize2fs扩容，原先不知道每个用户linux基础怎么样，我都不知道怎么回答，只能从简

谢谢带佬了
