### ISSUE TITLE
Ruby依赖异常

### ISSUE THREAD

**Issue by L1cardo** [klever1988/nanopi-openwrt#507]
r2s在开启openclash时，4.1，4.2的固件均提示Ruby依赖异常

3.28的固件没有此问题

我是使用自动更新脚本更新的

**Comment by klever1988** [comment]
ruby卸载重装试试

**Comment by EliceAM** [comment]
r4s 在线升级28号以后版本先遇到Capsh异常，请尝试重新安装依赖的问题重新安装libcap后，也出现提示ruby依赖异常的问题

**Comment by zufu2018zufu2018** [comment]
安装libcap-bin
