### ISSUE TITLE
lienol版本的怎么几天没更了？

### ISSUE THREAD

**Issue by Benjamin23333** [klever1988/nanopi-openwrt#53]
lienol版本的怎么几天没更了？我看到一个testcombined版本，刷进去发现是双L大杂交版本，酸酸乳和passwall都有，请问以后是不出单独的lienol版了么？

**Comment by klever1988** [comment]
lienol编译出现一点错误 正在修复

**Comment by kulanchong** [comment]
r2s  14号testcombined昨天刷了，在内网有ARP欺骗，重新写入也是，找不到原因，大佬检查下

**Comment by klever1988** [comment]
tesecombined只是测试用而已 不建议日常使用 合并两个大佬的插件我觉得有好多问题 所以一直没做合并 尝试玩玩而已
