### ISSUE TITLE
R4S固件CPU性能优化调节预设参数问题

### ISSUE THREAD

**Issue by niceluckyday** [klever1988/nanopi-openwrt#539]
4月9号的固件用卡刷预设如图,请问这是正常的吗？正常的就不管了
![image](https://user-images.githubusercontent.com/10098987/114275862-c0f3cc00-9a56-11eb-9f74-5fc715535b80.png)
![image](https://user-images.githubusercontent.com/10098987/114275865-c4875300-9a56-11eb-86a3-0a8a6176f02c.png)

**Comment by eagleonefight** [comment]
跟我的一样，我直接把 最大 选项 调到最大了
