### ISSUE TITLE
rtl8821CU 的驱动能不能移植到其他h5开发板的openwrt系统上

### ISSUE THREAD

**Issue by CMCCAdmin** [klever1988/nanopi-openwrt#56]
我手里有一个nanopi neo plus2，和一个rtl8811CU的usb网卡（rtl8821CU同驱动），刷的自编译的openwrt系统，怎么让openwrt系统支持这个网卡呢，google了好久都找不到方法。

**Comment by klever1988** [comment]
给你找好链接，试试看
https://blog.csdn.net/hailang5337/article/details/71158166
https://github.com/whitebatman2/rtl8821CU
