### ISSUE TITLE
装不上openclash

### ISSUE THREAD

**Issue by catbbc** [klever1988/nanopi-openwrt#59]
昨天316可以装openclash，今天317版又装不上了，mini版

**Comment by klever1988** [comment]
缺什么？

**Comment by catbbc** [comment]
重新写入又能装上了，估计网络不稳定，现在不翻都上不来github

**Comment by catbbc** [comment]
318装好openclash后启动不了，好像还缺依赖
2020-03-18 21:38:32 Config 【D】 Update Successful
/etc/rc.common: line 755: nohup: not found
2020-03-18 21:38:49 OpenClash Can Not Start, Please Check The Error Info And Try Again
/etc/rc.common: line 755: nohup: not found
2020-03-18 21:42:04 OpenClash Can Not Start, Please Check The Error Info And Try Again

**Comment by catbbc** [comment]
装上coreutils-nohup后成功启动

**Comment by klever1988** [comment]
318指的是哪个版本，我内置openclash的这个版本启动不起来吗？

**Comment by catbbc** [comment]
自动发布 R2S-Lean-2020-03-18
是这个，内置openclash的还没试过

**Comment by klever1988** [comment]
帮我试试，clash配置太麻烦了我都不想试

**Comment by catbbc** [comment]
OK正在下

**Comment by catbbc** [comment]
ok非常顺利直接更新内核运行就行了没有缺组件

**Comment by klever1988** [comment]
感谢

我预装的内核不是最新的吗？

**Comment by catbbc** [comment]
好像是的和每天刷你固件一样就是手痒

**Comment by klever1988** [comment]
哈哈哈
