### ISSUE TITLE
R4S固件端口转发不生效

### ISSUE THREAD

**Issue by hiethan** [klever1988/nanopi-openwrt#611]
需要将局域网里NAS做端口转发挂PT，但是在防火墙里设置了转发完全不起作用
在防火墙里添加iptables -t nat -I PREROUTING -i pppoe-wan -p udp --dport 51413 -j DNAT --to-destination 10.0.0.10:51413同样不生效
关闭流量分载还是不生效
第一次用这个系统，其他功能都很好用，速度也很快，就是这个端口转发很头疼

**Comment by klever1988** [comment]
试试

![image](https://user-images.githubusercontent.com/56048681/117413221-48ded000-af48-11eb-8889-3da7a5fdd82c.png)

**Comment by hiethan** [comment]
你的设置我之前试过没能成功，后面把全部设备改了网段解决了，很是奇怪，期间自查多次设置没有问题，遇到同样问题的朋友可以试试改网段！
