### ISSUE TITLE
更新2021/5/21版本后haproxy消失

### ISSUE THREAD

**Issue by jimmyk1m** [klever1988/nanopi-openwrt#637]
如题，负载均衡菜单等消失，系统报错
================================
找不到 haproxy，无法启动...
haproxy -f /var/etc/passwall/haproxy/config.cfg

**Comment by klever1988** [comment]
默认不含haproxy，你需要使用slim自己装一下haproxy

**Comment by jimmyk1m** [comment]
感谢，手工安装Haproxy可用了，我装的是with docker，可能是更新的时候出了啥差错
