### ISSUE TITLE
不管哪个版本，现在新刷的都不能开启FULLCONE NAT加速

### ISSUE THREAD

**Issue by gfx1980** [klever1988/nanopi-openwrt#64]
不管哪个版本，现在新刷的都不能开启FULLCONE NAT加速，麻烦大神解决一下，谢谢

**Comment by klever1988** [comment]
r1s不可以 沒有打補丁

r2s沒有問題

**Comment by gfx1980** [comment]
我就是r2s啊，如果刷了新的，直接开启不了，但是用以前的备份来恢复就可以开启，我刷了不下5次，两个大神的还有mini的都是这样

**Comment by q943613777** [comment]
> r1s不可以 沒有打補丁
> 
> r2s沒有問題

r1s h3能打个补丁不。

**Comment by klever1988** [comment]
不打补丁也不影响跑到350M的硬件极限啊

**Comment by klever1988** [comment]
> 我就是r2s啊，如果刷了新的，直接开启不了，但是用以前的备份来恢复就可以开启，我刷了不下5次，两个大神的还有mini的都是这样

刷新固件之前格式化一下内存卡，不要快速格式化

**Comment by gfx1980** [comment]
> 内

哦，我试试不用快速格式化
