### ISSUE TITLE
您好请问 包含19.07 这个版本吗？

### ISSUE THREAD

**Issue by baojiliu** [klever1988/nanopi-openwrt#645]

**Comment by baojiliu** [comment]
https://openwrt.org/docs/guide-user/services/vpn/openvpn/client-luci#b_upload_a_openvpn_config_file
请问这个featue，是不是要重新编译

**Comment by minkaka** [comment]
同问，19.07 安装的openvpn 版本和现在的不一样，配置也更方便。
