### ISSUE TITLE
5.28版本，修改wifi之后，无线就无法再打开

### ISSUE THREAD

**Issue by hwdef** [klever1988/nanopi-openwrt#660]
例如只修改一个名字，从Openwrt修改为test ，无限状态就变为`无线未开启或未关联`

![image](https://user-images.githubusercontent.com/13084946/120157419-94258f00-c225-11eb-8e91-5c98f7eec08d.png)

**Comment by hwdef** [comment]
rtl8811cu，

刷完固件，不做任何修改，wifi是正常的。

**Comment by hwdef** [comment]
重试几次之后，又好了，，暂不清楚如何100%触发

**Comment by klever1988** [comment]
修改wifi设置之后 需要重启才能激活的 无解

**Comment by hwdef** [comment]
有时候重启也没用，就改几次无关的设置，说不定改哪次之后就成功了。。。。

**Comment by klever1988** [comment]
https://github.com/klever1988/nanopi-openwrt/raw/master/usb-wifi.sh

你可以用这个

**Comment by hwdef** [comment]
好的，谢谢
