### ISSUE TITLE
请教NanoPi R1 的编译

### ISSUE THREAD

**Issue by Tigerlee100307** [klever1988/nanopi-openwrt#68]
能出一个NanoPi R1 的编译吗，我看到里面有Nanopi R1s H3，但是不知道固件是否通用？

**Comment by Tigerlee100307** [comment]
看到以前的问题了，可以刷Nanopi R1s H3版，我试了一下，可以启动，但是无线连接上后，不能上网，里面SSR+测试可以连接国外和国内。

**Comment by klever1988** [comment]
你是说无线ap模式还是客户端模式？

**Comment by Tigerlee100307** [comment]
是无线ap模式，Wan 口是DHCP客户端，电脑连接上后不能上网

**Comment by klever1988** [comment]
无线网卡的防火墙应该设置为lan区域

**Comment by Tigerlee100307** [comment]
> 无线网卡的防火墙应该设置为lan区域

好像设置的是Lan口，我晚上再确认一下，
另外大佬，有个请求，能赐教一下编译NanoPi R1的教程吗？我也想学习一下自己编译，不知大佬是否愿意？

**Comment by klever1988** [comment]
编译过程你看yml就足够了呀

**Comment by Tigerlee100307** [comment]
问题已经解决
