### ISSUE TITLE
可否在R2S-Lienol 版上增加ShadowsocksR Python 服务器

### ISSUE THREAD

**Issue by kwzz03** [klever1988/nanopi-openwrt#69]
可否在R2S-Lienol 版上增加ShadowsocksR Python 服务器？

喜欢用PASSWALL。但外出又要连接回家里。谢谢

**Comment by klever1988** [comment]
https://github.com/Lienol/openwrt-package/tree/master/lienol/luci-app-ssr-libev-server
这个是不是

**Comment by kwzz03** [comment]
对。是你发连接的那个。SSRP在R2S上用着速度没PASSALL快。
你LEAN的固件上有这个。在VPN里SSR Python 服务器

**Comment by klever1988** [comment]
好的已经加入
