### ISSUE TITLE
异常断电之后磁盘只读

### ISSUE THREAD

**Issue by yanyu469** [klever1988/nanopi-openwrt#698]
扩容了/之后有次异常断电，开机之后根目录挂载为只读模式，用了网上的方式都无效。无法修改应用配置。
只能重新刷机。

**Comment by klever1988** [comment]
因为异常关机分区会被标记为只读  必须把tf卡挂载到其他运行linux的主机或者虚拟机也行 用e2fsck修复分区才可以

**Comment by knaffe** [comment]
> 因为异常关机分区会被标记为只读 必须把tf卡挂载到其他运行linux的主机或者虚拟机也行 用e2fsck修复分区才可以
 这个具体怎么操作呢？
