### ISSUE TITLE
能否你在的minimal版加入softether VPN插件

### ISSUE THREAD

**Issue by stevenlinfeng** [klever1988/nanopi-openwrt#70]
你的minimal版性能不错。不过觉得lean版太臃肿，插件太多，96%都用不到。能否你在的minimal版加入softether VPN。因为有时候在外需要通过VPN连接回家。那么minimal版加入softether VPN我觉比较好，因为对于大多数而然，有softether VPN连接回家，SSRPLUS出国。那就够了

**Comment by klever1988** [comment]
肥版加入ok不 然后你再慢慢去砍掉不用的包

**Comment by king050203** [comment]
minimal版已经补上kmod-tun，softether VPN可以自行从openwrt官方源安装
