### ISSUE TITLE
17和21号R1s h3固件的Turbo ACC 网络加速设置运行不了

### ISSUE THREAD

**Issue by q943613777** [klever1988/nanopi-openwrt#71]
![image](https://user-images.githubusercontent.com/53282874/77243188-5355e180-6c42-11ea-9704-5ab25339d2f4.png)

我记得大佬前几个固件DNS加速是可以的。但17和21号更新的固件DNS运行不了。

**Comment by klever1988** [comment]
r1s是一直不能开加速的 这个设备开不开加速没什么影响啦

**Comment by q943613777** [comment]
> r1s是一直不能开加速的 这个设备开不开加速没什么影响啦

好吧。我记得之前更新的几次固件DNS加速是可以开启的。最近发现17号和21号的不行了。
还有我发现21号的固件貌似跟之前前几次更新的固件不一样了。少了一些我用不上的插件。
请问大佬21号更新的r1s h3的固件是做了什么改动吗

**Comment by klever1988** [comment]
你帮我比较一下不同日期固件包的.config异同
工具可以考虑用这个
https://www.diffchecker.com/

**Comment by q943613777** [comment]
0321-0317  https://www.diffchecker.com/ViGYdowc
0321-0313  https://www.diffchecker.com/m1hfi5Dr
0321-0311  https://www.diffchecker.com/4b3beIIf
0321-0310  https://www.diffchecker.com/LJoc8V0l

**Comment by q943613777** [comment]
> 你帮我比较一下不同日期固件包的.config异同
> 工具可以考虑用这个
> https://www.diffchecker.com/

0321-0317 https://www.diffchecker.com/ViGYdowc
0321-0313 https://www.diffchecker.com/m1hfi5Dr
0321-0311 https://www.diffchecker.com/4b3beIIf
0321-0310 https://www.diffchecker.com/LJoc8V0l

**Comment by klever1988** [comment]
我看了一下21号flowoffload插件dnscache的基础包pdnsd有编译到了
另外bbr应该能用啊，内核是支持的，你进ssh用lsmod | grep bbr我看看

**Comment by klever1988** [comment]
试试把卡格式化一下（普通不要快速），然后重新刷一遍试试

**Comment by q943613777** [comment]
> 试试把卡格式化一下（普通不要快速），然后重新刷一遍试试

每次更新固件之后会把卡给格式化，所以这个操作是有做到的

**Comment by q943613777** [comment]
> 我看了一下21号flowoffload插件dnscache的基础包pdnsd有编译到了
> 另外bbr应该能用啊，内核是支持的，你进ssh用lsmod | grep bbr我看看

这个要晚上回去看

**Comment by q943613777** [comment]
> 我看了一下21号flowoffload插件dnscache的基础包pdnsd有编译到了
> 另外bbr应该能用啊，内核是支持的，你进ssh用lsmod | grep bbr我看看

貌似我用了这个指令没反应

**Comment by klever1988** [comment]
那lsmod呢

**Comment by q943613777** [comment]
> 那lsmod呢


BusyBox v1.30.0 () built-in shell (ash)

  ___    _             _ _    __      _____ _____ 
 | __| _(_)___ _ _  __| | |_  \ \    / / _ \_   _|
 | _| '_| / -_) ' \/ _` | | || \ \/\/ /|   / | |  
 |_||_| |_\___|_||_\__,_|_|\_, |\_/\_/ |_|_\ |_|  
                           |__/                  
 -----------------------------------------------------
 FriendlyWRT SNAPSHOT, r0+2356-c763bf85d9
 -----------------------------------------------------

DYC Build

root@FriendlyWrt:~# lsmod
8189es               1024000  0 
8821cu               1683456  0 
ah4                    16384  0 
ah6                    16384  0 
authenc                16384  0 
brcmfmac              180224  0 
brcmutil               16384  1 brcmfmac
bridge                 94208  0 
cdc_ether              16384  0 
deflate                16384  0 
echainiv               16384  0 
esp4                   20480  0 
esp6                   20480  0 
ip_set                 32768 16 xt_set,ip_set_list_set,ip_set_hash_netportnet,ip_set_hash_netport,ip_set_hash_netnet,ip_set_hash_netiface,ip_set_hash_net,ip_set_hash_mac,ip_set_hash_ipportnet,ip_set_hash_ipportip,ip_set_hash_ipport,ip_set_hash_ipmark,ip_set_hash_ip,ip_set_bitmap_port,ip_set_bitmap_ipmac,ip_set_bitmap_ip
ip_set_bitmap_ip       20480  0 
ip_set_bitmap_ipmac    20480  0 
ip_set_bitmap_port     20480  0 
ip_set_hash_ip         32768  1 
ip_set_hash_ipmark     32768  2 
ip_set_hash_ipport     32768  0 
ip_set_hash_ipportip   32768  0 
ip_set_hash_ipportnet   36864  0 
ip_set_hash_mac        20480  0 
ip_set_hash_net        32768  9 
ip_set_hash_netiface   36864  0 
ip_set_hash_netnet     36864  0 
ip_set_hash_netport    36864  0 
ip_set_hash_netportnet   36864  0 
ip_set_list_set        20480  2 
ip_tables              24576  5 iptable_nat,iptable_raw,iptable_mangle,iptable_filter
ip_tunnel              24576  1 sit
ip6_tables             24576 30 ip6table_nat,ip6table_mangle,ip6table_filter
ip6t_MASQUERADE        16384  0 
ip6t_NPT               16384  0 
ip6t_REJECT            16384  2 
ip6table_filter        16384  1 
ip6table_mangle        16384  1 
ip6table_nat           16384  0 
ipcomp                 16384  0 
ipcomp6                16384  0 
ipt_ECN                16384  0 
ipt_MASQUERADE         16384  2 
ipt_REJECT             16384  2 
ipt_ah                 16384  0 
iptable_filter         16384  1 
iptable_mangle         16384  1 
iptable_nat            16384  1 
iptable_raw            16384  1 
llc                    16384  2 bridge,stp
nf_conntrack           94208 36 nf_nat_pptp,nf_conntrack_pptp,ipt_MASQUERADE,xt_state,xt_nat,xt_helper,xt_conntrack,xt_connmark,xt_connlimit,xt_connbytes,xt_REDIRECT,xt_CT,nf_nat_tftp,nf_nat_snmp_basic,nf_nat_sip,nf_nat_masquerade_ipv4,nf_nat_irc,nf_conntrack_ipv4,nf_nat_ipv4,nf_nat_h323,nf_nat_ftp,nf_nat_amanda,nf_conntrack_tftp,nf_conntrack_snmp,nf_conntrack_sip,nf_conntrack_proto_gre,nf_conntrack_netlink,nf_conntrack_irc,nf_conntrack_h323,nf_conntrack_ftp,nf_conntrack_broadcast,nf_conntrack_amanda,nf_conntrack_ipv6,nf_nat_ipv6,nf_nat_masquerade_ipv6,nf_nat
nf_conntrack_amanda    16384  2 nf_nat_amanda
nf_conntrack_broadcast   16384  1 nf_conntrack_snmpnf_conntrack_ftp       16384  2 nf_nat_ftp
nf_conntrack_h323      45056  3 nf_nat_h323
nf_conntrack_ipv4      16384 43 
nf_conntrack_ipv6      16384 13 
nf_conntrack_irc       16384  2 nf_nat_irc
nf_conntrack_netlink   32768  0 
nf_conntrack_pptp      16384  2 nf_nat_pptp
nf_conntrack_proto_gre   16384  1 nf_conntrack_pptpnf_conntrack_sip       24576  3 nf_nat_sip
nf_conntrack_snmp      16384  2 nf_nat_snmp_basic
nf_conntrack_tftp      16384  2 nf_nat_tftp
nf_defrag_ipv4         16384  2 xt_TPROXY,nf_conntrack_ipv4
nf_defrag_ipv6         16384  2 xt_TPROXY,nf_conntrack_ipv6
nf_log_common          16384  2 nf_log_ipv4,nf_log_ipv6
nf_log_ipv4            16384  0 
nf_log_ipv6            16384  0 
nf_nat                 24576 14 nf_nat_pptp,xt_nat,nf_nat_tftp,nf_nat_sip,nf_nat_redirect,nf_nat_proto_gre,nf_nat_masquerade_ipv4,nf_nat_irc,nf_nat_ipv4,nf_nat_h323,nf_nat_ftp,nf_nat_amanda,nf_nat_ipv6,nf_nat_masquerade_ipv6
nf_nat_amanda          16384  0 
nf_nat_ftp             16384  0 
nf_nat_h323            16384  0 
nf_nat_ipv4            16384  1 iptable_nat
nf_nat_ipv6            16384  1 ip6table_nat
nf_nat_irc             16384  0 
nf_nat_masquerade_ipv4   16384  1 ipt_MASQUERADE
nf_nat_masquerade_ipv6   16384  1 ip6t_MASQUERADE
nf_nat_pptp            16384  0 
nf_nat_proto_gre       16384  1 nf_nat_pptp
nf_nat_redirect        16384  1 xt_REDIRECT
nf_nat_sip             20480  0 
nf_nat_snmp_basic      20480  0 
nf_nat_tftp            16384  0 
nf_reject_ipv4         16384  1 ipt_REJECT
nf_reject_ipv6         16384  1 ip6t_REJECT
nf_socket_ipv4         16384  0 
nf_socket_ipv6         16384  0 
nfnetlink              16384  4 nf_conntrack_netlink,ip_set
nls_ascii              16384  1 
r8152                  45056  0 
rtc_sunxi              16384  0 
rtl_usb                20480  1 rtl8192cu
rtl8192c_common        49152  1 rtl8192cu
rtl8192cu              81920  0 
rtl8xxxu               81920  0 
rtlwifi                73728  3 rtl8192cu,rtl8192c_common,rtl_usb
sit                    24576  0 
stp                    16384  1 bridge
ts_bm                  16384  0 
ts_fsm                 16384  0 
ts_kmp                 16384  5 
tunnel4                16384  2 sit,xfrm4_tunnel
tunnel6                16384  1 xfrm6_tunnel
x_tables               20480 46 ipt_REJECT,ipt_MASQUERADE,xt_time,xt_tcpudp,xt_tcpmss,xt_statistic,xt_state,xt_recent,xt_policy,xt_nat,xt_multiport,xt_mark,xt_mac,xt_limit,xt_length,xt_hl,xt_helper,xt_esp,xt_ecn,xt_dscp,xt_conntrack,xt_connmark,xt_connlimit,xt_connbytes,xt_comment,xt_TPROXY,xt_TCPMSS,xt_REDIRECT,xt_LOG,xt_HL,xt_DSCP,xt_CT,xt_CLASSIFY,iptable_raw,iptable_mangle,iptable_filter,ipt_ah,ipt_ECN,ip_tables,xt_set,ip6t_NPT,ip6t_MASQUERADE,ip6table_mangle,ip6table_filter,ip6_tables,ip6t_REJECT
xfrm_ipcomp            16384  2 ipcomp6,ipcomp
xfrm4_mode_beet        16384  0 
xfrm4_mode_transport   16384  0 
xfrm4_mode_tunnel      16384  0 
xfrm4_tunnel           16384  0 
xfrm6_mode_beet        16384  0 
xfrm6_mode_transport   16384  0 
xfrm6_mode_tunnel      16384  0 
xfrm6_tunnel           16384  1 ipcomp6
xradio_wlan           110592  0 
xt_CLASSIFY            16384  0 
xt_CT                  16384 10 
xt_DSCP                16384  0 
xt_HL                  16384  0 
xt_LOG                 16384  0 
xt_REDIRECT            16384 11 
xt_TCPMSS              16384  4 
xt_TPROXY              16384  0 
xt_comment             16384213 
xt_connbytes           16384  0 
xt_connlimit           16384  0 
xt_connmark            16384  4 
xt_conntrack           16384 26 
xt_dscp                16384  0 
xt_ecn                 16384  0 
xt_esp                 16384  0 
xt_helper              16384  0 
xt_hl                  16384  0 
xt_length              16384  0 
xt_limit               16384 20 
xt_mac                 16384  0 
xt_mark                16384 38 
xt_multiport           16384  6 
xt_nat                 16384  1 
xt_policy              16384  4 
xt_recent              20480  0 
xt_set                 20480 27 
xt_state               16384  0 
xt_statistic           16384  0 
xt_tcpmss              16384  0 
xt_tcpudp              16384 42 
xt_time                16384  0 
root@FriendlyWrt:~# lsmod

**Comment by q943613777** [comment]
> 那lsmod呢



BusyBox v1.30.0 () built-in shell (ash)

  ___    _             _ _    __      _____ _____ 
 | __| _(_)___ _ _  __| | |_  \ \    / / _ \_   _|
 | _| '_| / -_) ' \/ _` | | || \ \/\/ /|   / | |  
 |_||_| |_\___|_||_\__,_|_|\_, |\_/\_/ |_|_\ |_|  
                           |__/                  
 -----------------------------------------------------
 FriendlyWRT SNAPSHOT, r0+2356-c763bf85d9
 -----------------------------------------------------

DYC Build

root@FriendlyWrt:~# lsmod
8189es               1024000  0 
8821cu               1683456  0 
ah4                    16384  0 
ah6                    16384  0 
authenc                16384  0 
brcmfmac              180224  0 
brcmutil               16384  1 brcmfmac
bridge                 94208  0 
cdc_ether              16384  0 
deflate                16384  0 
echainiv               16384  0 
esp4                   20480  0 
esp6                   20480  0 
ip_set                 32768 16 xt_set,ip_set_list_set,ip_set_hash_netportnet,ip_set_hash_netport,ip_set_hash_netnet,ip_set_hash_netiface,ip_set_hash_net,ip_set_hash_mac,ip_set_hash_ipportnet,ip_set_hash_ipportip,ip_set_hash_ipport,ip_set_hash_ipmark,ip_set_hash_ip,ip_set_bitmap_port,ip_set_bitmap_ipmac,ip_set_bitmap_ip
ip_set_bitmap_ip       20480  0 
ip_set_bitmap_ipmac    20480  0 
ip_set_bitmap_port     20480  0 
ip_set_hash_ip         32768  1 
ip_set_hash_ipmark     32768  2 
ip_set_hash_ipport     32768  0 
ip_set_hash_ipportip   32768  0 
ip_set_hash_ipportnet   36864  0 
ip_set_hash_mac        20480  0 
ip_set_hash_net        32768  9 
ip_set_hash_netiface   36864  0 
ip_set_hash_netnet     36864  0 
ip_set_hash_netport    36864  0 
ip_set_hash_netportnet   36864  0 
ip_set_list_set        20480  2 
ip_tables              24576  5 iptable_nat,iptable_raw,iptable_mangle,iptable_filter
ip_tunnel              24576  1 sit
ip6_tables             24576 30 ip6table_nat,ip6table_mangle,ip6table_filter
ip6t_MASQUERADE        16384  0 
ip6t_NPT               16384  0 
ip6t_REJECT            16384  2 
ip6table_filter        16384  1 
ip6table_mangle        16384  1 
ip6table_nat           16384  0 
ipcomp                 16384  0 
ipcomp6                16384  0 
ipt_ECN                16384  0 
ipt_MASQUERADE         16384  2 
ipt_REJECT             16384  2 
ipt_ah                 16384  0 
iptable_filter         16384  1 
iptable_mangle         16384  1 
iptable_nat            16384  1 
iptable_raw            16384  1 
llc                    16384  2 bridge,stp
nf_conntrack           94208 36 nf_nat_pptp,nf_conntrack_pptp,ipt_MASQUERADE,xt_state,xt_nat,xt_helper,xt_conntrack,xt_connmark,xt_connlimit,xt_connbytes,xt_REDIRECT,xt_CT,nf_nat_tftp,nf_nat_snmp_basic,nf_nat_sip,nf_nat_masquerade_ipv4,nf_nat_irc,nf_conntrack_ipv4,nf_nat_ipv4,nf_nat_h323,nf_nat_ftp,nf_nat_amanda,nf_conntrack_tftp,nf_conntrack_snmp,nf_conntrack_sip,nf_conntrack_proto_gre,nf_conntrack_netlink,nf_conntrack_irc,nf_conntrack_h323,nf_conntrack_ftp,nf_conntrack_broadcast,nf_conntrack_amanda,nf_conntrack_ipv6,nf_nat_ipv6,nf_nat_masquerade_ipv6,nf_nat
nf_conntrack_amanda    16384  2 nf_nat_amanda
nf_conntrack_broadcast   16384  1 nf_conntrack_snmpnf_conntrack_ftp       16384  2 nf_nat_ftp
nf_conntrack_h323      45056  3 nf_nat_h323
nf_conntrack_ipv4      16384 43 
nf_conntrack_ipv6      16384 13 
nf_conntrack_irc       16384  2 nf_nat_irc
nf_conntrack_netlink   32768  0 
nf_conntrack_pptp      16384  2 nf_nat_pptp
nf_conntrack_proto_gre   16384  1 nf_conntrack_pptpnf_conntrack_sip       24576  3 nf_nat_sip
nf_conntrack_snmp      16384  2 nf_nat_snmp_basic
nf_conntrack_tftp      16384  2 nf_nat_tftp
nf_defrag_ipv4         16384  2 xt_TPROXY,nf_conntrack_ipv4
nf_defrag_ipv6         16384  2 xt_TPROXY,nf_conntrack_ipv6
nf_log_common          16384  2 nf_log_ipv4,nf_log_ipv6
nf_log_ipv4            16384  0 
nf_log_ipv6            16384  0 
nf_nat                 24576 14 nf_nat_pptp,xt_nat,nf_nat_tftp,nf_nat_sip,nf_nat_redirect,nf_nat_proto_gre,nf_nat_masquerade_ipv4,nf_nat_irc,nf_nat_ipv4,nf_nat_h323,nf_nat_ftp,nf_nat_amanda,nf_nat_ipv6,nf_nat_masquerade_ipv6
nf_nat_amanda          16384  0 
nf_nat_ftp             16384  0 
nf_nat_h323            16384  0 
nf_nat_ipv4            16384  1 iptable_nat
nf_nat_ipv6            16384  1 ip6table_nat
nf_nat_irc             16384  0 
nf_nat_masquerade_ipv4   16384  1 ipt_MASQUERADE
nf_nat_masquerade_ipv6   16384  1 ip6t_MASQUERADE
nf_nat_pptp            16384  0 
nf_nat_proto_gre       16384  1 nf_nat_pptp
nf_nat_redirect        16384  1 xt_REDIRECT
nf_nat_sip             20480  0 
nf_nat_snmp_basic      20480  0 
nf_nat_tftp            16384  0 
nf_reject_ipv4         16384  1 ipt_REJECT
nf_reject_ipv6         16384  1 ip6t_REJECT
nf_socket_ipv4         16384  0 
nf_socket_ipv6         16384  0 
nfnetlink              16384  4 nf_conntrack_netlink,ip_set
nls_ascii              16384  1 
r8152                  45056  0 
rtc_sunxi              16384  0 
rtl_usb                20480  1 rtl8192cu
rtl8192c_common        49152  1 rtl8192cu
rtl8192cu              81920  0 
rtl8xxxu               81920  0 
rtlwifi                73728  3 rtl8192cu,rtl8192c_common,rtl_usb
sit                    24576  0 
stp                    16384  1 bridge
ts_bm                  16384  0 
ts_fsm                 16384  0 
ts_kmp                 16384  5 
tunnel4                16384  2 sit,xfrm4_tunnel
tunnel6                16384  1 xfrm6_tunnel
x_tables               20480 46 ipt_REJECT,ipt_MASQUERADE,xt_time,xt_tcpudp,xt_tcpmss,xt_statistic,xt_state,xt_recent,xt_policy,xt_nat,xt_multiport,xt_mark,xt_mac,xt_limit,xt_length,xt_hl,xt_helper,xt_esp,xt_ecn,xt_dscp,xt_conntrack,xt_connmark,xt_connlimit,xt_connbytes,xt_comment,xt_TPROXY,xt_TCPMSS,xt_REDIRECT,xt_LOG,xt_HL,xt_DSCP,xt_CT,xt_CLASSIFY,iptable_raw,iptable_mangle,iptable_filter,ipt_ah,ipt_ECN,ip_tables,xt_set,ip6t_NPT,ip6t_MASQUERADE,ip6table_mangle,ip6table_filter,ip6_tables,ip6t_REJECT
xfrm_ipcomp            16384  2 ipcomp6,ipcomp
xfrm4_mode_beet        16384  0 
xfrm4_mode_transport   16384  0 
xfrm4_mode_tunnel      16384  0 
xfrm4_tunnel           16384  0 
xfrm6_mode_beet        16384  0 
xfrm6_mode_transport   16384  0 
xfrm6_mode_tunnel      16384  0 
xfrm6_tunnel           16384  1 ipcomp6
xradio_wlan           110592  0 
xt_CLASSIFY            16384  0 
xt_CT                  16384 10 
xt_DSCP                16384  0 
xt_HL                  16384  0 
xt_LOG                 16384  0 
xt_REDIRECT            16384 11 
xt_TCPMSS              16384  4 
xt_TPROXY              16384  0 
xt_comment             16384213 
xt_connbytes           16384  0 
xt_connlimit           16384  0 
xt_connmark            16384  4 
xt_conntrack           16384 26 
xt_dscp                16384  0 
xt_ecn                 16384  0 
xt_esp                 16384  0 
xt_helper              16384  0 
xt_hl                  16384  0 
xt_length              16384  0 
xt_limit               16384 20 
xt_mac                 16384  0 
xt_mark                16384 38 
xt_multiport           16384  6 
xt_nat                 16384  1 
xt_policy              16384  4 
xt_recent              20480  0 
xt_set                 20480 27 
xt_state               16384  0 
xt_statistic           16384  0 
xt_tcpmss              16384  0 
xt_tcpudp              16384 42 
xt_time                16384  0 
root@FriendlyWrt:~# lsmod

**Comment by klever1988** [comment]
modprobe tcp_bbr
试试看

**Comment by klever1988** [comment]
试一下今天新编译的版本能开不

**Comment by q943613777** [comment]
> 试一下今天新编译的版本能开不

好，晚上回去试

**Comment by q943613777** [comment]
> 试一下今天新编译的版本能开不

今天编译的版本，DNS加速又可以运行起来了
![image](https://user-images.githubusercontent.com/53282874/77435512-5a851700-6e1d-11ea-9a1b-f4ae23b0ee7a.png)

**Comment by q943613777** [comment]
> 试一下今天新编译的版本能开不

今天编译的版本试了modprobe tcp_bbr指令，貌似没啥反应
![image](https://user-images.githubusercontent.com/53282874/77435652-84d6d480-6e1d-11ea-9153-19ac6d39840b.png)

**Comment by klever1988** [comment]
![image](https://user-images.githubusercontent.com/56048681/77506450-d96f6380-6ea0-11ea-8329-88e0563fa37c.png)
这两项建议关闭
bbr已经加入内核支持
下载最新版试试看

**Comment by q943613777** [comment]
> ![image](https://user-images.githubusercontent.com/56048681/77506450-d96f6380-6ea0-11ea-8329-88e0563fa37c.png)
> 这两项建议关闭
> bbr已经加入内核支持
> 下载最新版试试看

刷了今天更新的R1s h3的固件，可以运行DNS加速和BBR 加速了
![image](https://user-images.githubusercontent.com/53282874/77533464-df316d00-6ed1-11ea-9ec7-f96323d1b53e.png)

**Comment by q943613777** [comment]
> ![image](https://user-images.githubusercontent.com/56048681/77506450-d96f6380-6ea0-11ea-8329-88e0563fa37c.png)
> 这两项建议关闭
> bbr已经加入内核支持
> 下载最新版试试看

大神，发现个问题
开启bbr之后，貌似会影响我二级路由器的wifi功能。具体表现就是移动设备上不了网。关闭之后就恢复正常。

**Comment by klever1988** [comment]
bbr对wifi确实是有负优化的 网上有讨论

**Comment by q943613777** [comment]
> bbr对wifi确实是有负优化的 网上有讨论

好吧。那就是无解了
