### ISSUE TITLE
r2s加一个usb无线网卡只能激发2.4g或者5g wifi的一种嘛？

### ISSUE THREAD

**Issue by testnobody** [klever1988/nanopi-openwrt#713]
淘宝买了个支持usb3.0的2.4ghz+5ghz无线网卡，刷了固件安装对应的驱动后成功发出wifi，5g wifi下本地500mbps宽带跑满，屋里设备不多的情况下还是不错的，减去一个ap设备。
有个问题是我只能选择开启2.4g或者5g，同时开就gg，有时候直接强制重启，系统都进不去。是usb网卡的问题还是系统的问题呢

**Comment by otaku525** [comment]
应该是只能同时开启一个        r2s就一个usb2.0    你lan口接个ap不好吗

**Comment by testnobody** [comment]
确实只能开一个，嘿嘿嘿，不是折腾吗
感觉性能过剩，加个无线网卡也能带动，还行
