### ISSUE TITLE
如何自编译silm版本

### ISSUE THREAD

**Issue by hwdef** [klever1988/nanopi-openwrt#734]
fork之后再action手动编译，release中没有slim版本

**Comment by messense** [comment]
https://github.com/klever1988/nanopi-openwrt/blob/94388c4eb6dedfcfedcbcfc5e3418b19289d4f11/.github/workflows/lo-test.yml#L165 下面增加一行：`if: always()`

**Comment by hwdef** [comment]
@messense 好的，谢谢
