### ISSUE TITLE
我不能启动 docker 了

### ISSUE THREAD

**Issue by SpaceCZ** [klever1988/nanopi-openwrt#754]
我在 6.1 日的版本中使用了 r2s-with-docker，但是后续发现稳定性较差，于是我在今天更新了它，我仍然完全使用的默认配置但是 docker 守护程序无法打开，提示 Please input the SOCKET PATH of docker daemon！在配置中使用的是默认的 /var/run/docker.sock

**Comment by SpaceCZ** [comment]
我发现在  /var/run/docker.sock 这个位置并没有 docker.sock。我在正在新建文件并尝试是否可行

**Comment by sdmkjz** [comment]
> 我发现在 /var/run/docker.sock 这个位置并没有 docker.sock。我在正在新建文件并尝试是否可行

换silm版本 我已经尝试过了 with-docker版本的CE引擎有问题 如果你有安装源 自己安装上就行了 如果找不到安装源 那就换silm版本的 这个问题在七月中旬的版本就已经存在了 我也发过一次Issues

**Comment by hans362** [comment]
https://github.com/klever1988/nanopi-openwrt/issues/722#issuecomment-881990993

**Comment by SpaceCZ** [comment]
好的，感谢
