### ISSUE TITLE
关于自行修改配置问题

### ISSUE THREAD

**Issue by GimmGoo** [klever1988/nanopi-openwrt#79]
你好，我想使用您的脚本编译自己想要的固件，也就是有一些我不用的插件我想不要，然后我fork以后，在仓库添加了带 gist权限的token，然后修改了yml中的 if条件，但是编译不成功，不会release，请问我该怎么修改，还有应该用带有什么权限的token啊？

**Comment by klever1988** [comment]
https://github.com/coolsnowwolf/lede/blob/master/.github/workflows/openwrt-ci.yml

你可以改成upload artifact就不需要token了
参考它最后两段
