### ISSUE TITLE
关于自编译的一些问题

### ISSUE THREAD

**Issue by MilesPoupart** [klever1988/nanopi-openwrt#790]
1. 向config.seed文件中添加软件是否需要考虑到依赖？
比如我添加了
CONFIG_PACKAGE_luci-app-socat=y
需要同时添加
CONFIG_PACKAGE_socat=y吗？还是说相关依赖是可以自动获取编译的？

2. 是否不需要单独考虑app语言包？
粗略看了一下fork后的actions配置文件，比如在添加
CONFIG_PACKAGE_luci-app-socat=y
时，似乎会同时加入了CONFIG_PACKAGE_luci-i18n-socat-zh-cn=y，因此就无需在config.seed中单独添加了？
这样是否会导致如luci-app-xlnetacc之类没有相应语言包的app产生问题？

3. dockerd相关
目前的docker版本镜像似乎都存在dockerd无法正常运行，需要强制重装的问题，如 #722
如果在config.seed中加入CONFIG_PACKAGE_dockerd=y是否有望解决这一问题？加入这一句后是否会导致编译后的slim等版本中也出现dockerd？

谢谢！

**Comment by klever1988** [comment]
1，不需要，会自动获取依赖
2，如果发现中文语言包，会自动随插件安装
3，会预装dockerd，但是预装的dockerd能不能用我不知道
