### ISSUE TITLE
在线升级出现这个问题是什么情况？

### ISSUE THREAD

**Issue by chwl66** [klever1988/nanopi-openwrt#796]
![image](https://user-images.githubusercontent.com/58024471/130025258-f39ad31e-7282-4a03-adb3-de6340e4bfd0.png)
搜索了下，没找到是什么原因，有大佬知道是啥原因吗？

**Comment by klever1988** [comment]
wget -qO- https://github.com/klever1988/nanopi-openwrt/raw/master/scripts/autoupdate.sh | sh

**Comment by chwl66** [comment]
> wget -qO- https://github.com/klever1988/nanopi-openwrt/raw/master/scripts/autoupdate.sh | sh

wget -qO- https://github.com/klever1988/nanopi-openwrt/raw/master/scripts/autoupdate.sh | ver=-with-docker sh 我的加了版本以后就提示那个错误，不加能升级。原来加了版本是可以升级的。

**Comment by klever1988** [comment]
wget提示缺少参数， 你应该是输入了全角或者汉字的符号了吧

**Comment by chwl66** [comment]
> wget提示缺少参数， 你应该是输入了全角或者汉字的符号了吧

重新手打了一遍，可以升级了，谢谢大佬
