### ISSUE TITLE
能否添加对docker的支持

### ISSUE THREAD

**Issue by zhhuabj** [klever1988/nanopi-openwrt#80]
如题

**Comment by klever1988** [comment]
fork项目 修改app_config.seed加入docker就可以的

**Comment by zhhuabj** [comment]
好的, 我试试加下面的配置之后再看能否安装https://download.docker.com/linux/static/stable/aarch64/docker-19.03.8.tgz, 
多谢.

CONFIG_KERNEL_PERF_EVENTS=y
CONFIG_KERNEL_PROC_PID_CPUSET=y
CONFIG_KERNEL_MEMCG_SWAP=y
CONFIG_KERNEL_CGROUP_PERF=y
CONFIG_KERNEL_NAMESPACES=y
CONFIG_KERNEL_UTS_NS=y                                       
CONFIG_KERNEL_IPC_NS=y                                       
CONFIG_KERNEL_USER_NS=y                                      
CONFIG_KERNEL_PID_NS=y                                       
CONFIG_KERNEL_NET_NS=y
