### ISSUE TITLE
R2C WAN不工作

### ISSUE THREAD

**Issue by OTLeon** [klever1988/nanopi-openwrt#800]
使用官方提供的FriendlyWRT两个网口都能够正常工作，但是release下的R2C和R2S的WAN口都无法正常工作（无亮灯），LAN口能够正常使用。

**Comment by gsown** [comment]
确实是用不了，从dmesg信息看，驱动加载的还是RTL8211E的
[   28.581170] rk_gmac-dwmac ff540000.ethernet eth0: PHY [stmmac-0:01] driver [RTL8211E Gigabit Ethernet]
[   28.687604] rk_gmac-dwmac ff540000.ethernet: Failed to reset the dma
[   28.688207] rk_gmac-dwmac ff540000.ethernet eth0: stmmac_hw_setup: DMA engine initialization failed
[   28.689011] rk_gmac-dwmac ff540000.ethernet eth0: stmmac_open: Hw setup failed

**Comment by klever1988** [comment]
@thomaswcy

**Comment by klever1988** [comment]
我的错 智障了

**Comment by klever1988** [comment]
@gsown @OTLeon 再试试

**Comment by gsown** [comment]
@klever1988 正常了 感谢

**Comment by OTLeon** [comment]
@klever1988 谢谢，已经正常了
