### ISSUE TITLE
R2S lean固件在“状态”->“概况”页面下CPU一直占用率20%以上，其他页面没有问题

### ISSUE THREAD

**Issue by lernb** [klever1988/nanopi-openwrt#81]
![image](https://user-images.githubusercontent.com/23007808/77668145-fd749700-6fbd-11ea-9d61-48ece80c9c2f.jpeg)

**Comment by klever1988** [comment]
这个很正常，因为这个页面是一个是脚本一直在输出动态数据，需要占用很大的cpu时间

**Comment by liuenrong** [comment]
> 这个很正常，因为这个页面是一个是脚本一直在输出动态数据，需要占用很大的cpu时间

谢谢回复，就是这个CPU占用有点太高

**Comment by klever1988** [comment]
https://github.com/coolsnowwolf/lede/commit/b2ca31e6b0de42d3b009044edab69dbc7e111967

大雕今天对首页数据生成逻辑做了修改，静待今天的版本看看有没有降低

**Comment by liuenrong** [comment]
> https://github.com/coolsnowwolf/lede/commit/b2ca31e6b0de42d3b009044edab69dbc7e111967
> 
> 
> 
> 大雕今天对首页数据生成逻辑做了修改，静待今天的版本看看有没有降低

OK

**Comment by lernb** [comment]
> [coolsnowwolf/lede@b2ca31e](https://github.com/coolsnowwolf/lede/commit/b2ca31e6b0de42d3b009044edab69dbc7e111967)
> 
> 大雕今天对首页数据生成逻辑做了修改，静待今天的版本看看有没有降低

之前刚看到今天自动发布的版本，现在看没了，还没下载

**Comment by lernb** [comment]
> https://github.com/coolsnowwolf/lede/commit/b2ca31e6b0de42d3b009044edab69dbc7e111967
> 
> 
> 
> 大雕今天对首页数据生成逻辑做了修改，静待今天的版本看看有没有降低

试了27号版的，概况页面CPU占用情况，最低的时候比之前低，最高的比之前高，netdata监控显示总体还是在20%以上

**Comment by klever1988** [comment]
那木有办法 习惯就好

**Comment by klever1988** [comment]
![image](https://user-images.githubusercontent.com/56048681/77823252-92999c00-7134-11ea-9473-ce7ee2cca618.png)
我觉得还好啊 minimal一直是3-5%的占用

**Comment by lernb** [comment]
> ![image](https://user-images.githubusercontent.com/56048681/77823252-92999c00-7134-11ea-9473-ce7ee2cca618.png)
> 
> 我觉得还好啊 minimal一直是3-5%的占用

Lean版“概况”页面今天的版本是百分之几、百分之三十几的跳，netdata上看就是一直在百分之二十几的浮动

**Comment by klever1988** [comment]
进ssh用top命令看看

**Comment by lernb** [comment]
> 进ssh用top命令看看

![image](https://user-images.githubusercontent.com/23007808/77840536-480f3280-71bb-11ea-96f4-22729f6a1212.png)
已经刷了28号版的lean固件，情况好很多了，现在一直在百分之十以下，netdata上看是百分之十左右。不过一开始占用都是在二十以上，ssh进去top看是图中的一直占用25%左右
