### ISSUE TITLE
r2s lean固件无法使用pppoe拨号上网

### ISSUE THREAD

**Issue by NathanDai** [klever1988/nanopi-openwrt#82]
格式化刷入最新系统 使用dhcp上网正常 使用pppoe上网无法连接到网络

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by klever1988** [comment]
你有其他运行op的设备吗？
其他op系统是否可以拨号？
某些拨号环境需要设置vlan？
https://www.right.com.cn/forum/thread-215774-1-1.html

**Comment by NathanDai** [comment]
解决了

**Comment by klever1988** [comment]
> 解决了

解决也分享一下解决办法- -  方便别人搜索啊

**Comment by lovemei2u4ever** [comment]
前些日子我也遇到这种问题，修改/etc/config/network文件，在wan口配置一个mac地址就解决了
