### ISSUE TITLE
桥接模式带宽减半

### ISSUE THREAD

**Issue by mynameiscaa** [klever1988/nanopi-openwrt#825]
家里1k兆宽带，光猫为华为hn8145v，光猫路由模式有线连电脑能到930M+，硬路由桥接拨号有线接电脑也有900+，用r4s桥接拨号只有500多？不知道哪里出问题了？

**Comment by klever1988** [comment]
看看启动了哪些插件，逐一关闭插件看看谁对速度产生影响
