### ISSUE TITLE
0901 r2s ddns中没有了阿里云

### ISSUE THREAD

**Issue by junzhewenming** [klever1988/nanopi-openwrt#830]
![image](https://user-images.githubusercontent.com/23341115/131768974-fbf34819-fd5f-410b-9017-9c458792e618.png)

**Comment by klever1988** [comment]
已添加

**Comment by junzhewenming** [comment]
> 已添加

这两天的新版本还是没有诶。是我打开的方式不对么？

**Comment by klever1988** [comment]
> > 已添加
> 
> 这两天的新版本还是没有诶。是我打开的方式不对么？

抱歉 确实是失误了  下一版会加上
