### ISSUE TITLE
r2s 0903 更新后

### ISSUE THREAD

**Issue by iamfuhui** [klever1988/nanopi-openwrt#833]
通过命令更新了0903 r2s胖版后
status/overview
概览 
<html>
<body>

CPU 信息 | ?
-- | --

</body>
</html>

adgurad home 错误

> download success start copy
start copy
awk: /etc/AdGuardHome.yaml: No such file or directory
uci: I/O error
sed: can't create temp file '/etc/hostsXXXXXX': Read-only file system
/usr/share/AdGuardHome/addhost.sh: line 31: can't create /etc/hosts: Read-only file system
/usr/share/AdGuardHome/addhost.sh: line 32: can't create /etc/hosts: Read-only file system
AdGuardHome service disabled
Command failed: Not found
rm: can't remove '/usr/bin/AdGuardHome': Read-only file system
mv: can't remove '/usr/bin/AdGuardHome': Read-only file system
mv failed maybe not enough space please use upx or change bin to /tmp/AdGuardHome

**Comment by klever1988** [comment]
内存卡的文件系统坏掉了  拔卡冲刷吧~

**Comment by iamfuhui** [comment]
已重刷。
