### ISSUE TITLE
DHCP/DNS里面怎么没有域名重定向了？

### ISSUE THREAD

**Issue by Mac0ne16** [klever1988/nanopi-openwrt#834]
DHCP/DNS里面怎么没有域名重定向了，需要将NTP域名劫持到国内IP上。什么鬼？

**Comment by klever1988** [comment]
![image](https://user-images.githubusercontent.com/56048681/132080841-fa33de80-52e7-4e27-b5b9-4a40cb945434.png)

**Comment by Mac0ne16** [comment]
原来是这样的，好吧这个说明完全没看懂的说。
