### ISSUE TITLE
patches.sh里这段代码失效了，上游无此三文件

### ISSUE THREAD

**Issue by DeborahCox** [klever1988/nanopi-openwrt#837]
### nanopi-openwrt/patches.sh里这段代码失效了，上游无此三文件

`#bring the ethinfo back`
`if [ $DEVICE != 'r1s' ]; then`
`cd package/emortal/autocore/files/x86`
`cp rpcd_luci rpcd_10_system.js rpcd_luci-mod-status.json ../arm`
`cd -`

> cp: cannot stat 'rpcd_luci': No such file or directory

> cp: cannot stat 'rpcd_10_system.js': No such file or directory

> cp: cannot stat 'rpcd_luci-mod-status.json': No such file or directory

**Comment by klever1988** [comment]
都还在

你要自己生成固件不用改yml脚本啊 你改了才出错的
