### ISSUE TITLE
菜单部分点击展开后，不能再次点击折叠

### ISSUE THREAD

**Issue by yukkuna** [klever1988/nanopi-openwrt#839]
状态、系统、服务那些点击展开后不能再次点击折叠，这是bug嘛...还是版本就是这样的？

**Comment by klever1988** [comment]
是的bug  argon作者没对snapshot的luci仔细做适配的 所以用起来感觉残残的 等他吧~

**Comment by yukkuna** [comment]
> 是的bug argon作者没对snapshot的luci仔细做适配的 所以用起来感觉残残的 等他吧~

好的~感谢大佬解惑
