### ISSUE TITLE
SSR Plus无法自动启动，OpenVPN服务端无法连接，WAN和LAN灯不亮。

### ISSUE THREAD

**Issue by Felix-Bao** [klever1988/nanopi-openwrt#84]
版本：自动发布 R2S-Lean-2020-03-26
问题：SSR Plus开机后无法自动启动。
           OpenVPN服务端开启后，用户无法连接。确认过端口已开启，配置文件五错误。
           WAN和LAN灯不亮。

**Comment by klever1988** [comment]
你的op应该是有内核模块启动的时候没加载成功
去看看系统日志吧
