### ISSUE TITLE
x86-slim使用内置后台上传固件升级后，无法扩充软件包空间

### ISSUE THREAD

**Issue by str0078** [klever1988/nanopi-openwrt#841]
目前r2s在线升级一次后，可以自动扩容，然而X86-slim的版本无法在线升级只能手动，但是软件包空间始终不能扩充，请问有什么办法？

**Comment by klever1988** [comment]
如果你固件跑在u盘上 可以把u盘拔下来插到运行linux上快速扩容
如果跑在内部sata硬盘里 那还是算了 openwrt ext4无法在线扩容

**Comment by str0078** [comment]
> 如果你固件跑在u盘上 可以把u盘拔下来插到运行linux上快速扩容
> 如果跑在内部sata硬盘里 那还是算了 openwrt ext4无法在线扩容

我的是在群晖VMM虚拟机里面运行的，请问这种也是无法修改吗？

**Comment by klever1988** [comment]
当然可以 这样很方便啊 你直接在群晖操作vmm的磁盘映像就可以了

**Comment by str0078** [comment]
已解决，参考https://www.moewah.com/archives/4719.html

**Comment by klever1988** [comment]
他那方法不好  你可以在群晖里把op关机 然后直接扩展它的根分区

**Comment by str0078** [comment]
我用的第二个方法，在群晖vmm里面再添加一个虚拟盘，然后在op里面挂载，之后运行ssh命令重启

如果有更好的，希望有详细说明
