### ISSUE TITLE
r2s在刷了固件之后不能通过HTTP或者SSH访问

### ISSUE THREAD

**Issue by RitterHou** [klever1988/nanopi-openwrt#845]
r2s刷完了固件之后把r2s的wan口连到路由器的lan口上面，电脑通过无线连到路由器之后使用路由器通过dhcp给r2s分配的ip地址访问r2s，发现既不能通过ssh访问也不能通过http访问，请问下这是什么原因呢？此前的版本是可以的，这次我打算更新一下固件就重新刷了最新版本的固件，然后就不可以了。希望能够帮助解答一下，谢谢！！！

**Comment by RitterHou** [comment]
电脑都没有RJ45接口连不了网线😂，不过还是感谢帮助！

**Comment by RitterHou** [comment]
去楼下买了个USB转RJ45的转接器把问题解决了，悟空牛逼！！！

**Comment by klever1988** [comment]
我不是悟空 :sweat_smile:

**Comment by RitterHou** [comment]
啊这！！！我一直弄错了这个repository的主人了啊😥😥😥抱歉😭😭😭！！！K神牛逼！！！（破音）🥳🥳🥳

**Comment by klever1988** [comment]
没事的
