### ISSUE TITLE
wan口灯不亮，无法联网......

### ISSUE THREAD

**Issue by kklod** [klever1988/nanopi-openwrt#862]
固件版本：2021.09.17    R2S
连上猫后，WAN口没有反应-_-||
有相同问题的吗？

**Comment by calkchu** [comment]
我估计你是下错固件了，可能看错了下成了r2c版本的吧，我之前下错了刷好以后就这个情况

**Comment by kklod** [comment]
> 我估计你是下错固件了，可能看错了下成了r2c版本的吧，我之前下错了刷好以后就这个情况

我确认了一下，下载的是“r2s-with-docker”，没错啊

**Comment by kklod** [comment]
> > 我估计你是下错固件了，可能看错了下成了r2c版本的吧，我之前下错了刷好以后就这个情况
> 
> 我确认了一下，下载的是“r2s-with-docker”，没错啊

你是对的，我买的机子居然是 R2C，我搞错了  😅
