### ISSUE TITLE
最新版本是换主题了么

### ISSUE THREAD

**Issue by 412999826** [klever1988/nanopi-openwrt#866]
比较喜欢原来的主题，感觉特别好看，自己怎么更换主题啊？

**Comment by QPass** [comment]
系统-系统-语言和界面-主题-Argon

**Comment by 412999826** [comment]
> 系统-系统-语言和界面-主题-Argon
但是好像只能换背景和调颜色吧，整个主题怎么改啊

**Comment by symantes** [comment]
我也很喜欢原来主题，不过改成 BOOTSTRAP 后感觉比原来主题还要漂亮
