### ISSUE TITLE
添加两个包

### ISSUE THREAD

**Issue by L1cardo** [klever1988/nanopi-openwrt#870]
希望可以默认添加这两个插件
```
luci-lib-json.
luci-mod-rpc.
```

在玩home assistant时，如果想要追踪连入openwrt的设备时，这两个是必装的，但是每次用脚本更新，这两个都需要重新安装。
希望作者能默认包含，就几kb的文件，对其他人不会有影响的

**Comment by klever1988** [comment]
加咯

**Comment by L1cardo** [comment]
> 加咯

感谢感谢！
