### ISSUE TITLE
这主题也太粗糙了吧 Edit：原来主题可以改啊...

### ISSUE THREAD

**Issue by NianyiYang** [klever1988/nanopi-openwrt#874]
新入坑，随便点了几下，发现页面里还有 HTML 标签露出...据说原先的主题还好看点？

---

我看到了，在系统更新里可以选主题的...瞎眼了

**Comment by 412999826** [comment]
怎么系统更新改啊？

**Comment by 412999826** [comment]
> 怎么系统更新改啊？

我也看到了…..我傻了…..还是argon好看
