### ISSUE TITLE
0326版minimal固件防火墙多次配置会失效

### ISSUE THREAD

**Issue by lovemei2u4ever** [klever1988/nanopi-openwrt#88]
0326版minimal固件防火墙多次配置会失效，可复现

路由器使用pppoe拨号获得公网ip，配置动态dns，进防火墙添加2条端口转发，继续添加并保存应用时会卡住。
再次点击防火墙-端口转发会看到已保存完成，但转发规则并没有生效。

**Comment by klever1988** [comment]
重启会生效吗

**Comment by lovemei2u4ever** [comment]
重启后再看会发现刚刚添加的记录消失了

**Comment by klever1988** [comment]
我刚刚试了同时添加2条转发规则 没有死机 也重启了 没有发现问题 

不过我没有配置ddns 也没有用来拨号

等刷今天的27版本试试吧

**Comment by lovemei2u4ever** [comment]
刚刚更新了，没问题了，谢谢，打扰了
