### ISSUE TITLE
状态概览报错，求大神帮忙看看原因

### ISSUE THREAD

**Issue by lfdfxl** [klever1988/nanopi-openwrt#883]
SyntaxError
Unexpected identifier
  in http://192.168.123.1/luci-static/resources/view/status/include/10_system.js?v=2.2.4:?
  at http://192.168.123.1/luci-static/resources/luci.js?v=git-21.273.05721-4244f3b:181:29

![image](https://user-images.githubusercontent.com/23272518/135745744-4a60cb94-ecae-4bea-8d29-1836b5973820.png)
重新登录、清理缓存和重启设备都无法解决。

**Comment by mengxinz** [comment]
我还以为是我一个人出问题，害得我把数据全清了

**Comment by mengxinz** [comment]
问题好像是从2号的版本开始的

**Comment by klever1988** [comment]
修复了 等编译出固件试试

**Comment by mengxinz** [comment]
> 修复了 等编译出固件试试

测试没问题了

**Comment by yukkuna** [comment]
> > 修复了 等编译出固件试试
> 
> 测试没问题了

啊 我用argon主题还是会报错诶 openwrt2020不会

**Comment by mengxinz** [comment]
> > > 修复了 等编译出固件试试
> > 
> > 
> > 测试没问题了
> 
> 啊 我用argon主题还是会报错诶 openwrt2020不会



> > > 修复了 等编译出固件试试
> > 
> > 
> > 测试没问题了
> 
> 啊 我用argon主题还是会报错诶 openwrt2020不会

我是slim版完全没问题

**Comment by lfdfxl** [comment]
> 修复了 等编译出固件试试

感谢大佬。
