### ISSUE TITLE
R2s 实时监控（netdata)插件问题-21.10.06

### ISSUE THREAD

**Issue by WilsonXu0512** [klever1988/nanopi-openwrt#885]
实时监控（netdata)插件，卡刷完成之后的全新系统是可以正常显示的，但是一旦恢复备份设置后，就无法正常显示，如下图：
![无标题](https://user-images.githubusercontent.com/80147765/136159645-a4fa0302-9643-4bfd-ad3d-15a4803962f8.png)

设备：R2S，
固件版本：r2s.img.gz-10.06
固件刷入方式：卡刷，卡刷前备份旧配置并在卡刷后导入恢复

已知：出现问题后，使用在线升级（重刷）无效，依然无法正确显示

**Comment by klever1988** [comment]
我也没见过  
从备份包里删除netdata相干内容再还原试试

**Comment by WilsonXu0512** [comment]
> 我也没见过 从备份包里删除netdata相干内容再还原试试

似乎是被汉化包里的一个缓存污染了……清空netdata的缓存就好了，搞了一下午，哭

**Comment by WilsonXu0512** [comment]
> > 我也没见过 从备份包里删除netdata相干内容再还原试试
> 
不好意思，问题似乎没有解决。
从备份包里删除netdata相关内容  →  试过了，无效，
清空netdata的缓存文件（路径：/var/cache/netdata）→  可以使用IP:19999的方式正常访问了， 但是菜单：“系统：实时监控”里，还是图上老样子
