### ISSUE TITLE
能否即将SSH链接客户端的插件编译进固件？现在用FinalShell连接后看不见文件。

### ISSUE THREAD

**Issue by swingpon** [klever1988/nanopi-openwrt#890]
能否即将SSH链接客户端的插件编译进固件？现在用FinalShell连接后看不见文件。

**Comment by swingpon** [comment]
> 什么插件？ finashell提示缺少了什么插件

用第三方的SSH可以连接，但是就是无法加载OPENWRT里的文件，永远显示加载

**Comment by klever1988** [comment]
这个问题已从上游修复了
