### ISSUE TITLE
大神 能在 R1S-Lienol 中增加adbyby-plus编译吗

### ISSUE THREAD

**Issue by GeekerXu** [klever1988/nanopi-openwrt#9]
大神 能在 R1S-Lienol 中增加adbyby-plus编译吗，想用passwall，但是没有去除广告。

**Comment by klever1988** [comment]
要adbyby-plus还是adguardhome  貌似第二个也挺受欢迎的

**Comment by GeekerXu** [comment]
adbyby-plus主要是屏蔽广告，原理不清楚，但是感觉比adguardhome厉害清理的干净。adguardhome是通过域名方式屏蔽的广告，除此之外还能优化dns。要是可以，两个可以都上。另外您看看方便集成frpc，家里没有公网ip，只能用这个做内网穿越。感谢大神

**Comment by klever1988** [comment]
ok 明天更新推出

**Comment by GeekerXu** [comment]
拜谢！！！

**Comment by xpliu1016** [comment]
r2s也加入adguardhome可以吗
