### ISSUE TITLE
多级路由上网问题

### ISSUE THREAD

**Issue by zia123-ai** [klever1988/nanopi-openwrt#90]
刚才连上用了就一会儿就又不行了，就是LAN口接LAN口

**Comment by klever1988** [comment]
这些 软路由使用的基础知识 还是去恩山讨论吧  因为这个东西跟设备跟固件的关系不大。。。

**Comment by zia123-ai** [comment]
> 这些 软路由使用的基础知识 还是去恩山讨论吧 因为这个东西跟设备跟固件的关系不大。。。

好的好的。。😂
