### ISSUE TITLE
重启失效问题

### ISSUE THREAD

**Issue by ni7ht** [klever1988/nanopi-openwrt#923]
R2S初始版本2021-10-08发现重启功能及自动重启后直接关机了，没办法启动。
2021-10-30版本更新完发现还是一样，用的闪迪的A1灰卡32G，大佬有空看下。

**Comment by klever1988** [comment]
应该就是卡的问题 我用京东或者天猫的垃圾卡都还好

**Comment by ni7ht** [comment]
> 应该就是卡的问题 我用京东或者天猫的垃圾卡都还好

换了卡，正常啦，感谢回复。
