### ISSUE TITLE
openconnect 速度非常慢

### ISSUE THREAD

**Issue by tomzhu1024** [klever1988/nanopi-openwrt#928]
使用 openconnect 连接服务器后测速发现带宽只有下行 20M 上行 5M，测试其他固件没有发现这个情况，猜测是固件编译时少了协议或者硬件加速的支持库。

**Comment by klever1988** [comment]
应该不是 看看测试带宽时的资源占用

**Comment by tomzhu1024** [comment]
通过 netdata 来看，测试带宽时资源占用很少，CPU 在 10% 左右，磁盘读写基本为零，机器是 R4S。

**Comment by klever1988** [comment]
那只能从配置上找原因了
