### ISSUE TITLE
更换主题失败

### ISSUE THREAD

**Issue by ks0998-5431** [klever1988/nanopi-openwrt#929]
最新11.3的包跟新后，主题显示是Argon，实际是imm那个，更改并保存其他主题后，主题没有变化，右上角仍然显示未保存的配置

**Comment by ks0998-5431** [comment]
补充一下，测试了别的插件，配置也改变不了，保存并应用后，右上角依然显示未保存配置，重启后，还是老配置

**Comment by klever1988** [comment]
你的卡坏了吧 dmesg看看文件系统是不是变成只读的

**Comment by mengxinz** [comment]
> 补充一下，测试了别的插件，配置也改变不了，保存并应用后，右上角依然显示未保存配置，重启后，还是老配置

系统坏了，重刷吧
