### ISSUE TITLE
SSR+微信走代理怎么解决呀

### ISSUE THREAD

**Issue by mynameiscaa** [klever1988/nanopi-openwrt#935]
![123](https://user-images.githubusercontent.com/41559238/141387285-c33318da-2c15-46bf-8523-11f3eb068304.jpg)

ssr+怎么解决微信走代理呀 访问控制里添加了不走代理的域名还是没用

**Comment by klever1988** [comment]
你用什么模式？另外这个是什么介面？

**Comment by mynameiscaa** [comment]
![3FE5049C-F52C-4A26-A3CE-2650B33C4D71](https://user-images.githubusercontent.com/41559238/141496666-b4a66b2c-efcd-459d-bd6a-9034e7c010aa.png)
刚刚我试了一下又好了 😅抱歉
