### ISSUE TITLE
更新固件后出现系统中的系统菜单出现RPCError

### ISSUE THREAD

**Issue by yellowjal** [klever1988/nanopi-openwrt#937]
![image](https://user-images.githubusercontent.com/19889343/141662567-e65bb82d-41b9-40a2-b788-d5c80ecfb960.png)
11月14日，在线更新固件，更新后主题回到默认。然后我手动重新把主题改回Argon然后就出现上面的错误。请帮忙看看。谢谢！

**Comment by yellowjal** [comment]
试了一下，发现就是Argon主题的问题，不选这个主题就没事。希望大佬能够修复。谢谢！

**Comment by macvip** [comment]
目前装的slim版，用的就是这个Argon主题，没发现类似问题。会不会是哪个插件冲突呢？

**Comment by yellowjal** [comment]
我用的是常规版本，不是slim版。10月28日的版本没有问题，11月7日后我试了好几个版本都不行。
