### ISSUE TITLE
2.5G usb 网卡是不是一直没有支持？

### ISSUE THREAD

**Issue by macvip** [klever1988/nanopi-openwrt#939]
试用了11月9日的版本，用的是 kmod-usb-net-rtl8152-vendor 这个驱动，也试用了更早的 kmod-usb-net-rtl8152 驱动，结果网卡能正常识别，但就是无法稳定通信。
vendor 那个驱动，只要不开大量的 udp 请求，比如打开爱奇艺app看视频，就可以用。如果有大量udp请求，br-lan 就挂掉了，局域网就断了，也打不开192.168.2.1后台。这时，把网线从 2.5G 网卡上拔下来，插到R4S 自带的 LAN 口，局域网就能够恢复，能打开192.168.2.1后台了，也能上网了。
没有 vendor 那个，根本不行，如果插着 2.5G 网卡的网线启动，直接就挂了，R4S 有时都启动不了。
希望有用过 2.5G usb 网卡的同学来说说，用的什么版本的固件。非常感谢。

**Comment by klever1988** [comment]
更新了一下 用新版再试试

**Comment by macvip** [comment]
已解决，非常感谢
