### ISSUE TITLE
R2S-Minimal版的LAN口的MAC地址总是变成WAN口的MAC地址

### ISSUE THREAD

**Issue by gd82324976** [klever1988/nanopi-openwrt#95]
前面的版本没试过，但是27号和28号的版本都有这个问题，刚刷完，进入web界面的网络接口查看，此时LAN口和WAN口的的MAC地址是不一样的，什么也不动，重启后LAN口的MAC地址就变成和WAN口的一样了。

我的连接方式：光猫千兆口(已改为桥接) -> R2S WAN口 / R2S LAN口 -> 路由器WAN口

**Comment by klever1988** [comment]
我也发现了 这是内核原因 很早的版本也这样的
