### ISSUE TITLE
上电前，插入usb网卡cf811ac网卡会导致红灯一直闪烁

### ISSUE THREAD

**Issue by Erohal** [klever1988/nanopi-openwrt#955]
Nanopi R2S，带风扇，用的卡是C10的闪迪。
如果不接cf811ac网卡，开机是没问题的，反之，则一直闪烁。

开机后插入cf811ac网卡，再去配置wifi，也会导致死机。

请问大佬，有什么解决办法吗？

**Comment by Erohal** [comment]
据说是上游的问题，大佬也没有办法呀，好无奈。

**Comment by Erohal** [comment]
> 我用r4s 也是这个情况

我用了小朋友的固件，没有发现这个问题，工作良好。大概是内核版本的问题？

**Comment by wjybing** [comment]
> > 我用r4s 也是这个情况
> 
> 我用了小朋友的固件，没有发现这个问题，工作良好。大概是内核版本的问题？

能给我一个镜像么？我用的是r4s wifi是cf811ac，thx

**Comment by Erohal** [comment]
> > > 我用r4s 也是这个情况
> > 
> > 我用了小朋友的固件，没有发现这个问题，工作良好。大概是内核版本的问题？
> 
> 能给我一个镜像么？我用的是r4s wifi是cf811ac，thx

https://github.com/DHDAXCW/NanoPi-R4S-2021
这个是r4s的，你试试行不行。

**Comment by Erohal** [comment]
骷髅头的镜像挺稳定的，小朋友的会概率性重启失败。

**Comment by Erohal** [comment]
> > 骷髅头的镜像挺稳定的，小朋友的会概率性重启失败。
> 
> 下载了，12月2日的，能用，ac下149信道，20hz。通了，但是改了个ssid 找不到了，估计还得重刷。谢谢了。

更改配置之后要重启！
