### ISSUE TITLE
希望更新下内核版本

### ISSUE THREAD

**Issue by gili-gili** [klever1988/nanopi-openwrt#975]
目前版本是5.4.162，有点老了导致一些东西装不上，希望能更新到5.10左右

**Comment by klever1988** [comment]
啥玩意装不了

**Comment by gili-gili** [comment]
> 啥玩意装不了

SQM，就是QoS，依赖装不上，至少要5.10，有办法自行升级吗

**Comment by klever1988** [comment]
用slim是可以装的吧

**Comment by gili-gili** [comment]
> 用slim是可以装的吧

不行，试过了，依赖要求要5.10，你看报错信息

已安装的软件包 kernel 版本不兼容，需要 5.10.83-1-dd3e905a… 而 5.4.162-1-545c66e6… 已安装。

要咋装啊......

**Comment by klever1988** [comment]
可以的呀
![IMG_20211214_233925](https://user-images.githubusercontent.com/56048681/146030137-56ebd95c-12b2-44fa-83f8-3718a103939d.jpg)
![IMG_20211214_233936](https://user-images.githubusercontent.com/56048681/146030143-25b11933-6d19-4109-b19c-52114dde7bbe.jpg)

**Comment by gili-gili** [comment]
![F96DEED1-7205-46D4-BB0E-FC747D6F8692](https://user-images.githubusercontent.com/53759426/146170033-412d8f5b-7ba6-4464-b24d-a0b8ec29ff34.png)
我下的是最新的镜像啊......奇了怪了

**Comment by gili-gili** [comment]
> 可以的呀

你那个镜像内核版本是多少啊......

**Comment by klever1988** [comment]
![image](https://user-images.githubusercontent.com/56048681/146200492-24729762-9f2b-488a-8e56-9449b70bf971.png)

**Comment by klever1988** [comment]
> > 可以的呀
> 
> 你那个镜像内核版本是多少啊......

你是启用了软件源里的http源吧，看看你下面这个地方的配置内容
![image](https://user-images.githubusercontent.com/56048681/146200724-a74aec93-1de4-4da9-949a-1f84409ce642.png)

**Comment by gili-gili** [comment]
> 你是启用了软件源里的http源吧，看看你下面这个地方的配置内容 ![image]
对的我启用了......
所以说不能使用在线的，只能用本地的？

**Comment by klever1988** [comment]
使用在线软件源的内核模块是无法兼容的
即使是你自己编译的固件
因为在线内核模块的编译生成摘要，每次编译都会不一样
即使内核版本一样，也会因为摘要不同，而提示不兼容

**Comment by gili-gili** [comment]
> 使用在线软件源的内核模块是无法兼容的
> 即使是你自己编译的固件
> 因为内核模块的编译生成摘要，每次编译都会不一样
> 即使内核版本一样，也会因为摘要不同，而提示不兼容

懂了谢谢
