### ISSUE TITLE
能否增加Netgear A6210 无线网卡驱动

### ISSUE THREAD

**Issue by rxchen** [klever1988/nanopi-openwrt#98]
A6210是双频wifi，性能不错，可惜插上去没反应，倒是能识别出来这个网卡，就是驱动不起来。
管理界面直接看不到接口，也没有无线网络这个设置页面。

**Comment by klever1988** [comment]
来这儿，https://github.com/friendlyarm/friendlywrt_device_rk3328/issues

跟友善公司讲，让他们从内核层面加入驱动

**Comment by rxchen** [comment]
多谢，已经发了，不知道会不会有回应~

**Comment by klever1988** [comment]
难啊 他们要卖网卡的
