### ISSUE TITLE
r4s DNS转发的设置，设置好了后会无故消失

### ISSUE THREAD

**Issue by junanc** [klever1988/nanopi-openwrt#982]
使用的版本是 r4s 标准版本  无docker
 
我在网络设置dns里面设置了dns转发，刚设置好没有问题，但是使用一会就会自动消失，设置好的dns转发就消失了 ， 最近几个版本的我都测试了 都有这个情况 之前11月的版本就没有这个情况    不知道是什么原因，求大佬修复下

很奇怪 设置好了后保存了的， 然后可以生效。然后点击其他选项在点回来也都有，退出在进入查看也还在
 但是过一会就自动消失了。设置的就没了。 

这个是设置好了dns端口的时候
<img width="1196" alt="iShot2021-12-18 00 09 07" src="https://user-images.githubusercontent.com/44342736/146574518-46496d20-ec38-46d5-9e5e-967c0097638b.png">

这个是使用了一会就会自动消失后的情况
<img width="1268" alt="iShot2021-12-18 00 10 03" src="https://user-images.githubusercontent.com/44342736/146574578-782227ab-5325-49cb-9d3a-ccc2a2bd3eb1.png">

**Comment by klever1988** [comment]
被其他插件改写了设置的

**Comment by gili-gili** [comment]
看你这个端口号，是不是装了ChinaDNS
建议不要用5353,会有奇怪的冲突问题

**Comment by junanc** [comment]
> 被其他插件改写了设置的

没有使用其他插件，就只使用了 ShadowSocksR Plus+  和 AdGuard Home 

AdGuard Home 的端口设置的5353  我一直都是这样使用的  之前的版本也都是这样设置的 没有出现问题过 就最近的几个版本才开始出现这个问题的


ShadowSocksR Plus+ 设置
<img width="951" alt="iShot2021-12-19 16 20 09" src="https://user-images.githubusercontent.com/44342736/146668461-bd3c50a9-c211-44aa-aa06-24fb7ec1b298.png">


AdGuard Home 设置
<img width="1086" alt="iShot2021-12-19 16 20 29" src="https://user-images.githubusercontent.com/44342736/146668471-6c1a3623-0850-4391-b097-dcedc2717269.png">

**Comment by gili-gili** [comment]
> 没有使用其他插件，就只使用了 ShadowSocksR Plus+ 和 AdGuard Home
> 
> AdGuard Home 的端口设置的5353 我一直都是这样使用的 之前的版本也都是这样设置的 没有出现问题过 就最近的几个版本才开始出现这个问题的

建议备份下设置，重装AdGuard，不要用5353端口，5300或者5350啥的都行（之前我也遇到过，换个端口马上就好了）。AdGuard重定向模式选择后会自己配置DNS转发，不用手动设置

**Comment by gili-gili** [comment]
你可以试试这条命令来看看端口到底有没有占用
netstat -tunlp | grep 5353

**Comment by junanc** [comment]
> 你可以试试这条命令来看看端口到底有没有占用 netstat -tunlp | grep 5353

没有被其他程序占用

<img width="911" alt="截屏2021-12-19 19 53 17" src="https://user-images.githubusercontent.com/44342736/146673919-475e726c-4a79-4b34-93e3-6a67981b6289.png">

**Comment by junanc** [comment]
> > 没有使用其他插件，就只使用了 ShadowSocksR Plus+ 和 AdGuard Home
> > AdGuard Home 的端口设置的5353 我一直都是这样使用的 之前的版本也都是这样设置的 没有出现问题过 就最近的几个版本才开始出现这个问题的
> 
> 建议备份下设置，重装AdGuard，不要用5353端口，5300或者5350啥的都行（之前我也遇到过，换个端口马上就好了）。AdGuard重定向模式选择后会自己配置DNS转发，不用手动设置

我试一下换个端口， 
AdGuard重定向模式选择后会自己配置DNS转发， 这个就是他自己设置好的  就是没有了我才手动重新加上去或者把AdGuard关闭在开启一下 就会又自动加上了。

**Comment by Ra2-IFV** [comment]
> 我试一下换个端口， AdGuard重定向模式选择后会自己配置DNS转发， 这个就是他自己设置好的 就是没有了我才手动重新加上去或者把AdGuard关闭在开启一下 就会又自动加上了。

在AdGuard配置文件内改端口，可以在luci界面第三个选项卡改，不是改dnsmasq那个
