### ISSUE TITLE
passwall xray tcp xtls 10Mbps 解决方法

### ISSUE THREAD

**Issue by xtccc** [klever1988/nanopi-openwrt#985]
R2s passwall xray tcp xtls 10Mbps 解决方法

我是 高大全 版本(ImmortalWrt SNAPSHOT r21084-483a4981cd) ， passwall 国外速度  只有10Mbps，  把“高级设置“的 “TCP转发端口“ 设置为所有端口 我的国外速度就正常了 ， 是
## 修改前

![10Mbps](https://user-images.githubusercontent.com/37169212/146671126-bfc5c97b-fa3e-4992-bb07-1ba93f65249a.PNG)

## 修改后
![200Mbps](https://user-images.githubusercontent.com/37169212/146671131-bdae7969-ab04-4b21-b0eb-d56a3c7b0bd0.PNG)

**Comment by klever1988** [comment]
这是因为speedtest测速走的不是常用的80/443端口，而是8080

**Comment by xtccc** [comment]
哦 ， 学习了
