### ISSUE TITLE
minimal固件，UnblockNeteaseMusic 运行不起来，一直是未运行的状态

### ISSUE THREAD

**Issue by 15416769** [klever1988/nanopi-openwrt#99]
minimal固件，UnblockNeteaseMusic 运行不起来，一直是未运行的状态。

固件版本 | OpenWrt R20.3.19 / LuCI Master (git-20.088.29068-cebe120) built by DYC

**Comment by klever1988** [comment]
![image](https://user-images.githubusercontent.com/56048681/77864959-6417e000-725e-11ea-9f62-914043f5b741.png)
![image](https://user-images.githubusercontent.com/56048681/77864965-709c3880-725e-11ea-81a8-a4fed98547d1.png)

能启动，不能启动格式化tf卡重刷
