### ISSUE TITLE
在线脚本更新的问题

### ISSUE THREAD

**Issue by AbsurdYu** [klever1988/nanopi-openwrt#993]
看release最新的是1228的，后面没有自动发布（或者自动发布没成功？）。最近想用脚本升级发现脚本只会检查今天的，今天没有固件就检查昨天的，但是这两天都没固件就直接跳出了，想问下这个地方能否优化下，多谢。

**Comment by wei0908** [comment]
> 

那就再等一天,一般不会超过3-4天.

**Comment by klever1988** [comment]
README启用了新的更新命令了，试试吧

**Comment by AbsurdYu** [comment]
> > 
> 
> 那就再等一天,一般不会超过3-4天.

嗯嗯 是的


> README启用了新的更新命令了，试试吧

好的
