### ISSUE TITLE
R2S 升级到 2022-01-08 无法开机，网线灯也不亮

### ISSUE THREAD

**Issue by palemoky** [klever1988/nanopi-openwrt#999]
我从 2021-12-06 在线升级的，升级完等了十分钟都没有网，断电重启后就无法开机了，请问只能刷机了吗？

**Comment by palemoky** [comment]
直接裸刷 8 号的也无法进入后台，7 号的可以进入后台，上传备份后也是无法启动

**Comment by mengxinz** [comment]
> 直接裸刷 8 号的也无法进入后台，7 号的可以进入后台，上传备份后也是无法启动

你是不是用了无线网卡

**Comment by palemoky** [comment]
> > 直接裸刷 8 号的也无法进入后台，7 号的可以进入后台，上传备份后也是无法启动
> 
> 你是不是用了无线网卡

什么无线网卡？我用网线连接的 R2S 登陆的，最后还是刷了 12 月 6 号的，用备份恢复了，以后没啥毛病我就不折腾了，太花时间了:(

**Comment by zhangguanzhang** [comment]
`touch /etc/opkg`
执行下这个命令看看报错不

**Comment by palemoky** [comment]
> `touch /etc/opkg` 执行下这个命令看看报错不

我登陆不了后台，这个命令无法执行吧？
